<a href="https://colab.research.google.com/github/Jonchyk/Datamgmt/blob/main/Capstone_Workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Set Up

In [244]:
#---------------------------SETUP----------------------------------
#get useful libraries
import time, os, sys, re #basics
import zipfile, json, datetime, string   #string for annotating points in scatter
import numpy as np #basic math
# Install tabula-py using pip
!pip install tabula-py
# Import the correct module
from tabula import read_pdf
import statsmodels.api as sm
from statsmodels.formula.api import ols

!pip install pyreadstat


import matplotlib.pyplot as plt #import pylab as plt #apparently discouraged now:
 #https://stackoverflow.com/questions/11469336/what-is-the-difference-between-pylab-and-pyplot
 #https://www.tutorialspoint.com/matplotlib/matplotlib_pylab_module.htm

import pandas as pd
import pandas_datareader as pdr
from pandas_datareader import wb
from pandas.io.formats.style import Styler
#s4 = Styler(df4, uuid_len=0, cell_ids=False)

import urllib  #weird, guess need to have os and pandas imported for this to work  %TODO/LATER ditch it, its weird anyway, just use wget/curl

from google.colab import files

#import webbrowser

import seaborn as sns

from google.colab import data_table
data_table.enable_dataframe_formatter() #this enables spreadsheet view upon calling dataframe (without() )

#many tricks how to extend notebook functionality
#https://coderzcolumn.com/tutorials/python/list-of-useful-magic-commands-in-jupyter-notebook-lab
#will display all output not just last command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#MAGICS and THEMES/STYLES: important! does affect not just shading/colors, but also fonts, spacing, etc
#(even if you only select default (v not selecting anything) [but does seem to work better if you do make explicit sleections])

###magics: https://ipython.readthedocs.io/en/stable/interactive/magics.html
#most essential setup for vis: it does affect vis! careful!! stick with inline, maybe notebook; others mostly for non-notebook, eg spyder environ
#https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html recomends *inline*!
#show current one:
#%matplotlib
#%matplotlib --list
#interactive plots:
#%matplotlib notebook
#static images of your plot:
%matplotlib inline
#may play with this one and other magics (btw default is probably agg)
#%matplotlib nbagg
##https://www.marktechpost.com/2023/10/20/6-magic-commands-for-jupyter-notebooks-in-python-data-science/
#%%latex
#%ai
#%run
#%writefile
#%history -n

###themes/styles: https://matplotlib.org/stable/gallery/style_sheets/style_sheets_reference.html
#https://jakevdp.github.io/PythonDataScienceHandbook/04.11-settings-and-stylesheets.html
#https://matplotlib.org/stable/tutorials/introductory/customizing.html
#here more about art and style than under the hood functionality as with magics, explore and experiment
#many may find 'default' or seaborn ones more pleasing; my fav 'classic' is back from 90s ;)
#plt.style.available #list available styles :) may install more
#plt.style.use('default') # more delicate subtle than classic
plt.style.use('classic')  #  'seaborn-whitegrid' 'seaborn-white' 'seaborn-poster'
# btw: magics v theme/style sequence matters, eg if i specify classic style before inline magic, i wouldnt get grey bounding box im getting

#sometimes have to install library which you get from https://pypi.org/
#!pip install geopandas

Requirement already satisfied: tabula-py in /usr/local/lib/python3.11/dist-packages (2.10.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Requirement already satisfied: pyreadstat in /usr/local/lib/python3.11/dist-packages (1.2.8)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from pyreadstat) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.17.0)

In [245]:
import plotly.express as px
from statsmodels.stats.multicomp import pairwise_tukeyhsd

#Datasets

##Ministry of Science and Education Report - Population and Ethnic Demographics by Region
Report accessed here, table with population information summarized and rebuilt using Tabula. All data is from 2022

 https://stat.gov.kg/media/publicationarchive/fa3392ca-c76e-456f-badd-7a324ff5204d.pdf

In [246]:
!wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn" -O moesreport.pdf

--2025-03-29 18:28:06--  https://drive.google.com/uc?export=download&id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn
Resolving drive.google.com (drive.google.com)... 74.125.126.102, 74.125.126.139, 74.125.126.113, ...
Connecting to drive.google.com (drive.google.com)|74.125.126.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn&export=download [following]
--2025-03-29 18:28:06--  https://drive.usercontent.google.com/download?id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 209.85.145.132, 2607:f8b0:4001:c10::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|209.85.145.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1484754 (1.4M) [application/octet-stream]
Saving to: ‘moesreport.pdf’

moesreport.pdf      100%[===================>]   1.42M  --.-KB/s    in 0.03s

2025-03-29 18:28:10 (42.7 MB/s) - ‘moesreport.pdf’ saved [1484754/1484754]

## Early Grade Reading Assessment Data

Early Grade Reading Assessment: received with permission from employer, RTI.
Dataset can be accessed at: data.usaid.gov

This is a dataset from the Okuu Keremet! Program's 2021 Baseline study. It has a wealth of information, ranging from G2 teacher, head teacher, and librarian interviews, classroom observations, math results, and early grade reading results. For the purpose of my capstone study, I will be using this dataset, cleaned and targeting specifically the EGRA subtasks: Oral Reading, Oral Reading Comprehension, Invented Word Reading,  Silent Reading Comprehension, and listening comprehension.

In [247]:
# let's load the data set - this is the EGRA file
!wget --no-check-certificate 'https://docs.google.com/spreadsheets/d/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU/export?format=csv' -O Datareading.csv

--2025-03-29 18:28:10--  https://docs.google.com/spreadsheets/d/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU/export?format=csv
Resolving docs.google.com (docs.google.com)... 142.250.125.101, 142.250.125.138, 142.250.125.100, ...
Connecting to docs.google.com (docs.google.com)|142.250.125.101|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://doc-0c-7s-sheets.googleusercontent.com/export/54bogvaave6cua4cdnls17ksc4/kmv24g109ml9voitcknph39cao/1743272890000/113781219181981321798/*/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU?format=csv [following]
Warning: wildcards not supported in HTTP.
--2025-03-29 18:28:10--  https://doc-0c-7s-sheets.googleusercontent.com/export/54bogvaave6cua4cdnls17ksc4/kmv24g109ml9voitcknph39cao/1743272890000/113781219181981321798/*/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU?format=csv
Resolving doc-0c-7s-sheets.googleusercontent.com (doc-0c-7s-sheets.googleusercontent.com)... 173.194.193.132, 2607:f8b0:4001:c0f::84
Connecting to doc-0c-7s-sheets.googleusercontent.com (doc-0c-7s-sheets.googleusercontent.com)|173.194.193.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘Datareading.csv’

Datareading.csv         [      <=>           ]  29.92M  26.1MB/s    in 1.1s

2025-03-29 18:28:19 (26.1 MB/s) - ‘Datareading.csv’ saved [31368932]

In [248]:
egra = pd.read_csv('Datareading.csv')#let's take a look at this
egra.describe()
pd.set_option('display.max_columns', None)

<ipython-input-248-afdb31daaa64>:1: DtypeWarning:

Columns (15,18,19,20,21,22,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,44,45,46,50,52,58,59,60,67,69,70,71,80,90,95,96,100,101,102,104,108,109,110,115,121,128,132,133,134,136,137,138,139,140,141,146,147,148,152,155,156,157,158,159,167,168,176,178,179,185,192,200,201,212,219,220,229,230,241,242,243,245,253,254,263,267,268,269,271,276,277,278,280,281,290,291,292,293,294,300,301,305,306,307,311,312,313,314,315,323,324,326,327,328,333,337,338,391,392,393,396,397,452,453,454,455,456,457,458,459,460,461,462,463,464,465,468,469,475,476,478,479,485,486,488,489,500,501,503,504,510,511,513,514,520,521,523,524,533,535,549,551,555,559,563,565,567,569,571,572,573,574,575,576,582,583,584,585,586,587,588,592,593,604,605,608,610,624,626,629,630,631,632,633,634,637,638,639,640,642,643,644,645,647,648,649,650,652,653,654,655,660,661,662,663,664,665,667,670,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748) have mixed types. Specify dtype option on import or set low_memory=False.

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
count,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5199.0,5275,5275,5275,5275,5275,5265,4730,5199.0,5199.0,5275,1,5275,5275,5275,5275,5275,5275,5265,5175.0,5275,5105,5105,5105,5105,5105,5105,5105,5069,5069,5105,5105.0,5105,411,5095,5095,5095,5095,5095,5095,5095,821,5079,5079,5079,5079,5079,5079,2450.0,5079,5079,5079,776,5059,5059,5059,5059,5059,5059,5059,5059,5059,731,5059,5059,5059,5059,5059,5059,5059,5059,5059,5059,5059,5059,5059,3599,5105.0,5105,5105,5105,5105.0,5105.0,5105.0,5275,5275,4587,4587,4587,4081.0,4081.0,4081.0,4587,4587,4587,4587,2230.0,4587,4587,4587,4587,4587,4587,4587,4587,4587,4587,4587,4587,4587.0,4587,4587,4587,4587.0,4587.0,4587.0,5275,5275,5275,5275,5275,5275,5275,5160,5160,5160,5160,4670.0,4670.0,4670.0,5160,5160,5160,1,5160,5160,2473,2473,2473,2473,2473.0,5160,5160,5160,5160,5160,5160,5160,5130,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160.0,5160,5160,5160,5160,5160,5160.0,582,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160.0,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,5160,703,5160,5160,5160,5160,5160,5160,5160,715,5150,5150,5150,5150,5150,5150,5150,5150,5150.0,5150,119,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,311,5150,30,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5150,5160,5160,5160,5160,5160.0,5160,5160.0,5275,5275,5111,5111,5111,5111,4688.0,4688.0,4688.0,5111,5111.0,5111.0,5111,5111,5111,5111,5111,5111,5111,5111,5111.0,5111.0,5111.0,5111.0,5111,5111,5111,5111,5111,5111,848,5111.0,5111,5111,5111,5111.0,5111.0,5111.0,5275,5275,5275,5275,5275,5275,5275,5275,5271,5271,5271,5271,5271,5271,5271,5271.0,5271.0,5271,5271.0,5271.0,5275,5275,5275,5275,5275,5275,5275,5219,5275,5271.0,5268.0,5271,5271,5271,5265,5258,5250,5232,5130,5101,5081,5038,5000,4938,4874,4822,4762,4689,4615,4517,4434,4349,4245,4131,4015,3898,3750,3607,3450,3339,3200,3056,2925,2743,2592,2455,2276,2153,2002,1877,1718,1563,1433,1303,1210,1135,1024,948,861,804,748,684,618,5271.0,5271.0,5271.0,5271,5271,5271.0,5271.0,5271,5267,5261,5248,5219,5192,5173,5142,5109,5075,5026,4989,4958,4912,4871,4836,4785,4728,4670,4602,4521,4442,4354,4260,4187,4087,4014,3961,3870,3799,3709,3648,3581,3523,3382,3315,3226,3150,3076,2929,2784,2696,2624,2575,2491,2409,2330,2280,2244,2204,2128,2089,2040,1240,1076,1032,16,16,16,16,15,14,14,13,11,5271.0,5271.0,5271.0,5271,5271,5271.0,5271.0,5068,4516,3616,2889,1932,5271.0,5271.0,5271,5271.0,5271.0,5271,5271,5271,5271,5270,5271.0,5271.0,5271,5271.0,5271.0,5275,5275,5275,5275,5082,5017,4825,4634,4316,4207,5275,5275,5275,5275,5275,5275,5275,5275,5275,5044,5275,5275,5275,5275,5275,5275,5275,5275,5275,4771,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5235,5113,4915,4953,4699,4227,5062,5275,4835,5275,5275,5275,4535,5275,5273,5273,4518,5273.0,5273,5273,3825,5273.0,5273,5273.0,5272,5272.0,5272,5272.0,5151,5272.0,5271.0,5271.0,5271.0,5271.0,5271.0,5271,5271,5271,5271,5271,5271,5271.0,5271,5271,5271,36,9,5271,5271,5271,5271,5271,5271,5271,53,5271,5271,5271,5271,5271,5271,5271,4776,5271,5271,5271,5271,5271,194,5271,5271,5271,5271,5271,5271,5271,5271,5271,5271,5271,5271,5271,5271,5271,111,5271,2401,1,1,1,1,1,1,5275,5275,5275,5219.0,5275,5275,5275,5275,5266.0,5275,5275,5275,5275,5192.0,5275,5275,5275,5275,5273.0,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,5268,5271.0,5271,5275,5275,5268,2630.0,2620,2620,2620,2620,2620,2620,2620,2620,2620,2620,2620,356,1,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,2358,762,1034.0,273.0,2678,2678,2678,2678,2678,2678,2678,11.0,2678.0,2678.0,2678,2678,2678,2678,2678,2678,2678,2678,2678,11.0,2678.0,2678,2678,2678,2678,282,2542.0,253,2542.0,259.0,1199,31,31,31,31,31,31,31,1,1,1,1,1214.0,5275
unique,10,54,233,5,5,3,9,233,3,9,3,3,3,3,552,9,2,3,21,12.0,9,19,17,3,212,21,4,20.0,20.0,2,1,9,9,268,9,212,199,21,22.0,5,516,514,301,40,550,550,320,44,39,2,5.0,3,25,8,3,3,3,3,4,4,84,3,3,3,3,3,3,3.0,3,4,4,77,3,3,3,3,3,3,3,3,4,75,4,7,4,4,4,4,4,4,6,4,7,33,304,6,4.0,33,33,7,5.0,41.0,47.0,3,5,463,469,40,11.0,21.0,116.0,2,3,4,3,40.0,3,3,3,3,3,4,8,8,4,9,282,298,4.0,32,32,7,5.0,41.0,36.0,3,12,59,13,6,56,5,525,519,312,40,11.0,21.0,125.0,2,3,5,1,7,7,3,4,4,6,6.0,8,3,3,3,3,3,3,4,4,3,7,4,4,4,4,4,6,4,6,5.0,3,3,3,3,3,4.0,58,3,3,3,3,3,4,3,3,3,3,3,3,3,4,3.0,4,8,3,4,4,4,4,4,4,4,6,72,3,3,3,3,3,4,4,69,4,4,4,4,4,4,4,5,5.0,8,13,4,4,4,4,4,4,4,4,5,5,32,8,4,3,3,3,3,3,3,3,4,4,5,3,4,3,4,3,4,314,4,33,33,7,5.0,41,55.0,3,5,525,514,336,40,11.0,21.0,110.0,5,55.0,57.0,3,3,3,3,3,3,3,3,3.0,137.0,120.0,69.0,100,3,3,3,5,325,9,4.0,33,33,7,5.0,41.0,30.0,3,2,286,20,20,71,64,3,3,3,4,4,4,4,4,13.0,13.0,3,3.0,13.0,4,3,33,5275,3,12,3994,4074,2,167.0,248.0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,103.0,88.0,103.0,3,3,101.0,145.0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,3,121.0,90.0,177.0,3,3,118.0,132.0,4,4,4,4,4,13.0,13.0,3,13.0,23.0,4,4,4,4,4,13.0,13.0,3,4.0,13.0,4,4,4,4,4,4,4,4,4,4,23,23,3,15,44,4,4,4,4,4,13,13,3,5,13,4,4,4,4,4,13,13,3,5,13,578,91,4582,4581,928,5,6,4,9,6,6,5,6,4,5,6,4,3,3,3,3,3,3,3,64,3,87,6,4,3,103,6,4,3,67.0,6,4,3,147.0,3,27.0,3,25.0,3,41.0,3,20.0,3.0,3.0,3.0,4.0,3.0,4,4,6,3,3,4,4.0,4,4,4,22,8,3,3,3,4,4,3,3,50,3,3,3,3,3,3,3,3,4,3,3,4,3,155,4,4,7,4,3,3,3,3,3,3,3,3,3,4,8,68,573,3,1,1,1,1,1,1,33,7,41,184.0,15,15,3,15,27.0,13,13,3,13,23.0,11,11,3,8,14.0,70,70,3,2,3,5275,64,26,202,14,3,194,3,6.0,5,3,4,3,6.0,4,3,6,4,6,4,4,4,4,4,6,15,1,4,4,4,4,6,3,4,8,9,4,4,4,4,4,4,6,6,7,2.0,2.0,3,4,4,4,4,4,4,2.0,6.0,3.0,8,9,4,3,4,4,4,4,4,2.0,3.0,6,9,9,4,7,4.0,4,4.0,4.0,18,2,3,3,2,3,4,2,1,1,1,1,3.0,13

In [249]:
#let's check what we have. I know there's baseline and endline data here. We want just the baseline data, prior to program interventions
egra['g2_year'].value_counts()

g2_year
2024                      2692
2021                      1559
2021                      1023
Grade 2 Read/Math Year       1
Name: count, dtype: int64

In [250]:
#Strange. I have two identical values for 2021. what's up?
egra['g2_year'].apply(type)
egra['g2_year'].dtypes

#Looks like I have strings and integers...I want to convery this all to string

0       <class 'str'>
1       <class 'str'>
2       <class 'str'>
3       <class 'str'>
4       <class 'str'>
            ...
5270    <class 'int'>
5271    <class 'int'>
5272    <class 'int'>
5273    <class 'int'>
5274    <class 'int'>
Name: g2_year, Length: 5275, dtype: object

dtype('O')

In [251]:
#let's see if we can convert all our "2021"'s to a string so its the same value
egra['g2_year'] = egra['g2_year'].apply(lambda x: '2021' if str(x) == '2021' else x)

In [252]:
#let's run it again, looks like it worked!
egra['g2_year'].value_counts()

g2_year
2024                      2692
2021                      2582
Grade 2 Read/Math Year       1
Name: count, dtype: int64

In [253]:
#now I can finally filter to the data I want.
base = egra[egra['g2_year'] == '2021']

In [254]:
base.count()
#bingo!

region                     2582
district                   2582
school_code                2582
language                   2582
language_name              2582
                           ...
invent_worditem_at_time       0
oral_readitem_at_time         0
sil_readitem_at_time          0
userprofileitem1female        0
strata1                    2582
Length: 750, dtype: int64

In [255]:
base.groupby('region').size()

#Breakdown by region, and by group within the baseline study of 2500 observations.
#will need to rename this, but gives some nice quick insights as to what i'll be looking at for my roll up by region!

region
Баткенская        301
Жалал-Абадская    580
Иссык-Кульская    230
Нарынская          96
Ошская            437
Таласская         140
Чуйская           341
г. Бишкек         318
г. Ош             139
dtype: int64

In [256]:
base

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
1,Ошская,Араванский,1S32310502,Kyrgyz,Kyrgyz,Rural,KRU,СШ им.С.Шарипова,Control,KRU,Kyrgyz,Russian,Uzbek,No,1S32310502-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,28,1,Mixed,5,5,2nd,NaN,8883,8677,50,17560,28,22,1,1,1,4/28/21 2:30,4/28/21 2:41,08:30,IISIEVA,40.5202934,72.4959869,3.900000095,Исиева,Инабат,Yes,0,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,Other,0,"Менторства бар. Сабактарга катышуу,алдынкы иш ...",Lesson planning,Methods of teaching mathematics,0,0,0,Use of new information technologies in teaching,0,Additional training and use of training mater...,0,0,NaN,0,0,Library,Internet,Joint meeting of teachers,0,0,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,0,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a year,2021-04-28,08:41,0,2021,4/28/2021,4/28/2021,Wed,4,28,11,Matched (3),1,4/28/21 4:00,4/28/21 4:06,IISIEVA,41,72,4,Yes,Female,YES,YES,20,YES,0,0,3rd grade,4th grade,0,Once every six months,Once a year,YES,Once a week,10:06,10:00,2021,4/28/2021,4/28/2021,Wed,4,28,6,Matched (3),74,5,297,1,4,1,4/28/21 2:54,4/28/21 3:10,08:54,IISIEVA,41,72,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),16-25 years,No,999,999,999,999,Once a week,0,0,0,0,0,0,None of the above,0,No,999,999,999,999,999,999,999,999,999,999,0,Oral assessment,Observations during the lesson,0,0,0,NaN,To assess,0,To plan / change further learning,0,0,0,0,Count to 20,0,Addition and subtraction of simple numbers up...,0,0,Solving Problems from Simple Life,0,0,End of 2nd grade,2nd grade,No,999,999,999,999,999,999,999,999,NaN,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,0,0,0,0,Geometric figures,Visual aids,0,0,Every lesson,NaN,No,999,999,999,999,999,999,999,999,999,NaN,999,NaN,0,Textbook,0,0,Online resources,0,0,0,0,I will show the solution of the problem / problem,Elementary school students can solve new probl...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,09:10,2021,4/28/2021,4/28/2021,Wed,4,28,16,In Both,1,4/28/21 4:14,4/28/21 4:21,10:14,IISIEVA,41,72,6,Kyrgyz,12,16,Blackboard,Chalk or whiteboard marker,0,0,Notebook,0,0,0,0,37,12,0,2,Yes,No,Yes,Row,10:21,NaN,2021,4/28/2021,4/28/2021,Wed,4,28,6,In Both,2nd,1S32310502-Kyr_2,1,1,5,4,1,No,No,Correct,888,Incorrect,Incorrect,888,1,20,Proportion > 0 Correct,5,20,2021,April,4/28/2021,MXGYEW,Female,8,4/28/21 4:08,4/28/21 4:34,Yes,0,3,No,No,Incorrect,Incorrect,Incorrect,Incorrect,Incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0,Proportion = 0 Correct,Yes,5,0,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,5,Proportion > 0 Correct,No,9,33,NaN,NaN,NaN,NaN,NaN,0,0,Proportion = 0 Correct,0,0,Correct,No Answer,Incorrect,No Answer,No Answer,1,20,Proportion > 0 Correct,5,20,Incorrect,Correct,Incorrect,Correct,Incorrect,No Answer,Incorrect,Correct,Incorrect,Incorrect,3,30,Proportion > 0 Correct,10,30,Correct,Correct,Correct,Incorrect,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Incorrect,Incorrect,3,60,Proportion > 0 Correct,5,60,10:08,MUHAMMET,40.5201917,72.4956256,7.504000187,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,1,In the mind / mouth (the student is thinking o...,0,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,In writing,Issued the report in column form (for example ...,No,Correct,Incorrect,Correct,NaN,Incorrect,Correct,Correct,999,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,48,Answers in a different way (I just liked it),No,Incorrect,18,Answers in a different way (I just liked it),No,Incorrect,87,Correct,999,Correct,999,Incorrect,8,Incorrect,4,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,Uzbek,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,2-3 times a week,Yes,TV,0,0,Toilet inside the house,Smartphone,0,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,10:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/28/2021,Wed,28,26,3,50,Score>0,5,60,2,40,Score>0,5,40,2,50,Score>0,4,50,17,49,No,Matched (3),Female,MXGYEW,16,3,15,8314,1,16,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz
2,г. Ош,г. Ош,013RTICODE,Kyrgyz,Kyrgyz,Urban,KR,№2 К. Маркса,Control,KR,Kyrgyz,Russian,No,No,013RTICODE-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,37,1,Mixed,7,3,2nd,NaN,8883,8677,81,17560,37,44,1,1,1,4/22/21 4:51,4/22/21 4:59,10:51,JTOKTOSHEVA,40.5064858,72.8229702,7.074999809,Мамасадыковна,Жамила,Yes,1,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,0,0,NaN,0,0,Methods of teaching literature,0,0,0,0,0,Other,0,Каллиграфии б ча кайрылышат,0,0,Library,Internet,0,0,School administration,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,Teachers started to apply new strategies for ...,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a quarter,2021-04-22,10:59,0,2021,4/22/2021,4/22/2021,Thu,4,22,9,Matched (3),1,4/22/21 5:40,4/22/21 5:43,JTOKTOSHEVA,41,73,7,Yes,Female,YES,YES,40,YES,1st grade,2nd grade,3rd grade,4th grade,0,Once a week,Once a month,YES,Once a month,11:43,11:40,2021,4/22/2021,4/22/2021,Thu,4,22,3,Matched (3),74,3,297,1,3,1,4/22/21 5:18,4/22/21 5:35,11:18,JTOKTOSHEVA,41,73,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),9-15 years,No,999,999,999,999,Once a month,Improving lesson plans,New strategies for teaching mathematics,New strategies for teaching literature,0,0,0,0,0,No,999,999,999,999,999,999,999,999,999,999,Written tests,Oral assessment,Observations during the lesson,Homework,0,0,NaN,To assess,To assess the student's mastery of the subject,0,Feedback to the student,0,0,Count to 10,0,0,0,0,0,0,0,0,End of 3rd grade,2nd grade,Yes,0,Literary reading competitions and festivals,0,0,0,0,Other,0,Энелердин майрамы,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,Counting sticks,0,0,Geometric board,Geometric figures,Visual aids,0,0,Every lesson,NaN,Yes,0,Children's books,Visual aids,0,0,Didactic materials,0,0,0,NaN,Twice a week,NaN,0,Textbook,Information literature,Guidelines for teachers,Online resources,Lesson plans for other teachers,0,0,0,I will explain the new topic,Primary school students should always be shown...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,11:35,2021,4/22/2021,4/22/2021,Thu,4,22,17,In Both,1,4/22/21 4:36,4/22/21 4:40,10:36,JTOKTOSHEVA,41,73,5,Kyrgyz,15,20,Blackboard,Chalk or whiteboard marker,0,Pencil or pencil,Notebook,0,0,Lesson plan / lesson results,0,54,14,2,24,Yes,Yes,Yes,Row,10:40,NaN,2021,4/22/2021,4/22/2021,Thu,4,22,4,In Both,2nd,013RTICODE-Kyr_2,1,1,3,3,1,No,No,Correct,Correct,Incorrect,Incorrect,Incorrect,2,40,Proportion > 0 Correct,5,40,2021,April,4/22/2021,AQSAQP,Male,8,4/22/21 4:45,4/22/21 5:09,Yes,31,30,No,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,0,62,Proportion > 0 Correct,No,32,97,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,0,54,Proportion > 0 Correct,No,30,100,Correct,Correct,NaN,NaN,NaN,2,40,Proportion > 0 Correct,2,100,Correct,Correct,Incorrect,Correct,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,9,90,Proportion > 0 Correct,10,90,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,10:45,GDOSMATOVA,40.5065752,72.8232433,4.288000107,In writing,Issued the report in column form (for example ...,No,2,In the mind / mouth (the student is thinking o...,0,In writing,Divides numbers into components in some way,No,In writing,Issued the report in column form (for example ...,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,999,Correct,999,Reflected using numbers,No,Correct,999,Add / subtract numbers in the order given in t...,No,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,26,Correct,999,Correct,999,Correct,999,Correct,999,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,0,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,Once a week,Yes,TV,Bicycle,Car,Toilet inside the house,Smartphone,Computer,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,11:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,Thu,22,24,6,100,Score>0,6,100,4,80,Score>0,5,80,4,100,Score>0,4,100,33,94,Yes,Matched (3),Male,AQSAQP,15,3,9,8314,1,9,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz

##Cleaning Dataset for Regional Demographics

In [257]:
moes = read_pdf('moesreport.pdf', pages='19-20',multiple_tables=True, stream=True)

In [258]:
moes = pd.DataFrame(moes[1])

In [259]:
# Move column names into the first row
moes.loc[-1] = moes.columns  # Shift column names into row 0
moes.index = moes.index + 1  # Shift index to make space
moes = moes.sort_index().reset_index(drop=True)  # Reset index

# Rename the first column if necessary
moes = moes.rename(columns={moes.columns[0]: "Ethnicity"})

In [260]:
moes

,Ethnicity,7 037 590,570 898,1 311 007,538 384,308 348,1 460 425,273 509,1 068 702,1 145 044,361 273,Unnamed: 0
0,Total population,7 037 590,570 898,1 311 007,538 384,308 348,1 460 425,273 509,1 068 702,1 145 044,361 273,Unnamed: 0
1,including:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kyrgyz,5 470 806,451 422,967 355,492 452,307 095,1 003 764,260 038,798 347,975 128,215 205,Batken oblast
3,Russians,277 646,2 021,5 062,27 424,88,1 254,3 257,124 640,110 439,3 461,NaN
4,Uzbeks,995 454,78 314,321 461,3 463,291,421 519,1 006,17 480,15 899,136 021,Jalal-Abad
5,Ukrainians,3 257,10,88,147,-,14,55,1 715,1 199,29,oblast
6,Germans,2 747,2,55,85,6,1,143,1 768,671,16,NaN
7,Tatars,11 353,479,1 027,1 112,78,479,121,3 109,4 324,624,Issyk-Kul oblast
8,Kazakhs,28 389,317,898,5 976,190,823,2 141,10 554,7 176,314,NaN
9,Armenians,494,3,124,10,-,51,1,104,194,7,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Naryn oblast
11,Tajiks,60 752,36 921,7 153,213,23,8 626,53,5 208,1 743,812,NaN
12,Azerbaijanis,17 560,50,513,50,1,5 085,12,10 081,1 263,505,NaN
13,Chechens,1 116,21,34,6,-,64,20,766,201,4,Osh oblast
14,Belarusians,359,7,18,13,1,2,10,164,138,6,NaN
15,Georgians,154,6,34,2,-,1,8,38,65,-,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Talas oblast
17,Lithuanians,35,-,1,-,-,-,-,17,15,2,NaN
18,Moldovans,106,-,6,1,-,-,2,67,26,4,NaN
19,Latvians,33,-,-,-,-,-,-,15,18,-,Chui oblast
20,Turkmens,2 358,163,480,23,14,940,56,268,196,218,NaN
21,Estonians,26,1,-,2,-,-,-,13,10,-,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bishkek city
23,Jews,129,-,-,3,-,2,-,15,107,2,NaN
24,Uighurs,32 390,137,1 476,2 196,149,8 073,84,12 258,7 850,167,NaN
25,Dungan,67 268,11,17,3 161,368,580,31,59 922,3 149,29,Osh city
26,Koreans,5 935,28,68,48,-,21,28,1 465,4 219,58,NaN
27,Turks,22 397,733,2 980,34,9,8 549,901,6 796,1 865,530,NaN
28,people of india,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,and pakistan,8 271,2,411,328,2,2,9,809,3 806,2 902,NaN
30,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,nationalities,28 555,250,1 746,1 635,33,575,5 533,13 083,5 343,357,NaN

In [261]:
# Define new column names
new_column_names = {
    "Ethnicity": "Ethnicity",
    "7 037 590": "Total Population",
    "570 898": "Batken",
    "1 311 007": "Jalal-Abad",
    "538 384": "Issyk-Kul",
    "308 348": "Naryn",
    "1 460 425": "Osh",
    "273 509": "Talas",
    "1 068 702": "Chui",
    "1 145 044": "Bishkek",
    "361 273": "Osh city"
}

# Rename the columns in the DataFrame
moes = moes.rename(columns=new_column_names)

# Drop the "Unnamed: 0" column if it still exists
moes = moes.drop(columns=["Unnamed: 0"], errors="ignore")

# Display the updated DataFrame
moes

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Total population,7 037 590,570 898,1 311 007,538 384,308 348,1 460 425,273 509,1 068 702,1 145 044,361 273
1,including:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kyrgyz,5 470 806,451 422,967 355,492 452,307 095,1 003 764,260 038,798 347,975 128,215 205
3,Russians,277 646,2 021,5 062,27 424,88,1 254,3 257,124 640,110 439,3 461
4,Uzbeks,995 454,78 314,321 461,3 463,291,421 519,1 006,17 480,15 899,136 021
5,Ukrainians,3 257,10,88,147,-,14,55,1 715,1 199,29
6,Germans,2 747,2,55,85,6,1,143,1 768,671,16
7,Tatars,11 353,479,1 027,1 112,78,479,121,3 109,4 324,624
8,Kazakhs,28 389,317,898,5 976,190,823,2 141,10 554,7 176,314
9,Armenians,494,3,124,10,-,51,1,104,194,7
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Tajiks,60 752,36 921,7 153,213,23,8 626,53,5 208,1 743,812
12,Azerbaijanis,17 560,50,513,50,1,5 085,12,10 081,1 263,505
13,Chechens,1 116,21,34,6,-,64,20,766,201,4
14,Belarusians,359,7,18,13,1,2,10,164,138,6
15,Georgians,154,6,34,2,-,1,8,38,65,-
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Lithuanians,35,-,1,-,-,-,-,17,15,2
18,Moldovans,106,-,6,1,-,-,2,67,26,4
19,Latvians,33,-,-,-,-,-,-,15,18,-
20,Turkmens,2 358,163,480,23,14,940,56,268,196,218
21,Estonians,26,1,-,2,-,-,-,13,10,-
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Jews,129,-,-,3,-,2,-,15,107,2
24,Uighurs,32 390,137,1 476,2 196,149,8 073,84,12 258,7 850,167
25,Dungan,67 268,11,17,3 161,368,580,31,59 922,3 149,29
26,Koreans,5 935,28,68,48,-,21,28,1 465,4 219,58
27,Turks,22 397,733,2 980,34,9,8 549,901,6 796,1 865,530
28,people of india,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,and pakistan,8 271,2,411,328,2,2,9,809,3 806,2 902
30,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,nationalities,28 555,250,1 746,1 635,33,575,5 533,13 083,5 343,357

In [262]:
moes.drop([1,10,16,22,28,30], inplace=True)
# Define specific ethnicity name replacements
ethnicity_replacements = {
    "nationalities": "Other nationalities",
    "and pakistan": "Indian and Pakistani",
    # Add more replacements as needed
}

# Apply the replacements
moes["Ethnicity"] = moes["Ethnicity"].replace(ethnicity_replacements)

In [263]:
for col in moes.columns[1:]:  # Skip 'Ethnicity' column
    moes[col] = moes[col].astype(str).str.replace(" ", "").str.replace("-", "0") #replace '-' with 0 for missing values. you may want to use NaN instead
    moes[col] = pd.to_numeric(moes[col], errors='coerce').fillna(0).astype(int) # Convert to numeric, handle errors, fill NaN with 0, then to int

In [264]:
moes['Ethnicity'] = moes['Ethnicity'].str.replace('Total', 'Sum') #this will do it for any ethnicity with 'Total' in the name
moes

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,7037590,570898,1311007,538384,308348,1460425,273509,1068702,1145044,361273
2,Kyrgyz,5470806,451422,967355,492452,307095,1003764,260038,798347,975128,215205
3,Russians,277646,2021,5062,27424,88,1254,3257,124640,110439,3461
4,Uzbeks,995454,78314,321461,3463,291,421519,1006,17480,15899,136021
5,Ukrainians,3257,10,88,147,0,14,55,1715,1199,29
6,Germans,2747,2,55,85,6,1,143,1768,671,16
7,Tatars,11353,479,1027,1112,78,479,121,3109,4324,624
8,Kazakhs,28389,317,898,5976,190,823,2141,10554,7176,314
9,Armenians,494,3,124,10,0,51,1,104,194,7
11,Tajiks,60752,36921,7153,213,23,8626,53,5208,1743,812
12,Azerbaijanis,17560,50,513,50,1,5085,12,10081,1263,505
13,Chechens,1116,21,34,6,0,64,20,766,201,4
14,Belarusians,359,7,18,13,1,2,10,164,138,6
15,Georgians,154,6,34,2,0,1,8,38,65,0
17,Lithuanians,35,0,1,0,0,0,0,17,15,2
18,Moldovans,106,0,6,1,0,0,2,67,26,4
19,Latvians,33,0,0,0,0,0,0,15,18,0
20,Turkmens,2358,163,480,23,14,940,56,268,196,218
21,Estonians,26,1,0,2,0,0,0,13,10,0
23,Jews,129,0,0,3,0,2,0,15,107,2
24,Uighurs,32390,137,1476,2196,149,8073,84,12258,7850,167
25,Dungan,67268,11,17,3161,368,580,31,59922,3149,29
26,Koreans,5935,28,68,48,0,21,28,1465,4219,58
27,Turks,22397,733,2980,34,9,8549,901,6796,1865,530
29,Indian and Pakistani,8271,2,411,328,2,2,9,809,3806,2902
31,Other nationalities,28555,250,1746,1635,33,575,5533,13083,5343,357

In [265]:
regselect = ['Sum population','Kyrgyz','Russians','Uzbeks','Tajiks']
regethnics = moes[moes['Ethnicity'].isin(regselect)]

In [266]:
regethnics
#table to provide total population, filtered for the ethnicities of interest

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,7037590,570898,1311007,538384,308348,1460425,273509,1068702,1145044,361273
2,Kyrgyz,5470806,451422,967355,492452,307095,1003764,260038,798347,975128,215205
3,Russians,277646,2021,5062,27424,88,1254,3257,124640,110439,3461
4,Uzbeks,995454,78314,321461,3463,291,421519,1006,17480,15899,136021
11,Tajiks,60752,36921,7153,213,23,8626,53,5208,1743,812

In [267]:
regethnics = regethnics.applymap(lambda x: f"{x:,}" if isinstance(x, (int, float)) else x)
regethnics
#We are interested in the four target languages and groups by region, as well as total population

<ipython-input-267-5a03fe27d567>:1: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,"7,037,590","570,898","1,311,007","538,384","308,348","1,460,425","273,509","1,068,702","1,145,044","361,273"
2,Kyrgyz,"5,470,806","451,422","967,355","492,452","307,095","1,003,764","260,038","798,347","975,128","215,205"
3,Russians,"277,646","2,021","5,062","27,424",88,"1,254","3,257","124,640","110,439","3,461"
4,Uzbeks,"995,454","78,314","321,461","3,463",291,"421,519","1,006","17,480","15,899","136,021"
11,Tajiks,"60,752","36,921","7,153",213,23,"8,626",53,"5,208","1,743",812

Remaining is to download the report, remove the indexes, and add a title "Regional population breakout by region and demographics". This will then be transferred over to the appendix.

In [268]:
regethnics.to_csv('moesreport.csv')
files.download('moesreport.csv')

##Cleaning EGRA Dataset

In [269]:
base #Cleaning dataset
pd.set_option('display.max_columns', None)

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
1,Ошская,Араванский,1S32310502,Kyrgyz,Kyrgyz,Rural,KRU,СШ им.С.Шарипова,Control,KRU,Kyrgyz,Russian,Uzbek,No,1S32310502-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,28,1,Mixed,5,5,2nd,NaN,8883,8677,50,17560,28,22,1,1,1,4/28/21 2:30,4/28/21 2:41,08:30,IISIEVA,40.5202934,72.4959869,3.900000095,Исиева,Инабат,Yes,0,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,Other,0,"Менторства бар. Сабактарга катышуу,алдынкы иш ...",Lesson planning,Methods of teaching mathematics,0,0,0,Use of new information technologies in teaching,0,Additional training and use of training mater...,0,0,NaN,0,0,Library,Internet,Joint meeting of teachers,0,0,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,0,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a year,2021-04-28,08:41,0,2021,4/28/2021,4/28/2021,Wed,4,28,11,Matched (3),1,4/28/21 4:00,4/28/21 4:06,IISIEVA,41,72,4,Yes,Female,YES,YES,20,YES,0,0,3rd grade,4th grade,0,Once every six months,Once a year,YES,Once a week,10:06,10:00,2021,4/28/2021,4/28/2021,Wed,4,28,6,Matched (3),74,5,297,1,4,1,4/28/21 2:54,4/28/21 3:10,08:54,IISIEVA,41,72,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),16-25 years,No,999,999,999,999,Once a week,0,0,0,0,0,0,None of the above,0,No,999,999,999,999,999,999,999,999,999,999,0,Oral assessment,Observations during the lesson,0,0,0,NaN,To assess,0,To plan / change further learning,0,0,0,0,Count to 20,0,Addition and subtraction of simple numbers up...,0,0,Solving Problems from Simple Life,0,0,End of 2nd grade,2nd grade,No,999,999,999,999,999,999,999,999,NaN,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,0,0,0,0,Geometric figures,Visual aids,0,0,Every lesson,NaN,No,999,999,999,999,999,999,999,999,999,NaN,999,NaN,0,Textbook,0,0,Online resources,0,0,0,0,I will show the solution of the problem / problem,Elementary school students can solve new probl...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,09:10,2021,4/28/2021,4/28/2021,Wed,4,28,16,In Both,1,4/28/21 4:14,4/28/21 4:21,10:14,IISIEVA,41,72,6,Kyrgyz,12,16,Blackboard,Chalk or whiteboard marker,0,0,Notebook,0,0,0,0,37,12,0,2,Yes,No,Yes,Row,10:21,NaN,2021,4/28/2021,4/28/2021,Wed,4,28,6,In Both,2nd,1S32310502-Kyr_2,1,1,5,4,1,No,No,Correct,888,Incorrect,Incorrect,888,1,20,Proportion > 0 Correct,5,20,2021,April,4/28/2021,MXGYEW,Female,8,4/28/21 4:08,4/28/21 4:34,Yes,0,3,No,No,Incorrect,Incorrect,Incorrect,Incorrect,Incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0,Proportion = 0 Correct,Yes,5,0,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,5,Proportion > 0 Correct,No,9,33,NaN,NaN,NaN,NaN,NaN,0,0,Proportion = 0 Correct,0,0,Correct,No Answer,Incorrect,No Answer,No Answer,1,20,Proportion > 0 Correct,5,20,Incorrect,Correct,Incorrect,Correct,Incorrect,No Answer,Incorrect,Correct,Incorrect,Incorrect,3,30,Proportion > 0 Correct,10,30,Correct,Correct,Correct,Incorrect,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Incorrect,Incorrect,3,60,Proportion > 0 Correct,5,60,10:08,MUHAMMET,40.5201917,72.4956256,7.504000187,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,1,In the mind / mouth (the student is thinking o...,0,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,In writing,Issued the report in column form (for example ...,No,Correct,Incorrect,Correct,NaN,Incorrect,Correct,Correct,999,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,48,Answers in a different way (I just liked it),No,Incorrect,18,Answers in a different way (I just liked it),No,Incorrect,87,Correct,999,Correct,999,Incorrect,8,Incorrect,4,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,Uzbek,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,2-3 times a week,Yes,TV,0,0,Toilet inside the house,Smartphone,0,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,10:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/28/2021,Wed,28,26,3,50,Score>0,5,60,2,40,Score>0,5,40,2,50,Score>0,4,50,17,49,No,Matched (3),Female,MXGYEW,16,3,15,8314,1,16,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz
2,г. Ош,г. Ош,013RTICODE,Kyrgyz,Kyrgyz,Urban,KR,№2 К. Маркса,Control,KR,Kyrgyz,Russian,No,No,013RTICODE-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,37,1,Mixed,7,3,2nd,NaN,8883,8677,81,17560,37,44,1,1,1,4/22/21 4:51,4/22/21 4:59,10:51,JTOKTOSHEVA,40.5064858,72.8229702,7.074999809,Мамасадыковна,Жамила,Yes,1,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,0,0,NaN,0,0,Methods of teaching literature,0,0,0,0,0,Other,0,Каллиграфии б ча кайрылышат,0,0,Library,Internet,0,0,School administration,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,Teachers started to apply new strategies for ...,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a quarter,2021-04-22,10:59,0,2021,4/22/2021,4/22/2021,Thu,4,22,9,Matched (3),1,4/22/21 5:40,4/22/21 5:43,JTOKTOSHEVA,41,73,7,Yes,Female,YES,YES,40,YES,1st grade,2nd grade,3rd grade,4th grade,0,Once a week,Once a month,YES,Once a month,11:43,11:40,2021,4/22/2021,4/22/2021,Thu,4,22,3,Matched (3),74,3,297,1,3,1,4/22/21 5:18,4/22/21 5:35,11:18,JTOKTOSHEVA,41,73,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),9-15 years,No,999,999,999,999,Once a month,Improving lesson plans,New strategies for teaching mathematics,New strategies for teaching literature,0,0,0,0,0,No,999,999,999,999,999,999,999,999,999,999,Written tests,Oral assessment,Observations during the lesson,Homework,0,0,NaN,To assess,To assess the student's mastery of the subject,0,Feedback to the student,0,0,Count to 10,0,0,0,0,0,0,0,0,End of 3rd grade,2nd grade,Yes,0,Literary reading competitions and festivals,0,0,0,0,Other,0,Энелердин майрамы,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,Counting sticks,0,0,Geometric board,Geometric figures,Visual aids,0,0,Every lesson,NaN,Yes,0,Children's books,Visual aids,0,0,Didactic materials,0,0,0,NaN,Twice a week,NaN,0,Textbook,Information literature,Guidelines for teachers,Online resources,Lesson plans for other teachers,0,0,0,I will explain the new topic,Primary school students should always be shown...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,11:35,2021,4/22/2021,4/22/2021,Thu,4,22,17,In Both,1,4/22/21 4:36,4/22/21 4:40,10:36,JTOKTOSHEVA,41,73,5,Kyrgyz,15,20,Blackboard,Chalk or whiteboard marker,0,Pencil or pencil,Notebook,0,0,Lesson plan / lesson results,0,54,14,2,24,Yes,Yes,Yes,Row,10:40,NaN,2021,4/22/2021,4/22/2021,Thu,4,22,4,In Both,2nd,013RTICODE-Kyr_2,1,1,3,3,1,No,No,Correct,Correct,Incorrect,Incorrect,Incorrect,2,40,Proportion > 0 Correct,5,40,2021,April,4/22/2021,AQSAQP,Male,8,4/22/21 4:45,4/22/21 5:09,Yes,31,30,No,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,0,62,Proportion > 0 Correct,No,32,97,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,0,54,Proportion > 0 Correct,No,30,100,Correct,Correct,NaN,NaN,NaN,2,40,Proportion > 0 Correct,2,100,Correct,Correct,Incorrect,Correct,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,9,90,Proportion > 0 Correct,10,90,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,10:45,GDOSMATOVA,40.5065752,72.8232433,4.288000107,In writing,Issued the report in column form (for example ...,No,2,In the mind / mouth (the student is thinking o...,0,In writing,Divides numbers into components in some way,No,In writing,Issued the report in column form (for example ...,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,999,Correct,999,Reflected using numbers,No,Correct,999,Add / subtract numbers in the order given in t...,No,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,26,Correct,999,Correct,999,Correct,999,Correct,999,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,0,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,Once a week,Yes,TV,Bicycle,Car,Toilet inside the house,Smartphone,Computer,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,11:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,Thu,22,24,6,100,Score>0,6,100,4,80,Score>0,5,80,4,100,Score>0,4,100,33,94,Yes,Matched (3),Male,AQSAQP,15,3,9,8314,1,9,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz

In [271]:
#replace/map/recode
base['region'].replace({
    'Ошская': 'Osh',
    'г. Ош' : 'Osh_city',
    'Чуйская':'Chui',
    'Таласская':'Talas',
    'Иссык-Кульская':'Issyk-Kul',
    'г. Бишкек':'Bishkek',
    'Жалал-Абадская': 'Jalal-Abad',
    'Нарынская':'Naryn',
    'Баткенская':'Batken'}, inplace=True)
base.head(3)# names fixed,

<ipython-input-271-73aea0ebcfff>:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



<ipython-input-271-73aea0ebcfff>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
1,Osh,Араванский,1S32310502,Kyrgyz,Kyrgyz,Rural,KRU,СШ им.С.Шарипова,Control,KRU,Kyrgyz,Russian,Uzbek,No,1S32310502-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,28,1,Mixed,5,5,2nd,NaN,8883,8677,50,17560,28,22,1,1,1,4/28/21 2:30,4/28/21 2:41,08:30,IISIEVA,40.5202934,72.4959869,3.900000095,Исиева,Инабат,Yes,0,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,Other,0,"Менторства бар. Сабактарга катышуу,алдынкы иш ...",Lesson planning,Methods of teaching mathematics,0,0,0,Use of new information technologies in teaching,0,Additional training and use of training mater...,0,0,NaN,0,0,Library,Internet,Joint meeting of teachers,0,0,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,0,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a year,2021-04-28,08:41,0,2021,4/28/2021,4/28/2021,Wed,4,28,11,Matched (3),1,4/28/21 4:00,4/28/21 4:06,IISIEVA,41,72,4,Yes,Female,YES,YES,20,YES,0,0,3rd grade,4th grade,0,Once every six months,Once a year,YES,Once a week,10:06,10:00,2021,4/28/2021,4/28/2021,Wed,4,28,6,Matched (3),74,5,297,1,4,1,4/28/21 2:54,4/28/21 3:10,08:54,IISIEVA,41,72,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),16-25 years,No,999,999,999,999,Once a week,0,0,0,0,0,0,None of the above,0,No,999,999,999,999,999,999,999,999,999,999,0,Oral assessment,Observations during the lesson,0,0,0,NaN,To assess,0,To plan / change further learning,0,0,0,0,Count to 20,0,Addition and subtraction of simple numbers up...,0,0,Solving Problems from Simple Life,0,0,End of 2nd grade,2nd grade,No,999,999,999,999,999,999,999,999,NaN,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,0,0,0,0,Geometric figures,Visual aids,0,0,Every lesson,NaN,No,999,999,999,999,999,999,999,999,999,NaN,999,NaN,0,Textbook,0,0,Online resources,0,0,0,0,I will show the solution of the problem / problem,Elementary school students can solve new probl...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,09:10,2021,4/28/2021,4/28/2021,Wed,4,28,16,In Both,1,4/28/21 4:14,4/28/21 4:21,10:14,IISIEVA,41,72,6,Kyrgyz,12,16,Blackboard,Chalk or whiteboard marker,0,0,Notebook,0,0,0,0,37,12,0,2,Yes,No,Yes,Row,10:21,NaN,2021,4/28/2021,4/28/2021,Wed,4,28,6,In Both,2nd,1S32310502-Kyr_2,1,1,5,4,1,No,No,Correct,888,Incorrect,Incorrect,888,1,20,Proportion > 0 Correct,5,20,2021,April,4/28/2021,MXGYEW,Female,8,4/28/21 4:08,4/28/21 4:34,Yes,0,3,No,No,Incorrect,Incorrect,Incorrect,Incorrect,Incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0,Proportion = 0 Correct,Yes,5,0,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,5,Proportion > 0 Correct,No,9,33,NaN,NaN,NaN,NaN,NaN,0,0,Proportion = 0 Correct,0,0,Correct,No Answer,Incorrect,No Answer,No Answer,1,20,Proportion > 0 Correct,5,20,Incorrect,Correct,Incorrect,Correct,Incorrect,No Answer,Incorrect,Correct,Incorrect,Incorrect,3,30,Proportion > 0 Correct,10,30,Correct,Correct,Correct,Incorrect,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Incorrect,Incorrect,3,60,Proportion > 0 Correct,5,60,10:08,MUHAMMET,40.5201917,72.4956256,7.504000187,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,1,In the mind / mouth (the student is thinking o...,0,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,In writing,Issued the report in column form (for example ...,No,Correct,Incorrect,Correct,NaN,Incorrect,Correct,Correct,999,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,48,Answers in a different way (I just liked it),No,Incorrect,18,Answers in a different way (I just liked it),No,Incorrect,87,Correct,999,Correct,999,Incorrect,8,Incorrect,4,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,Uzbek,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,2-3 times a week,Yes,TV,0,0,Toilet inside the house,Smartphone,0,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,10:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/28/2021,Wed,28,26,3,50,Score>0,5,60,2,40,Score>0,5,40,2,50,Score>0,4,50,17,49,No,Matched (3),Female,MXGYEW,16,3,15,8314,1,16,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz
2,Osh_city,г. Ош,013RTICODE,Kyrgyz,Kyrgyz,Urban,KR,№2 К. Маркса,Control,KR,Kyrgyz,Russian,No,No,013RTICODE-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,37,1,Mixed,7,3,2nd,NaN,8883,8677,81,17560,37,44,1,1,1,4/22/21 4:51,4/22/21 4:59,10:51,JTOKTOSHEVA,40.5064858,72.8229702,7.074999809,Мамасадыковна,Жамила,Yes,1,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,0,0,NaN,0,0,Methods of teaching literature,0,0,0,0,0,Other,0,Каллиграфии б ча кайрылышат,0,0,Library,Internet,0,0,School administration,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,Teachers started to apply new strategies for ...,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a quarter,2021-04-22,10:59,0,2021,4/22/2021,4/22/2021,Thu,4,22,9,Matched (3),1,4/22/21 5:40,4/22/21 5:43,JTOKTOSHEVA,41,73,7,Yes,Female,YES,YES,40,YES,1st grade,2nd grade,3rd grade,4th grade,0,Once a week,Once a month,YES,Once a month,11:43,11:40,2021,4/22/2021,4/22/2021,Thu,4,22,3,Matched (3),74,3,297,1,3,1,4/22/21 5:18,4/22/21 5:35,11:18,JTOKTOSHEVA,41,73,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),9-15 years,No,999,999,999,999,Once a month,Improving lesson plans,New strategies for teaching mathematics,New strategies for teaching literature,0,0,0,0,0,No,999,999,999,999,999,999,999,999,999,999,Written tests,Oral assessment,Observations during the lesson,Homework,0,0,NaN,To assess,To assess the student's mastery of the subject,0,Feedback to the student,0,0,Count to 10,0,0,0,0,0,0,0,0,End of 3rd grade,2nd grade,Yes,0,Literary reading competitions and festivals,0,0,0,0,Other,0,Энелердин майрамы,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,Counting sticks,0,0,Geometric board,Geometric figures,Visual aids,0,0,Every lesson,NaN,Yes,0,Children's books,Visual aids,0,0,Didactic materials,0,0,0,NaN,Twice a week,NaN,0,Textbook,Information literature,Guidelines for teachers,Online resources,Lesson plans for other teachers,0,0,0,I will explain the new topic,Primary school students should always be shown...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,11:35,2021,4/22/2021,4/22/2021,Thu,4,22,17,In Both,1,4/22/21 4:36,4/22/21 4:40,10:36,JTOKTOSHEVA,41,73,5,Kyrgyz,15,20,Blackboard,Chalk or whiteboard marker,0,Pencil or pencil,Notebook,0,0,Lesson plan / lesson results,0,54,14,2,24,Yes,Yes,Yes,Row,10:40,NaN,2021,4/22/2021,4/22/2021,Thu,4,22,4,In Both,2nd,013RTICODE-Kyr_2,1,1,3,3,1,No,No,Correct,Correct,Incorrect,Incorrect,Incorrect,2,40,Proportion > 0 Correct,5,40,2021,April,4/22/2021,AQSAQP,Male,8,4/22/21 4:45,4/22/21 5:09,Yes,31,30,No,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,0,62,Proportion > 0 Correct,No,32,97,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,0,54,Proportion > 0 Correct,No,30,100,Correct,Correct,NaN,NaN,NaN,2,40,Proportion > 0 Correct,2,100,Correct,Correct,Incorrect,Correct,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,9,90,Proportion > 0 Correct,10,90,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,10:45,GDOSMATOVA,40.5065752,72.8232433,4.288000107,In writing,Issued the report in column form (for example ...,No,2,In the mind / mouth (the student is thinking o...,0,In writing,Divides numbers into components in some way,No,In writing,Issued the report in column form (for example ...,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,999,Correct,999,Reflected using numbers,No,Correct,999,Add / subtract numbers in the order given in t...,No,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,26,Correct,999,Correct,999,Correct,999,Correct,999,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,0,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,Once a week,Yes,TV,Bicycle,Car,Toilet inside the house,Smartphone,Computer,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,11:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,Thu,22,24,6,100,Score>0,6,100,4,80,Score>0,5,80,4,100,Score>0,4,100,33,94,Yes,Matched (3),Male,AQSAQP,15,3,9,8314,1,9,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz

In [272]:
#Let's get this ordered alphabetically
base.sort_values(by='region',ascending=True,inplace=True)

<ipython-input-272-ce4a05c3bb33>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [273]:
base['oral_read_score_pcnt'] = base['oral_read_score_pcnt'].fillna(0).round().astype(int)
base['oral_read_score_pcnt'].value_counts('')

<ipython-input-273-0d27f7ab883d>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

oral_read_score_pcnt
100    424
98     226
96     120
70      58
94      50
      ...
69       3
31       3
56       2
97       2
33       2
Name: count, Length: 95, dtype: int64

oral_read_score_pcnt	- DONE
g2_math_overall_score_pcnt - DONE

Now let's do some coding to clean up these remaining items that either could have NaN or odd numbers. let's go one by one.

oral_read_attempted_pcnt
read_comp_score_pcnt
word_score
word_score_pcnt
invent_word_score_pcnt

In [274]:
base['oral_read_attempted_pcnt'].value_counts('')
#same issue

oral_read_attempted_pcnt
100.0    571
100      399
98       205
98       134
96       134
        ...
66         1
63         1
47         1
36.0       1
38.0       1
Name: count, Length: 121, dtype: int64

In [275]:
base['oral_read_attempted_pcnt'] = base['oral_read_attempted_pcnt'].fillna(0).round().astype(int)
base['oral_read_attempted_pcnt'].value_counts()

<ipython-input-275-d097bc5717a9>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

oral_read_attempted_pcnt
100    970
98     339
96     202
97     116
95     115
      ...
29       1
45       1
49       1
66       1
36       1
Name: count, Length: 71, dtype: int64

In [276]:
base['read_comp_score_pcnt'].value_counts()

read_comp_score_pcnt
100.0    290
20       265
80.0     265
40.0     262
60       251
0.0      225
80       197
20       179
100      174
60       168
0        161
40       143
Name: count, dtype: int64

In [277]:
base['read_comp_score_pcnt'] = base['read_comp_score_pcnt'].fillna(0).round().astype(int)
base['read_comp_score_pcnt'].value_counts()
#looks cleaner to me!
base['list_comp_score_pcnt'] = base['list_comp_score_pcnt'].fillna(0).round().astype(int)
base['list_comp_score_pcnt'].value_counts()

<ipython-input-277-4d165f29d670>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

read_comp_score_pcnt
100    464
80     462
20     444
60     419
40     405
0      388
Name: count, dtype: int64

<ipython-input-277-4d165f29d670>:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

list_comp_score_pcnt
100    661
80     589
60     517
40     343
0      257
20     215
Name: count, dtype: int64

In [278]:
base['word_score'].value_counts()
#what is going on here.
base['word_score'].dtype

word_score
4    308
3    288
6    274
5    272
2    206
3    196
2    186
1    173
4    172
5    171
1    142
6    127
0     38
0     29
Name: count, dtype: int64

dtype('O')

In [279]:
base['word_score'] = base['word_score'].fillna(0).round().astype(int)
base['word_score'].value_counts() #better!

<ipython-input-279-b759158afdb2>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

word_score
3    484
4    480
5    443
6    401
2    392
1    315
0     67
Name: count, dtype: int64

In [280]:
base['word_score_pcnt'].value_counts()

word_score_pcnt
67     308
50     288
100    274
83     272
33     206
50     196
33     186
17     173
67     172
83     171
17     142
100    127
0       38
0       29
Name: count, dtype: int64

In [281]:
base['word_score_pcnt'] = base['word_score_pcnt'].fillna(0).round().astype(int)
base['word_score_pcnt'].value_counts() #much cleaner!

<ipython-input-281-6d9ff4f1bd4b>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

word_score_pcnt
50     484
67     480
83     443
100    401
33     392
17     315
0       67
Name: count, dtype: int64

In [282]:
base['invent_word_score_pcnt'].value_counts()

invent_word_score_pcnt
46.0    52
62      50
94      46
48.0    46
54      45
        ..
10       8
2        7
4        7
8.0      7
6        6
Name: count, Length: 102, dtype: int64

In [283]:
base['invent_word_score_pcnt'] = base['invent_word_score_pcnt'].fillna(0).round().astype(int)
base['invent_word_score_pcnt'].value_counts() #fixed!

<ipython-input-283-0719fad180d7>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

invent_word_score_pcnt
46     78
64     76
56     75
60     75
62     73
54     72
98     70
52     69
44     68
42     67
48     67
66     67
40     67
38     67
34     66
100    66
70     65
50     64
68     63
58     62
94     60
76     58
96     58
32     58
74     57
36     56
72     53
30     52
80     48
82     47
84     45
92     42
26     39
88     39
0      38
78     37
86     37
22     36
24     36
18     36
90     35
28     34
14     32
20     28
16     25
4      25
12     22
10     21
2      19
8      17
6      15
Name: count, dtype: int64

In [285]:
 #subset
 base = base[[
    'region',
    'district',
    'language',
    'urbanrural',
    'female',
    'age',
    'g2_year',
    'oral_read_score_pcnt',
    'oral_read_attempted_pcnt',
    'read_comp_score_pcnt',
    'word_score',
    'word_score_pcnt',
    'invent_word_score_pcnt',
    'list_comp_score_pcnt',
    ]]
base

Warning: Total number of columns (22) exceeds max_columns (20). Falling back to pandas display.

,region,district,language,urbanrural,female,age,g2_year,oral_read_score_pcnt,oral_read_attempted_pcnt,read_comp_score_pcnt,word_score,word_score_pcnt,invent_word_score_pcnt,list_comp_score_pcnt,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other
385,Batken,Кадамжайский,Kyrgyz,Rural,Female,8,2021,98,98,100,2,33,96,40,0,0,0,0,0,0,0,NaN
1136,Batken,Баткенский,Kyrgyz,Rural,Female,9,2021,46,100,40,2,33,48,60,0,0,0,0.0,0.0,0.0,0,NaN
1138,Batken,Баткенский,Kyrgyz,Rural,Female,9,2021,100,100,100,3,50,46,80,0,0,0,0.0,0.0,0.0,0,NaN
272,Batken,Кадамжайский,Kyrgyz,Rural,Female,8,2021,100,100,100,2,33,96,100,0,0,0,0,0,0,0,NaN
1140,Batken,Баткенский,Kyrgyz,Rural,Female,8,2021,52,94,40,4,67,40,40,0,0,0,0.0,0.0,0.0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,Talas,Бакай-Атинский,Russian,Rural,Female,9,2021,43,70,20,1,17,44,0,0,0,0,0,0,0,0,NaN
1642,Talas,Кара-Бууринский,Kyrgyz,Rural,Male,8,2021,38,100,20,6,100,36,60,0,0,0,0.0,0.0,0.0,0,NaN
799,Talas,Бакай-Атинский,Russian,Rural,Male,7,2021,70,90,20,5,83,70,40,Russian,0,0,0,0,0,0,NaN
778,Talas,Кара-Бууринский,Russian,Rural,Female,7,2021,85,92,80,4,67,52,80,Russian,0,0,0,0,0,0,NaN
550,Talas,Бакай-Атинский,Kyrgyz,Rural,Female,8,2021,84,89,80,5,83,40,40,0,0,0,0,0,0,0,NaN

# EGRA Initial Tables and Graphs

In [ ]:
baselinecount = base.groupby(by=['region','language']).size().rename('count')
baselinecount

In [ ]:
baselinemean = base.pivot_table(index=
 ['region', 'language'],
 values=[
     'oral_read_score_pcnt',
     'read_comp_score_pcnt',
     'word_score_pcnt',
     'invent_word_score_pcnt',
     'list_comp_score_pcnt'],
aggfunc='mean')
baselinemean.round(2)

In [ ]:
# Define the subtask (column name)
subtask = "oral_read_score_pcnt"

# Filter dataframe for only this subtask
oralread = base[["region", subtask]].dropna()  # Remove missing values

# violin plot
fig = px.violin(oralread, x="region", y=subtask, color="region",
                box=True,  # to add mini box plot
                points="all",  # show every datapoint distributed
                title=f"Score Distribution for {subtask} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

In [ ]:
# Define the subtask (column name)
subtask2 = "read_comp_score_pcnt"

# Filter dataframe for only this subtask
readcomp = base[["region", subtask2]].dropna()

# Create the violin plot
fig = px.violin(readcomp, x="region", y=subtask2, color="region",
                box=True,
                points="all",
                title=f"Score Distribution for {subtask2} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

In [ ]:
# Define the subtask (column name)
subtask3 = "word_score_pcnt"

# Filter dataframe for only this subtask
wordscore = base[["region", subtask3]].dropna()  # Remove missing values

# Create the violin plot
fig = px.violin(wordscore, x="region", y=subtask3, color="region",
                box=True,  # Adds a mini box plot inside
                points="all",  # Show all data points
                title=f"Score Distribution for {subtask3} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

In [ ]:
# Define the subtask (column name)
subtask4 = "invent_word_score_pcnt"

# Filter dataframe for only this subtask
inventwordscore = base[["region", subtask4]].dropna()  # Remove missing values

# Create the violin plot
fig = px.violin(inventwordscore, x="region", y=subtask4, color="region",
                box=True,  # Adds a mini box plot inside
                points="all",  # Show all data points
                title=f"Score Distribution for {subtask4} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

In [ ]:
# Define the subtask (column name)
subtask5 = 'list_comp_score_pcnt'


# Filter dataframe for only this subtask
wordscore = base[["region", subtask5]].dropna()  # Remove missing values

# Create the violin plot
fig = px.violin(wordscore, x="region", y=subtask5, color="region",
                box=True,  # Adds a mini box plot inside
                points="all",  # Show all data points
                title=f"Score Distribution for {subtask5} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

**Oral Reading Score**
We can see that Bishkek has one heck of a tail at the upper end, almost looks like a glassblowers pipe! And the box plot is super tight!

Other regions have similar candles, with the distribution towards the top.
The interesting outliers here appear to be Jalal-Abad, Osh, and Osh City. These three , in reviewing the box plot, have a much wider range and we can see don't have the "tail" appearing at the end of the violin chart. Definitely something up with these three regions as a whole!

**Invented Word**
Aside from Bishkek, we're seeing a pretty standard distribution across the board.

**Reading Comp Score Review**
Reading comprehension followed the story/oral reading score.
If students did not fail to read the first line of words, they would be asked questions. If they did not reach certain parts of the story in time, they might not be asked certain questions.
We would expect, as a result, the results might be a bit smoother as some students wouldn't get as far along to receive the next reading comprehension question.

Osh, Talas, and Jalal Abad show a strong concentration and grouping at the bottom of the violin chart. Osh especially is showing some interesting, and perhaps troubling, results. The other regions appear to have a more normal distribution in comparison.

**Word Score Pcnt**
This subtask involved silent reading comprehension.
We're seeing similar patterns to the prior two. However, a really, really interesting note is that the students in Chui seemed to have done a bit better, with a wider distribution than all the other regions, even Bishkek, which did an amazing job on the oral reading and oral reading comprehension questions compared to the other regions. Interesting!

#Statistics

##Two Way ANOVA - between region and language

To summarize the tests run below; a two way ANOVA run on each subtask shows that 1. Region is significant 2. Language is significant. and 3, and most importantly: the interaction between region and language is significant, and differs by region. This is true for all subtasks.

This means I need to follow up digging into each region to see where language is, and isn't, significant.

###Oral Reading Score Two Way ANOVA

In [ ]:
# Fit the two-way ANOVA model
model = smf.ols('oral_read_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

###Reading Comprehension Two Way ANOVA

In [ ]:
# Fit the two-way ANOVA model
model = smf.ols('read_comp_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

###Silent Reading Comprehension Two Way ANOVA

In [ ]:
# Fit the two-way ANOVA model
model = smf.ols('word_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

###Invented Word Score Two Way ANOVA

In [ ]:
# Fit the two-way ANOVA model
model = smf.ols('invent_word_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

###List Comp Score Two Way ANOVA

In [ ]:
# Fit the two-way ANOVA model
model = smf.ols('list_comp_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

##ANOVA - one way test - Language within a region by subtask

###Oral Reading Score Score - between languages within a region

In [ ]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('oral_read_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

Takeaways of ANOVA test within regions for the oral reading  subtask score - did language matter within the region?

1. Batken - significant as p <= .05
2. Bishkek - significant as p <= .05
3. Chui - not significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - significant as p <= .05
9. Talas - not significant as p > .05

###Reading Comprehension - between languages within a region

In [ ]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('read_comp_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

Oral Reading Comprehension  subtask, significance of language within regions
1. Batken - significant as p <= .05
2. Bishkek -  significant as p >= .05
3. Chui -  significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - not significant as p >= .05
9. Talas - not significant as p > .05

###Silent Reading Comprehension - between languages within a region

In [ ]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('word_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

Word Score Percent subtask, significance of language within regions
1. Batken - significant as p <= .05
2. Bishkek - not significant as p >= .05
3. Chui -  significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - significant as p <= .05
9. Talas - not significant as p > .05

###Invented Word Score - between languages within a region

In [ ]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('invent_word_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

Takeaways of ANOVA test within regions for the invented word subtask score - did language matter within the region?

1. Batken - significant as p <= .05
2. Bishkek - significant as p <= .05
3. Chui - not significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - significant as p <= .05
9. Talas - not significant as p > .05

###List Comp Score - between languages within a region

In [ ]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('list_comp_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

##Tukey Test - One Way Significant Results

Significance of Language *within* a region
1. Oral Reading: Batken, Bishkek, Jalal-Abad, Osh, Osh City
2. Reading Comprehension: Batken, Bishkek, Chui, Jalal-Abad, Osh, Osh City
3. Silent Reading: Batken, Bishkek, Chui, Jalal-Abad, Osh, Osh City, Talas
4. Invented Word: Batken, Bishkek, Jalal-Abad, Osh, Osh City
5. Listening Comp:Batken, Bishkek, Chui, Jalal-Abad, Osh, Osh City, Talas

###Oral Reading Tukey Test, Language within region

In [ ]:
oralreadonewayanova = ['Batken', 'Bishkek', 'Jalal-Abad', 'Osh', 'Osh_city']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in oralreadonewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['oral_read_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

###Reading Comp Tukey Test - Language within region

In [ ]:
readcomponewayanova = ['Batken', 'Bishkek', 'Chui','Jalal-Abad', 'Osh', 'Osh_city']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in readcomponewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['read_comp_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

###Silent Reading Tukey Test - Language within Region

In [ ]:
wordscoreonewayanova = ['Batken', 'Bishkek', 'Chui','Jalal-Abad', 'Osh', 'Osh_city','Talas']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in wordscoreonewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['word_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

###Invented Word Score - Language within Region

In [ ]:
inventwordoneway = ['Batken', 'Bishkek','Jalal-Abad', 'Osh', 'Osh_city']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in inventwordoneway:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['invent_word_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

###Listening Comprehension Score - Language within Region

In [ ]:
listcomponewayanova = ['Batken', 'Bishkek', 'Chui','Jalal-Abad', 'Osh', 'Osh_city','Talas']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in listcomponewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['word_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

##Tukey Test - Two Way Group Pairings

In [ ]:
# Create a combined category for region and language
base['Region_Language'] = base['region'] + "_" + base['language']

###Oral Reading Score Tukey Test

In [ ]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['oral_read_score_pcnt'], base['Region_Language'])

# Print results
print(tukey_results)
oraltukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
oraltukey

In [ ]:
# Assuming 'base' is your DataFrame, and it has the columns 'oral_read_score_pcnt' and 'Region_Language'

# Filter for rows where Region_Language includes 'bishkek_russian'
oshcitydata = base[base['Region_Language'] == 'Osh_city_Russian']

# Get the other regions/languages for comparison
other_regions = base[base['Region_Language'] != 'Osh_city_Russian']

# Combine the two datasets so that 'bishkek_russian' is compared to all others
comparison_data = pd.concat([oshcitydata, other_regions])

# Run Tukey's HSD test for the combined dataset
tukey_results = pairwise_tukeyhsd(comparison_data['oral_read_score_pcnt'], comparison_data['Region_Language'])

# Convert Tukey results to a DataFrame for better visualization
tukey_df = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Filter the results to show only those where 'bishkek_russian' is involved in the comparison
tukey_bishkek_russian_comparisons = tukey_df[tukey_df['group1'].str.contains('Osh_city_Russian') | tukey_df['group2'].str.contains('Osh_city_Russian')]

# Display the results
print(tukey_bishkek_russian_comparisons)

In [ ]:
# Assuming 'base' is your DataFrame, and it has the columns 'oral_read_score_pcnt' and 'Region_Language'

# Filter for rows where Region_Language includes 'bishkek_russian'
oshcity_data = base[base['Region_Language'] == 'Osh_city']

# Get the other regions/languages for comparison
other_regions = base[base['Region_Language'] != 'Bishkek_Russian']

# Combine the two datasets so that 'bishkek_russian' is compared to all others
comparison_data = pd.concat([bishkek_russian_data, other_regions])

# Run Tukey's HSD test for the combined dataset
tukey_results = pairwise_tukeyhsd(comparison_data['oral_read_score_pcnt'], comparison_data['Region_Language'])

# Convert Tukey results to a DataFrame for better visualization
tukey_df = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Filter the results to show only those where 'bishkek_russian' is involved in the comparison
tukey_bishkek_russian_comparisons = tukey_df[tukey_df['group1'].str.contains('Bishkek_Russian') | tukey_df['group2'].str.contains('bishkek_russian')]

# Display the results
print(tukey_bishkek_russian_comparisons)

###Reading Comprehension Score Tukey Test

In [ ]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['read_comp_score_pcnt'], base['Region_Language'])

# Print results
readcomptukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
readcomptukey

###Silent Reading Score Tukey Test

In [ ]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['word_score_pcnt'], base['Region_Language'])
wordscoretukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Print results
print(tukey_results)
wordscoretukey

###Invented Word Score Tukey Test

In [ ]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['invent_word_score_pcnt'], base['Region_Language'])
inventtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Print results
print(tukey_results)
inventtukey

###List Comprehension Score Tukey Test

In [ ]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['list_comp_score_pcnt'], base['Region_Language'])
listcomptukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Print results
print(tukey_results)
listcomptukey

##Tukey Analysis

The hypothesis was that Russian would, by and large, outperform the other languages, especially in Bishkek.

For that reason, all significant differences in any pairing with "Russian" and "Bishkek" will be reviewed.

###Original sample count by region and language, and pivot table with means by subtask

In [ ]:
baselinecount = base.groupby(by=['region','language']).size().rename('count')
baselinecount
regethnics

In [ ]:
baselinemean = base.pivot_table(index=
 ['region', 'language'],
 values=[
     'oral_read_score_pcnt',
     'read_comp_score_pcnt',
     'word_score_pcnt',
     'invent_word_score_pcnt',
     'list_comp_score_pcnt'],
aggfunc='mean')
baselinemean.round(2)

###Tukey Analysis - Two Way

In [ ]:
oraltukey[oraltukey['reject'] == True]

In [ ]:
readcomptukey[readcomptukey['reject'] == True]

In [ ]:
wordscoretukey[wordscoretukey['reject'] == True]

In [ ]:
inventtukey[inventtukey['reject'] == True]

# New Section