<a href="https://colab.research.google.com/github/Jonchyk/Datamgmt/blob/main/Capstone_Workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Set Up

In [1]:
#---------------------------SETUP----------------------------------
#get useful libraries
import time, os, sys, re #basics
import zipfile, json, datetime, string   #string for annotating points in scatter
import numpy as np #basic math
# Install tabula-py using pip
!pip install tabula-py
# Import the correct module
from tabula import read_pdf
import statsmodels.api as sm
from statsmodels.formula.api import ols
!pip install pyreadstat
import plotly.express as px
from statsmodels.stats.multicomp import pairwise_tukeyhsd


import matplotlib.pyplot as plt #import pylab as plt #apparently discouraged now:
 #https://stackoverflow.com/questions/11469336/what-is-the-difference-between-pylab-and-pyplot
 #https://www.tutorialspoint.com/matplotlib/matplotlib_pylab_module.htm

import pandas as pd
import pandas_datareader as pdr
from pandas_datareader import wb
from pandas.io.formats.style import Styler
#s4 = Styler(df4, uuid_len=0, cell_ids=False)

import urllib  #weird, guess need to have os and pandas imported for this to work  %TODO/LATER ditch it, its weird anyway, just use wget/curl

from google.colab import files

#import webbrowser

import seaborn as sns

from google.colab import data_table
data_table.enable_dataframe_formatter() #this enables spreadsheet view upon calling dataframe (without() )

#many tricks how to extend notebook functionality
#https://coderzcolumn.com/tutorials/python/list-of-useful-magic-commands-in-jupyter-notebook-lab
#will display all output not just last command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#MAGICS and THEMES/STYLES: important! does affect not just shading/colors, but also fonts, spacing, etc
#(even if you only select default (v not selecting anything) [but does seem to work better if you do make explicit sleections])

###magics: https://ipython.readthedocs.io/en/stable/interactive/magics.html
#most essential setup for vis: it does affect vis! careful!! stick with inline, maybe notebook; others mostly for non-notebook, eg spyder environ
#https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html recomends *inline*!
#show current one:
#%matplotlib
#%matplotlib --list
#interactive plots:
#%matplotlib notebook
#static images of your plot:
%matplotlib inline
#may play with this one and other magics (btw default is probably agg)
#%matplotlib nbagg
##https://www.marktechpost.com/2023/10/20/6-magic-commands-for-jupyter-notebooks-in-python-data-science/
#%%latex
#%ai
#%run
#%writefile
#%history -n

###themes/styles: https://matplotlib.org/stable/gallery/style_sheets/style_sheets_reference.html
#https://jakevdp.github.io/PythonDataScienceHandbook/04.11-settings-and-stylesheets.html
#https://matplotlib.org/stable/tutorials/introductory/customizing.html
#here more about art and style than under the hood functionality as with magics, explore and experiment
#many may find 'default' or seaborn ones more pleasing; my fav 'classic' is back from 90s ;)
#plt.style.available #list available styles :) may install more
#plt.style.use('default') # more delicate subtle than classic
plt.style.use('classic')  #  'seaborn-whitegrid' 'seaborn-white' 'seaborn-poster'
# btw: magics v theme/style sequence matters, eg if i specify classic style before inline magic, i wouldnt get grey bounding box im getting

#sometimes have to install library which you get from https://pypi.org/
#!pip install geopandas

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 57.3 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0
Collecting pyreadstat
  Downloading pyreadstat-1.2.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from pyreadstat) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.17.0)
Downloading pyreadstat-1.2.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 18.6 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.2.8

#Datasets

##Ministry of Science and Education Report - Population and Ethnic Demographics by Region
Report accessed here, table with population information summarized and rebuilt using Tabula. All data is from 2022

 https://stat.gov.kg/media/publicationarchive/fa3392ca-c76e-456f-badd-7a324ff5204d.pdf

In [2]:
!wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn" -O moesreport.pdf

--2025-04-09 23:21:18--  https://drive.google.com/uc?export=download&id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn
Resolving drive.google.com (drive.google.com)... 74.125.26.139, 74.125.26.100, 74.125.26.102, ...
Connecting to drive.google.com (drive.google.com)|74.125.26.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn&export=download [following]
--2025-04-09 23:21:18--  https://drive.usercontent.google.com/download?id=1fTVSC1y_1MSfCS44n7hR-Z7eU-vLtLTn&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.98.132, 2607:f8b0:400c:c1a::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.98.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1484754 (1.4M) [application/octet-stream]
Saving to: ‘moesreport.pdf’

moesreport.pdf      100%[===================>]   1.42M  --.-KB/s    in 0.02s

2025-04-09 23:21:22 (86.6 MB/s) - ‘moesreport.pdf’ saved [1484754/1484754]

## Early Grade Reading Assessment Data

Early Grade Reading Assessment: received with permission from employer, RTI.
Dataset can be accessed at: data.usaid.gov

This is a dataset from the Okuu Keremet! Program's 2021 Baseline study. It has a wealth of information, ranging from G2 teacher, head teacher, and librarian interviews, classroom observations, math results, and early grade reading results. For the purpose of my capstone study, I will be using this dataset, cleaned and targeting specifically the EGRA subtasks: Oral Reading, Oral Reading Comprehension, Invented Word Reading,  Silent Reading Comprehension, and listening comprehension.

In [3]:
# let's load the data set - this is the EGRA file
!wget --no-check-certificate 'https://docs.google.com/spreadsheets/d/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU/export?format=csv' -O Datareading.csv

--2025-04-09 23:21:22--  https://docs.google.com/spreadsheets/d/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU/export?format=csv
Resolving docs.google.com (docs.google.com)... 172.217.203.139, 172.217.203.138, 172.217.203.102, ...
Connecting to docs.google.com (docs.google.com)|172.217.203.139|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://doc-0c-7s-sheets.googleusercontent.com/export/54bogvaave6cua4cdnls17ksc4/cc4ark5iu0ejcsskaqvgdv43qo/1744240880000/113781219181981321798/*/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU?format=csv [following]
Warning: wildcards not supported in HTTP.
--2025-04-09 23:21:23--  https://doc-0c-7s-sheets.googleusercontent.com/export/54bogvaave6cua4cdnls17ksc4/cc4ark5iu0ejcsskaqvgdv43qo/1744240880000/113781219181981321798/*/1Rq8nK25uEKsjwwcu0Sr1IF1oBD6N2BwbmFW5VeiGAfU?format=csv
Resolving doc-0c-7s-sheets.googleusercontent.com (doc-0c-7s-sheets.googleusercontent.com)... 173.194.210.132, 2607:f8b0:400c:c0f::84
Connecting to doc-0c-7s-sheets.googleusercontent.com (doc-0c-7s-sheets.googleusercontent.com)|173.194.210.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘Datareading.csv’

Datareading.csv         [      <=>           ]  29.92M  25.3MB/s    in 1.2s

2025-04-09 23:21:29 (25.3 MB/s) - ‘Datareading.csv’ saved [31368932]

In [4]:
egra = pd.read_csv('Datareading.csv')#let's take a look at this
egra.describe()
pd.set_option('display.max_columns', None)

<ipython-input-4-afdb31daaa64>:1: DtypeWarning: Columns (15,18,19,20,21,22,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,44,45,46,50,52,58,59,60,67,69,70,71,80,90,95,96,100,101,102,104,108,109,110,115,121,128,132,133,134,136,137,138,139,140,141,146,147,148,152,155,156,157,158,159,167,168,176,178,179,185,192,200,201,212,219,220,229,230,241,242,243,245,253,254,263,267,268,269,271,276,277,278,280,281,290,291,292,293,294,300,301,305,306,307,311,312,313,314,315,323,324,326,327,328,333,337,338,391,392,393,396,397,452,453,454,455,456,457,458,459,460,461,462,463,464,465,468,469,475,476,478,479,485,486,488,489,500,501,503,504,510,511,513,514,520,521,523,524,533,535,549,551,555,559,563,565,567,569,571,572,573,574,575,576,582,583,584,585,586,587,588,592,593,604,605,608,610,624,626,629,630,631,632,633,634,637,638,639,640,642,643,644,645,647,648,649,650,652,653,654,655,660,661,662,663,664,665,667,670,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748) have mixed types. Specify dtype option on import or set low_memory=False.
  egra = pd.read_csv('Datareading.csv')#let's take a look at this

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,...,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
count,5275,5275,5275,5275,5275,5275,5275,5275,5275,5275,...,31,31,31,31,1,1,1,1,1214.0,5275
unique,10,54,233,5,5,3,9,233,3,9,...,2,3,4,2,1,1,1,1,3.0,13
top,Жалал-Абадская,Сузакский,20901461,Kyrgyz,Kyrgyz,Rural,K,СШ №66,Treatment,K,...,District,БаткенскаяЛейлекский,1S36560804,School,ci_,invent_word.item_at_time,oral_read.item_at_time,b_oral_read.item_at_time,1.0,2024--Program Kyrgyz
freq,1155,429,41,2874,2874,3797,1772,41,3139,1772,...,30,20,10,30,1,1,1,1,711.0,729

In [5]:
#let's check what we have. I know there's baseline and endline data here. We want just the baseline data, prior to program interventions
egra['g2_year'].value_counts()

g2_year
2024                      2692
2021                      1559
2021                      1023
Grade 2 Read/Math Year       1
Name: count, dtype: int64

In [6]:
#Strange. I have two identical values for 2021. what's up?
egra['g2_year'].apply(type)
egra['g2_year'].dtypes

#Looks like I have strings and integers...I want to convery this all to string

0       <class 'str'>
1       <class 'str'>
2       <class 'str'>
3       <class 'str'>
4       <class 'str'>
            ...
5270    <class 'int'>
5271    <class 'int'>
5272    <class 'int'>
5273    <class 'int'>
5274    <class 'int'>
Name: g2_year, Length: 5275, dtype: object

dtype('O')

In [7]:
#let's see if we can convert all our "2021"'s to a string so its the same value
egra['g2_year'] = egra['g2_year'].apply(lambda x: '2021' if str(x) == '2021' else x)

In [8]:
#let's run it again, looks like it worked!
egra['g2_year'].value_counts()

g2_year
2024                      2692
2021                      2582
Grade 2 Read/Math Year       1
Name: count, dtype: int64

In [9]:
#now I can finally filter to the data I want.
base = egra[egra['g2_year'] == '2021']

In [10]:
base.count()
#bingo!

region                     2582
district                   2582
school_code                2582
language                   2582
language_name              2582
                           ...
invent_worditem_at_time       0
oral_readitem_at_time         0
sil_readitem_at_time          0
userprofileitem1female        0
strata1                    2582
Length: 750, dtype: int64

In [11]:
base.groupby('region').size()

#Breakdown by region, and by group within the baseline study of 2500 observations.
#will need to rename this, but gives some nice quick insights as to what i'll be looking at for my roll up by region!

region
Баткенская        301
Жалал-Абадская    580
Иссык-Кульская    230
Нарынская          96
Ошская            437
Таласская         140
Чуйская           341
г. Бишкек         318
г. Ош             139
dtype: int64

In [12]:
base

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
1,Ошская,Араванский,1S32310502,Kyrgyz,Kyrgyz,Rural,KRU,СШ им.С.Шарипова,Control,KRU,Kyrgyz,Russian,Uzbek,No,1S32310502-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,28,1,Mixed,5,5,2nd,NaN,8883,8677,50,17560,28,22,1,1,1,4/28/21 2:30,4/28/21 2:41,08:30,IISIEVA,40.5202934,72.4959869,3.900000095,Исиева,Инабат,Yes,0,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,Other,0,"Менторства бар. Сабактарга катышуу,алдынкы иш ...",Lesson planning,Methods of teaching mathematics,0,0,0,Use of new information technologies in teaching,0,Additional training and use of training mater...,0,0,NaN,0,0,Library,Internet,Joint meeting of teachers,0,0,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,0,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a year,2021-04-28,08:41,0,2021,4/28/2021,4/28/2021,Wed,4,28,11,Matched (3),1,4/28/21 4:00,4/28/21 4:06,IISIEVA,41,72,4,Yes,Female,YES,YES,20,YES,0,0,3rd grade,4th grade,0,Once every six months,Once a year,YES,Once a week,10:06,10:00,2021,4/28/2021,4/28/2021,Wed,4,28,6,Matched (3),74,5,297,1,4,1,4/28/21 2:54,4/28/21 3:10,08:54,IISIEVA,41,72,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),16-25 years,No,999,999,999,999,Once a week,0,0,0,0,0,0,None of the above,0,No,999,999,999,999,999,999,999,999,999,999,0,Oral assessment,Observations during the lesson,0,0,0,NaN,To assess,0,To plan / change further learning,0,0,0,0,Count to 20,0,Addition and subtraction of simple numbers up...,0,0,Solving Problems from Simple Life,0,0,End of 2nd grade,2nd grade,No,999,999,999,999,999,999,999,999,NaN,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,0,0,0,0,Geometric figures,Visual aids,0,0,Every lesson,NaN,No,999,999,999,999,999,999,999,999,999,NaN,999,NaN,0,Textbook,0,0,Online resources,0,0,0,0,I will show the solution of the problem / problem,Elementary school students can solve new probl...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,09:10,2021,4/28/2021,4/28/2021,Wed,4,28,16,In Both,1,4/28/21 4:14,4/28/21 4:21,10:14,IISIEVA,41,72,6,Kyrgyz,12,16,Blackboard,Chalk or whiteboard marker,0,0,Notebook,0,0,0,0,37,12,0,2,Yes,No,Yes,Row,10:21,NaN,2021,4/28/2021,4/28/2021,Wed,4,28,6,In Both,2nd,1S32310502-Kyr_2,1,1,5,4,1,No,No,Correct,888,Incorrect,Incorrect,888,1,20,Proportion > 0 Correct,5,20,2021,April,4/28/2021,MXGYEW,Female,8,4/28/21 4:08,4/28/21 4:34,Yes,0,3,No,No,Incorrect,Incorrect,Incorrect,Incorrect,Incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0,Proportion = 0 Correct,Yes,5,0,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,5,Proportion > 0 Correct,No,9,33,NaN,NaN,NaN,NaN,NaN,0,0,Proportion = 0 Correct,0,0,Correct,No Answer,Incorrect,No Answer,No Answer,1,20,Proportion > 0 Correct,5,20,Incorrect,Correct,Incorrect,Correct,Incorrect,No Answer,Incorrect,Correct,Incorrect,Incorrect,3,30,Proportion > 0 Correct,10,30,Correct,Correct,Correct,Incorrect,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Incorrect,Incorrect,3,60,Proportion > 0 Correct,5,60,10:08,MUHAMMET,40.5201917,72.4956256,7.504000187,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,1,In the mind / mouth (the student is thinking o...,0,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,In writing,Issued the report in column form (for example ...,No,Correct,Incorrect,Correct,NaN,Incorrect,Correct,Correct,999,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,48,Answers in a different way (I just liked it),No,Incorrect,18,Answers in a different way (I just liked it),No,Incorrect,87,Correct,999,Correct,999,Incorrect,8,Incorrect,4,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,Uzbek,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,2-3 times a week,Yes,TV,0,0,Toilet inside the house,Smartphone,0,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,10:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/28/2021,Wed,28,26,3,50,Score>0,5,60,2,40,Score>0,5,40,2,50,Score>0,4,50,17,49,No,Matched (3),Female,MXGYEW,16,3,15,8314,1,16,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz
2,г. Ош,г. Ош,013RTICODE,Kyrgyz,Kyrgyz,Urban,KR,№2 К. Маркса,Control,KR,Kyrgyz,Russian,No,No,013RTICODE-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,37,1,Mixed,7,3,2nd,NaN,8883,8677,81,17560,37,44,1,1,1,4/22/21 4:51,4/22/21 4:59,10:51,JTOKTOSHEVA,40.5064858,72.8229702,7.074999809,Мамасадыковна,Жамила,Yes,1,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,0,0,NaN,0,0,Methods of teaching literature,0,0,0,0,0,Other,0,Каллиграфии б ча кайрылышат,0,0,Library,Internet,0,0,School administration,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,Teachers started to apply new strategies for ...,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a quarter,2021-04-22,10:59,0,2021,4/22/2021,4/22/2021,Thu,4,22,9,Matched (3),1,4/22/21 5:40,4/22/21 5:43,JTOKTOSHEVA,41,73,7,Yes,Female,YES,YES,40,YES,1st grade,2nd grade,3rd grade,4th grade,0,Once a week,Once a month,YES,Once a month,11:43,11:40,2021,4/22/2021,4/22/2021,Thu,4,22,3,Matched (3),74,3,297,1,3,1,4/22/21 5:18,4/22/21 5:35,11:18,JTOKTOSHEVA,41,73,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),9-15 years,No,999,999,999,999,Once a month,Improving lesson plans,New strategies for teaching mathematics,New strategies for teaching literature,0,0,0,0,0,No,999,999,999,999,999,999,999,999,999,999,Written tests,Oral assessment,Observations during the lesson,Homework,0,0,NaN,To assess,To assess the student's mastery of the subject,0,Feedback to the student,0,0,Count to 10,0,0,0,0,0,0,0,0,End of 3rd grade,2nd grade,Yes,0,Literary reading competitions and festivals,0,0,0,0,Other,0,Энелердин майрамы,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,Counting sticks,0,0,Geometric board,Geometric figures,Visual aids,0,0,Every lesson,NaN,Yes,0,Children's books,Visual aids,0,0,Didactic materials,0,0,0,NaN,Twice a week,NaN,0,Textbook,Information literature,Guidelines for teachers,Online resources,Lesson plans for other teachers,0,0,0,I will explain the new topic,Primary school students should always be shown...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,11:35,2021,4/22/2021,4/22/2021,Thu,4,22,17,In Both,1,4/22/21 4:36,4/22/21 4:40,10:36,JTOKTOSHEVA,41,73,5,Kyrgyz,15,20,Blackboard,Chalk or whiteboard marker,0,Pencil or pencil,Notebook,0,0,Lesson plan / lesson results,0,54,14,2,24,Yes,Yes,Yes,Row,10:40,NaN,2021,4/22/2021,4/22/2021,Thu,4,22,4,In Both,2nd,013RTICODE-Kyr_2,1,1,3,3,1,No,No,Correct,Correct,Incorrect,Incorrect,Incorrect,2,40,Proportion > 0 Correct,5,40,2021,April,4/22/2021,AQSAQP,Male,8,4/22/21 4:45,4/22/21 5:09,Yes,31,30,No,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,0,62,Proportion > 0 Correct,No,32,97,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,0,54,Proportion > 0 Correct,No,30,100,Correct,Correct,NaN,NaN,NaN,2,40,Proportion > 0 Correct,2,100,Correct,Correct,Incorrect,Correct,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,9,90,Proportion > 0 Correct,10,90,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,10:45,GDOSMATOVA,40.5065752,72.8232433,4.288000107,In writing,Issued the report in column form (for example ...,No,2,In the mind / mouth (the student is thinking o...,0,In writing,Divides numbers into components in some way,No,In writing,Issued the report in column form (for example ...,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,999,Correct,999,Reflected using numbers,No,Correct,999,Add / subtract numbers in the order given in t...,No,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,26,Correct,999,Correct,999,Correct,999,Correct,999,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,0,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,Once a week,Yes,TV,Bicycle,Car,Toilet inside the house,Smartphone,Computer,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,11:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,Thu,22,24,6,100,Score>0,6,100,4,80,Score>0,5,80,4,100,Score>0,4,100,33,94,Yes,Matched (3),Male,AQSAQP,15,3,9,8314,1,9,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz

##Cleaning Dataset for Regional Demographics

In [13]:
moes = read_pdf('moesreport.pdf', pages='19-20',multiple_tables=True, stream=True)

WARNING:tabula.backend:Failed to import jpype dependencies. Fallback to subprocess.
WARNING:tabula.backend:No module named 'jpype'

In [14]:
moes = pd.DataFrame(moes[1])

In [15]:
# Move column names into the first row
moes.loc[-1] = moes.columns  # Shift column names into row 0
moes.index = moes.index + 1  # Shift index to make space
moes = moes.sort_index().reset_index(drop=True)  # Reset index

# Rename the first column if necessary
moes = moes.rename(columns={moes.columns[0]: "Ethnicity"})

In [16]:
moes

,Ethnicity,7 037 590,570 898,1 311 007,538 384,308 348,1 460 425,273 509,1 068 702,1 145 044,361 273,Unnamed: 0
0,Total population,7 037 590,570 898,1 311 007,538 384,308 348,1 460 425,273 509,1 068 702,1 145 044,361 273,Unnamed: 0
1,including:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kyrgyz,5 470 806,451 422,967 355,492 452,307 095,1 003 764,260 038,798 347,975 128,215 205,Batken oblast
3,Russians,277 646,2 021,5 062,27 424,88,1 254,3 257,124 640,110 439,3 461,NaN
4,Uzbeks,995 454,78 314,321 461,3 463,291,421 519,1 006,17 480,15 899,136 021,Jalal-Abad
5,Ukrainians,3 257,10,88,147,-,14,55,1 715,1 199,29,oblast
6,Germans,2 747,2,55,85,6,1,143,1 768,671,16,NaN
7,Tatars,11 353,479,1 027,1 112,78,479,121,3 109,4 324,624,Issyk-Kul oblast
8,Kazakhs,28 389,317,898,5 976,190,823,2 141,10 554,7 176,314,NaN
9,Armenians,494,3,124,10,-,51,1,104,194,7,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Naryn oblast
11,Tajiks,60 752,36 921,7 153,213,23,8 626,53,5 208,1 743,812,NaN
12,Azerbaijanis,17 560,50,513,50,1,5 085,12,10 081,1 263,505,NaN
13,Chechens,1 116,21,34,6,-,64,20,766,201,4,Osh oblast
14,Belarusians,359,7,18,13,1,2,10,164,138,6,NaN
15,Georgians,154,6,34,2,-,1,8,38,65,-,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Talas oblast
17,Lithuanians,35,-,1,-,-,-,-,17,15,2,NaN
18,Moldovans,106,-,6,1,-,-,2,67,26,4,NaN
19,Latvians,33,-,-,-,-,-,-,15,18,-,Chui oblast
20,Turkmens,2 358,163,480,23,14,940,56,268,196,218,NaN
21,Estonians,26,1,-,2,-,-,-,13,10,-,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bishkek city
23,Jews,129,-,-,3,-,2,-,15,107,2,NaN
24,Uighurs,32 390,137,1 476,2 196,149,8 073,84,12 258,7 850,167,NaN
25,Dungan,67 268,11,17,3 161,368,580,31,59 922,3 149,29,Osh city
26,Koreans,5 935,28,68,48,-,21,28,1 465,4 219,58,NaN
27,Turks,22 397,733,2 980,34,9,8 549,901,6 796,1 865,530,NaN
28,people of india,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,and pakistan,8 271,2,411,328,2,2,9,809,3 806,2 902,NaN
30,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,nationalities,28 555,250,1 746,1 635,33,575,5 533,13 083,5 343,357,NaN

In [17]:
# Define new column names
new_column_names = {
    "Ethnicity": "Ethnicity",
    "7 037 590": "Total Population",
    "570 898": "Batken",
    "1 311 007": "Jalal-Abad",
    "538 384": "Issyk-Kul",
    "308 348": "Naryn",
    "1 460 425": "Osh",
    "273 509": "Talas",
    "1 068 702": "Chui",
    "1 145 044": "Bishkek",
    "361 273": "Osh city"
}

# Rename the columns in the DataFrame
moes = moes.rename(columns=new_column_names)

# Drop the "Unnamed: 0" column if it still exists
moes = moes.drop(columns=["Unnamed: 0"], errors="ignore")

# Display the updated DataFrame
moes

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Total population,7 037 590,570 898,1 311 007,538 384,308 348,1 460 425,273 509,1 068 702,1 145 044,361 273
1,including:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kyrgyz,5 470 806,451 422,967 355,492 452,307 095,1 003 764,260 038,798 347,975 128,215 205
3,Russians,277 646,2 021,5 062,27 424,88,1 254,3 257,124 640,110 439,3 461
4,Uzbeks,995 454,78 314,321 461,3 463,291,421 519,1 006,17 480,15 899,136 021
5,Ukrainians,3 257,10,88,147,-,14,55,1 715,1 199,29
6,Germans,2 747,2,55,85,6,1,143,1 768,671,16
7,Tatars,11 353,479,1 027,1 112,78,479,121,3 109,4 324,624
8,Kazakhs,28 389,317,898,5 976,190,823,2 141,10 554,7 176,314
9,Armenians,494,3,124,10,-,51,1,104,194,7
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Tajiks,60 752,36 921,7 153,213,23,8 626,53,5 208,1 743,812
12,Azerbaijanis,17 560,50,513,50,1,5 085,12,10 081,1 263,505
13,Chechens,1 116,21,34,6,-,64,20,766,201,4
14,Belarusians,359,7,18,13,1,2,10,164,138,6
15,Georgians,154,6,34,2,-,1,8,38,65,-
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Lithuanians,35,-,1,-,-,-,-,17,15,2
18,Moldovans,106,-,6,1,-,-,2,67,26,4
19,Latvians,33,-,-,-,-,-,-,15,18,-
20,Turkmens,2 358,163,480,23,14,940,56,268,196,218
21,Estonians,26,1,-,2,-,-,-,13,10,-
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Jews,129,-,-,3,-,2,-,15,107,2
24,Uighurs,32 390,137,1 476,2 196,149,8 073,84,12 258,7 850,167
25,Dungan,67 268,11,17,3 161,368,580,31,59 922,3 149,29
26,Koreans,5 935,28,68,48,-,21,28,1 465,4 219,58
27,Turks,22 397,733,2 980,34,9,8 549,901,6 796,1 865,530
28,people of india,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,and pakistan,8 271,2,411,328,2,2,9,809,3 806,2 902
30,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,nationalities,28 555,250,1 746,1 635,33,575,5 533,13 083,5 343,357

In [18]:
moes.drop([1,10,16,22,28,30], inplace=True)
# Define specific ethnicity name replacements
ethnicity_replacements = {
    "nationalities": "Other nationalities",
    "and pakistan": "Indian and Pakistani",
    # Add more replacements as needed
}

# Apply the replacements
moes["Ethnicity"] = moes["Ethnicity"].replace(ethnicity_replacements)

In [19]:
for col in moes.columns[1:]:  # Skip 'Ethnicity' column
    moes[col] = moes[col].astype(str).str.replace(" ", "").str.replace("-", "0") #replace '-' with 0 for missing values. you may want to use NaN instead
    moes[col] = pd.to_numeric(moes[col], errors='coerce').fillna(0).astype(int) # Convert to numeric, handle errors, fill NaN with 0, then to int

In [20]:
moes['Ethnicity'] = moes['Ethnicity'].str.replace('Total', 'Sum') #this will do it for any ethnicity with 'Total' in the name
moes

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,7037590,570898,1311007,538384,308348,1460425,273509,1068702,1145044,361273
2,Kyrgyz,5470806,451422,967355,492452,307095,1003764,260038,798347,975128,215205
3,Russians,277646,2021,5062,27424,88,1254,3257,124640,110439,3461
4,Uzbeks,995454,78314,321461,3463,291,421519,1006,17480,15899,136021
5,Ukrainians,3257,10,88,147,0,14,55,1715,1199,29
6,Germans,2747,2,55,85,6,1,143,1768,671,16
7,Tatars,11353,479,1027,1112,78,479,121,3109,4324,624
8,Kazakhs,28389,317,898,5976,190,823,2141,10554,7176,314
9,Armenians,494,3,124,10,0,51,1,104,194,7
11,Tajiks,60752,36921,7153,213,23,8626,53,5208,1743,812
12,Azerbaijanis,17560,50,513,50,1,5085,12,10081,1263,505
13,Chechens,1116,21,34,6,0,64,20,766,201,4
14,Belarusians,359,7,18,13,1,2,10,164,138,6
15,Georgians,154,6,34,2,0,1,8,38,65,0
17,Lithuanians,35,0,1,0,0,0,0,17,15,2
18,Moldovans,106,0,6,1,0,0,2,67,26,4
19,Latvians,33,0,0,0,0,0,0,15,18,0
20,Turkmens,2358,163,480,23,14,940,56,268,196,218
21,Estonians,26,1,0,2,0,0,0,13,10,0
23,Jews,129,0,0,3,0,2,0,15,107,2
24,Uighurs,32390,137,1476,2196,149,8073,84,12258,7850,167
25,Dungan,67268,11,17,3161,368,580,31,59922,3149,29
26,Koreans,5935,28,68,48,0,21,28,1465,4219,58
27,Turks,22397,733,2980,34,9,8549,901,6796,1865,530
29,Indian and Pakistani,8271,2,411,328,2,2,9,809,3806,2902
31,Other nationalities,28555,250,1746,1635,33,575,5533,13083,5343,357

In [21]:
regselect = ['Sum population','Kyrgyz','Russians','Uzbeks','Tajiks']
regethnics = moes[moes['Ethnicity'].isin(regselect)]

In [22]:
regethnics
#table to provide total population, filtered for the ethnicities of interest

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,7037590,570898,1311007,538384,308348,1460425,273509,1068702,1145044,361273
2,Kyrgyz,5470806,451422,967355,492452,307095,1003764,260038,798347,975128,215205
3,Russians,277646,2021,5062,27424,88,1254,3257,124640,110439,3461
4,Uzbeks,995454,78314,321461,3463,291,421519,1006,17480,15899,136021
11,Tajiks,60752,36921,7153,213,23,8626,53,5208,1743,812

In [23]:
regethnics = regethnics.applymap(lambda x: f"{x:,}" if isinstance(x, (int, float)) else x)
regethnics
#We are interested in the four target languages and groups by region, as well as total population

<ipython-input-23-5a03fe27d567>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  regethnics = regethnics.applymap(lambda x: f"{x:,}" if isinstance(x, (int, float)) else x)

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,"7,037,590","570,898","1,311,007","538,384","308,348","1,460,425","273,509","1,068,702","1,145,044","361,273"
2,Kyrgyz,"5,470,806","451,422","967,355","492,452","307,095","1,003,764","260,038","798,347","975,128","215,205"
3,Russians,"277,646","2,021","5,062","27,424",88,"1,254","3,257","124,640","110,439","3,461"
4,Uzbeks,"995,454","78,314","321,461","3,463",291,"421,519","1,006","17,480","15,899","136,021"
11,Tajiks,"60,752","36,921","7,153",213,23,"8,626",53,"5,208","1,743",812

Remaining is to download the report, remove the indexes, and add a title "Regional population breakout by region and demographics". This will then be transferred over to the appendix.

In [24]:
regethnics.to_csv('moesreport.csv')
files.download('moesreport.csv')

##Cleaning EGRA Dataset

In [25]:
base #Cleaning dataset
pd.set_option('display.max_columns', None)

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
1,Ошская,Араванский,1S32310502,Kyrgyz,Kyrgyz,Rural,KRU,СШ им.С.Шарипова,Control,KRU,Kyrgyz,Russian,Uzbek,No,1S32310502-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,28,1,Mixed,5,5,2nd,NaN,8883,8677,50,17560,28,22,1,1,1,4/28/21 2:30,4/28/21 2:41,08:30,IISIEVA,40.5202934,72.4959869,3.900000095,Исиева,Инабат,Yes,0,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,Other,0,"Менторства бар. Сабактарга катышуу,алдынкы иш ...",Lesson planning,Methods of teaching mathematics,0,0,0,Use of new information technologies in teaching,0,Additional training and use of training mater...,0,0,NaN,0,0,Library,Internet,Joint meeting of teachers,0,0,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,0,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a year,2021-04-28,08:41,0,2021,4/28/2021,4/28/2021,Wed,4,28,11,Matched (3),1,4/28/21 4:00,4/28/21 4:06,IISIEVA,41,72,4,Yes,Female,YES,YES,20,YES,0,0,3rd grade,4th grade,0,Once every six months,Once a year,YES,Once a week,10:06,10:00,2021,4/28/2021,4/28/2021,Wed,4,28,6,Matched (3),74,5,297,1,4,1,4/28/21 2:54,4/28/21 3:10,08:54,IISIEVA,41,72,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),16-25 years,No,999,999,999,999,Once a week,0,0,0,0,0,0,None of the above,0,No,999,999,999,999,999,999,999,999,999,999,0,Oral assessment,Observations during the lesson,0,0,0,NaN,To assess,0,To plan / change further learning,0,0,0,0,Count to 20,0,Addition and subtraction of simple numbers up...,0,0,Solving Problems from Simple Life,0,0,End of 2nd grade,2nd grade,No,999,999,999,999,999,999,999,999,NaN,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,0,0,0,0,Geometric figures,Visual aids,0,0,Every lesson,NaN,No,999,999,999,999,999,999,999,999,999,NaN,999,NaN,0,Textbook,0,0,Online resources,0,0,0,0,I will show the solution of the problem / problem,Elementary school students can solve new probl...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,09:10,2021,4/28/2021,4/28/2021,Wed,4,28,16,In Both,1,4/28/21 4:14,4/28/21 4:21,10:14,IISIEVA,41,72,6,Kyrgyz,12,16,Blackboard,Chalk or whiteboard marker,0,0,Notebook,0,0,0,0,37,12,0,2,Yes,No,Yes,Row,10:21,NaN,2021,4/28/2021,4/28/2021,Wed,4,28,6,In Both,2nd,1S32310502-Kyr_2,1,1,5,4,1,No,No,Correct,888,Incorrect,Incorrect,888,1,20,Proportion > 0 Correct,5,20,2021,April,4/28/2021,MXGYEW,Female,8,4/28/21 4:08,4/28/21 4:34,Yes,0,3,No,No,Incorrect,Incorrect,Incorrect,Incorrect,Incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0,Proportion = 0 Correct,Yes,5,0,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,5,Proportion > 0 Correct,No,9,33,NaN,NaN,NaN,NaN,NaN,0,0,Proportion = 0 Correct,0,0,Correct,No Answer,Incorrect,No Answer,No Answer,1,20,Proportion > 0 Correct,5,20,Incorrect,Correct,Incorrect,Correct,Incorrect,No Answer,Incorrect,Correct,Incorrect,Incorrect,3,30,Proportion > 0 Correct,10,30,Correct,Correct,Correct,Incorrect,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Incorrect,Incorrect,3,60,Proportion > 0 Correct,5,60,10:08,MUHAMMET,40.5201917,72.4956256,7.504000187,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,1,In the mind / mouth (the student is thinking o...,0,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,In writing,Issued the report in column form (for example ...,No,Correct,Incorrect,Correct,NaN,Incorrect,Correct,Correct,999,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,48,Answers in a different way (I just liked it),No,Incorrect,18,Answers in a different way (I just liked it),No,Incorrect,87,Correct,999,Correct,999,Incorrect,8,Incorrect,4,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,Uzbek,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,2-3 times a week,Yes,TV,0,0,Toilet inside the house,Smartphone,0,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,10:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/28/2021,Wed,28,26,3,50,Score>0,5,60,2,40,Score>0,5,40,2,50,Score>0,4,50,17,49,No,Matched (3),Female,MXGYEW,16,3,15,8314,1,16,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz
2,г. Ош,г. Ош,013RTICODE,Kyrgyz,Kyrgyz,Urban,KR,№2 К. Маркса,Control,KR,Kyrgyz,Russian,No,No,013RTICODE-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,37,1,Mixed,7,3,2nd,NaN,8883,8677,81,17560,37,44,1,1,1,4/22/21 4:51,4/22/21 4:59,10:51,JTOKTOSHEVA,40.5064858,72.8229702,7.074999809,Мамасадыковна,Жамила,Yes,1,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,0,0,NaN,0,0,Methods of teaching literature,0,0,0,0,0,Other,0,Каллиграфии б ча кайрылышат,0,0,Library,Internet,0,0,School administration,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,Teachers started to apply new strategies for ...,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a quarter,2021-04-22,10:59,0,2021,4/22/2021,4/22/2021,Thu,4,22,9,Matched (3),1,4/22/21 5:40,4/22/21 5:43,JTOKTOSHEVA,41,73,7,Yes,Female,YES,YES,40,YES,1st grade,2nd grade,3rd grade,4th grade,0,Once a week,Once a month,YES,Once a month,11:43,11:40,2021,4/22/2021,4/22/2021,Thu,4,22,3,Matched (3),74,3,297,1,3,1,4/22/21 5:18,4/22/21 5:35,11:18,JTOKTOSHEVA,41,73,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),9-15 years,No,999,999,999,999,Once a month,Improving lesson plans,New strategies for teaching mathematics,New strategies for teaching literature,0,0,0,0,0,No,999,999,999,999,999,999,999,999,999,999,Written tests,Oral assessment,Observations during the lesson,Homework,0,0,NaN,To assess,To assess the student's mastery of the subject,0,Feedback to the student,0,0,Count to 10,0,0,0,0,0,0,0,0,End of 3rd grade,2nd grade,Yes,0,Literary reading competitions and festivals,0,0,0,0,Other,0,Энелердин майрамы,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,Counting sticks,0,0,Geometric board,Geometric figures,Visual aids,0,0,Every lesson,NaN,Yes,0,Children's books,Visual aids,0,0,Didactic materials,0,0,0,NaN,Twice a week,NaN,0,Textbook,Information literature,Guidelines for teachers,Online resources,Lesson plans for other teachers,0,0,0,I will explain the new topic,Primary school students should always be shown...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,11:35,2021,4/22/2021,4/22/2021,Thu,4,22,17,In Both,1,4/22/21 4:36,4/22/21 4:40,10:36,JTOKTOSHEVA,41,73,5,Kyrgyz,15,20,Blackboard,Chalk or whiteboard marker,0,Pencil or pencil,Notebook,0,0,Lesson plan / lesson results,0,54,14,2,24,Yes,Yes,Yes,Row,10:40,NaN,2021,4/22/2021,4/22/2021,Thu,4,22,4,In Both,2nd,013RTICODE-Kyr_2,1,1,3,3,1,No,No,Correct,Correct,Incorrect,Incorrect,Incorrect,2,40,Proportion > 0 Correct,5,40,2021,April,4/22/2021,AQSAQP,Male,8,4/22/21 4:45,4/22/21 5:09,Yes,31,30,No,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,0,62,Proportion > 0 Correct,No,32,97,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,0,54,Proportion > 0 Correct,No,30,100,Correct,Correct,NaN,NaN,NaN,2,40,Proportion > 0 Correct,2,100,Correct,Correct,Incorrect,Correct,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,9,90,Proportion > 0 Correct,10,90,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,10:45,GDOSMATOVA,40.5065752,72.8232433,4.288000107,In writing,Issued the report in column form (for example ...,No,2,In the mind / mouth (the student is thinking o...,0,In writing,Divides numbers into components in some way,No,In writing,Issued the report in column form (for example ...,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,999,Correct,999,Reflected using numbers,No,Correct,999,Add / subtract numbers in the order given in t...,No,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,26,Correct,999,Correct,999,Correct,999,Correct,999,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,0,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,Once a week,Yes,TV,Bicycle,Car,Toilet inside the house,Smartphone,Computer,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,11:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,Thu,22,24,6,100,Score>0,6,100,4,80,Score>0,5,80,4,100,Score>0,4,100,33,94,Yes,Matched (3),Male,AQSAQP,15,3,9,8314,1,9,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz

In [26]:
#replace/map/recode
base['region'].replace({
    'Ошская': 'Osh',
    'г. Ош' : 'Osh_city',
    'Чуйская':'Chui',
    'Таласская':'Talas',
    'Иссык-Кульская':'Issyk-Kul',
    'г. Бишкек':'Bishkek',
    'Жалал-Абадская': 'Jalal-Abad',
    'Нарынская':'Naryn',
    'Баткенская':'Batken'}, inplace=True)
base.head(3)# names fixed,

<ipython-input-26-73aea0ebcfff>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  base['region'].replace({
<ipython-input-26-73aea0ebcfff>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['region'].replace({

Warning: Total number of columns (750) exceeds max_columns (20). Falling back to pandas display.

,region,district,school_code,language,language_name,urbanrural,loi,school_name,treatment,loi_name,loi_kyrgyz,loi_russian,loi_uzbek,loi_tajik,stage1,fpc1,in_G2_master,in_G4_master,n_sampled,n_g4_sampled,pop_strata1,n_g2f_sampled,n_g2m_sampled,Dup_id,g_tot,n_classes,strata,n_g4f_sampled,n_g4m_sampled,grade,n_g2_sampled,pop_g2_strata1,pop_g4_strata1,g2g4_tot,pop_g2g4_strata1,g2_tot,g4_tot,g2_classes,g4_classes,in_ht,ht_start_time,ht_end_time,ht_time_start,ht_enumerator,ht_gps_latitude,ht_gps_longitude,ht_gps_accuracy,userprofileitem1first_name,userprofileitem1last_name,sh_consent,sh_female,sh_position,sh_position_other,sh_1,sh_2_1,sh_2_2,sh_2_3,sh_2_4,sh_2_777,sh_2_888,sh_2_other,sh_3_1,sh_3_2,sh_3_3,sh_3_4,sh_3_5,sh_3_6,sh_3_8,sh_3_7,sh_3_777,sh_3_888,sh_3_other,sh_4_1,sh_4_2,sh_4_3,sh_4_4,sh_4_5,sh_4_6,sh_4_7,sh_4_777,sh_4_888,sh_4_other,sh_5,sh_6,sh_7,sh_8_1,sh_8_2,sh_8_3,sh_8_4,sh_8_5,sh_8_888,sh_9,sh_10,date_end,ht_time_end,sh_8_6,ht_year,ht_date,ht_date_char,ht_dayofweek,ht_month,ht_day,sh_minutes_assess,_merge_Master_HT,in_l,l_start_time,l_end_time,l_enumerator,l_gps_latitude,l_gps_longitude,l_gps_accuracy,l_consent,l_female,l1,l2,l3,l4,l5_1,l5_2,l5_3,l5_4,l5_888,l6,l7,l8,l9,l_time_end,l_time_start,l_year,l_date,l_date_char,l_dayofweek,l_month,l_day,l_minutes_assess,_merge_Master_Lib,n_schools_sampled,wt1,sum_wt1,scale_wt1,wt_stage1,in_t,t_start_time,t_end_time,t_time_start,t_enumerator,t_gps_latitude,t_gps_longitude,t_gps_accuracy,t_consent,t_female,tq_language,tq_language_other,tq_1,tq_2,tq_3,tq_4_1,tq_4_2,tq_4_3,tq_4_888,tq_5,tq_6_1,tq_6_2,tq_6_3,tq_6_4,tq_6_5,tq_6_6,tq_6_000,tq_6_888,tq_7,tq_8,tq_9,tq_10_1,tq_10_2,tq_10_3,tq_10_4,tq_10_5,tq_10_6,tq_10_000,tq_10_888,tq_11_1,tq_11_2,tq_11_3,tq_11_4,tq_11_777,tq_11_888,tq_11_other,tq_12_1,tq_12_2,tq_12_3,tq_12_4,tq_12_5,tq_12_888,tq_13_1,tq_13_2,tq_13_3,tq_13_4,tq_13_5,tq_13_6,tq_13_7,tq_13_000,tq_13_888,tq_14,tq_15,tq_16,tq_17_1,tq_17_2,tq_17_3,tq_17_4,tq_17_5,tq_17_6,tq_17_777,tq_17_888,tq_17_other,tq_18_1,tq_18_2,tq_18_3,tq_18_4,tq_18_777,tq_18_000,tq_18_888,tq_18_other,tq_19,tq_20_1,tq_20_2,tq_20_3,tq_20_4,tq_20_5,tq_20_6,tq_20_777,tq_20_888,tq_21,tq_21_other,tq_22,tq_23_1,tq_23_2,tq_23_3,tq_23_4,tq_23_5,tq_23_6,tq_23_7,tq_23_777,tq_23_888,tq_23_other,tq_24,tq_24_other,tq_25_1,tq_25_2,tq_25_3,tq_25_4,tq_25_5,tq_25_6,tq_25_7,tq_25_777,tq_25_888,tq_26,tq_27,tq_28,tq_29,tq_30,tq_31,tq_32,t_time_end,t_year,t_date,t_date_char,t_dayofweek,t_month,t_day,t_minutes_assess,_merge_Master_Teach,in_ci,ci_start_time,ci_end_time,ci_time_start,ci_enumerator,ci_gps_latitude,ci_gps_longitude,ci_gps_accuracy,ci_language,males_enrolled,females_enrolled,ci_1_1,ci_1_2,ci_1_3,ci_1_4,ci_1_5,ci_1_6,ci_1_7,ci_1_8,ci_1_000,ci_2,ci_3,ci_4,ci_5,ci_6,ci_7,ci_8,ci_9,ci_time_end,userprofileid,ci_year,ci_date,ci_date_char,ci_dayofweek,ci_month,ci_day,ci_minutes_assess,_merge_Master_ClassInv,strata2,stage2,fpc2,wt2,wt12,wt_stage2,in_g2,sil_read_comp_score_pcnt80,sil_read_comp_attempted_pcnt80,sil_read_comp1,sil_read_comp2,sil_read_comp3,sil_read_comp4,sil_read_comp5,sil_read_comp_score,sil_read_comp_score_pcnt,sil_read_comp_score_zero,sil_read_comp_attempted,sil_read_comp_attempted_pcnt,g2_year,g2_month,g2_date,id,female,age,g2_start_time,g2_end_time,g2_consent,cnonwpm,orf,read_comp_score_pcnt80,read_comp_attempted_pcnt80,invent_word1,invent_word2,invent_word3,invent_word4,invent_word5,invent_word6,invent_word7,invent_word8,invent_word9,invent_word10,invent_word11,invent_word12,invent_word13,invent_word14,invent_word15,invent_word16,invent_word17,invent_word18,invent_word19,invent_word20,invent_word21,invent_word22,invent_word23,invent_word24,invent_word25,invent_word26,invent_word27,invent_word28,invent_word29,invent_word30,invent_word31,invent_word32,invent_word33,invent_word34,invent_word35,invent_word36,invent_word37,invent_word38,invent_word39,invent_word40,invent_word41,invent_word42,invent_word43,invent_word44,invent_word45,invent_word46,invent_word47,invent_word48,invent_word49,invent_word50,invent_word_score,invent_word_time_remain,invent_word_score_pcnt,invent_word_score_zero,invent_word_auto_stop,invent_word_attempted,invent_word_attempted_pcnt,oral_read1,oral_read2,oral_read3,oral_read4,oral_read5,oral_read6,oral_read7,oral_read8,oral_read9,oral_read10,oral_read11,oral_read12,oral_read13,oral_read14,oral_read15,oral_read16,oral_read17,oral_read18,oral_read19,oral_read20,oral_read21,oral_read22,oral_read23,oral_read24,oral_read25,oral_read26,oral_read27,oral_read28,oral_read29,oral_read30,oral_read31,oral_read32,oral_read33,oral_read34,oral_read35,oral_read36,oral_read37,oral_read38,oral_read39,oral_read40,oral_read41,oral_read42,oral_read43,oral_read44,oral_read45,oral_read46,oral_read47,oral_read48,oral_read49,oral_read50,oral_read51,oral_read52,oral_read53,oral_read54,oral_read55,oral_read56,oral_read57,oral_read58,oral_read59,oral_read60,oral_read61,oral_read62,oral_read63,oral_read64,oral_read65,oral_read_score,oral_read_time_remain,oral_read_score_pcnt,oral_read_score_zero,oral_read_auto_stop,oral_read_attempted,oral_read_attempted_pcnt,read_comp1,read_comp2,read_comp3,read_comp4,read_comp5,read_comp_score,read_comp_score_pcnt,read_comp_score_zero,read_comp_attempted,read_comp_attempted_pcnt,list_comp1,list_comp2,list_comp3,list_comp4,list_comp5,list_comp_score,list_comp_score_pcnt,list_comp_score_zero,list_comp_attempted,list_comp_attempted_pcnt,miss_num1,miss_num2,miss_num3,miss_num4,miss_num5,miss_num6,miss_num7,miss_num8,miss_num9,miss_num10,miss_num_score,miss_num_score_pcnt,miss_num_score_zero,miss_num_attempted,miss_num_attempted_pcnt,addlvl21,addlvl22,addlvl23,addlvl24,addlvl25,addlvl2_score,addlvl2_score_pcnt,addlvl2_score_zero,addlvl2_attempted,addlvl2_attempted_pcnt,sublvl21,sublvl22,sublvl23,sublvl24,sublvl25,sublvl2_score,sublvl2_score_pcnt,sublvl2_score_zero,sublvl2_attempted,sublvl2_attempted_pcnt,g2_time_start,g2_enumerator,g2_gps_latitude,g2_gps_longitude,g2_gps_accuracy,addlvl2_4_strategy,addlvl2_4_explain,addlvl2_4_change,addlvl2_5_strategy,addlvl2_5_explain,addlvl2_5_change,sublvl2_3_strategy,sublvl2_3_explain,sublvl2_3_change,sublvl2_5_strategy,sublvl2_5_explain,sublvl2_5_change,word1,word2,word3,word4,word5,word6,relational_reason1,relational_reason1_incorrect,relational_reason2,relational_reason2_incorrect,relational_reason2_explain,relational_reason2_change,relational_reason3,relational_reason3_incorrect,relational_reason3_explain,relational_reason3_change,relational_reason4,relational_reason4_incorrect,relational_reason4_explain,relational_reason4_change,relational_reason5,relational_reason5_incorrect,spatial_think_3d1,spatial_think_3d1_incorrect,spatial_think_3d2,spatial_think_3d2_incorrect,spatial_think_3d3,spatial_think_3d3_incorrect,spatial_think_3d4,spatial_think_3d4_incorrect,invent_word_time_allowed,invent_word_autostop_rule,oral_read_time_allowed,oral_read_autostop_rule,sil_time_allowed,sq1,sq2,sq4,sq3_2,sq3_3,sq3_4,sq3_5,sq3_6,sq3_7,sq3_777,sq3_other,sq4_other,sq5_1,sq5_2,sq5_3,sq5_4,sq5_0,sq5_777,sq5_888,sq5_other,sq6_0,sq6_1,sq6_2,sq6_3,sq6_4,sq6_5,sq6_6,sq6_7,sq6_8,sq6_9,sq6_10,sq6_777,sq6_888,sq6_other,sq7,sq8,sq9,sq10,sq11_1,sq11_2,sq11_3,sq11_4,sq11_5,sq11_6,sq11_7,sq11_8,sq11_9,sq11_888,sq12,sq12_other,g2_time_end,sq3_1,invent_wordnumber_of_items_corr,invent_wordnumber_of_items_atte,oral_readnumber_of_items_correc,oral_readnumber_of_items_attemp,sil_readnumber_of_items_corr,sil_readnumber_of_items_atte,g2_date_char,g2_dayofweek,g2_day,g2_minutes_assess,word_score,word_score_pcnt,word_score_zero,word_score_attempted,word_score_attempted_pcnt,relational_reason_score,relational_reason_score_pcnt,relational_reason_score_zero,relational_reason_attempted,relational_reason_attempted_pcnt,spatial_think_3d_score,spatial_think_3d_score_pcnt,spatial_think_3d_score_zero,spatial_think_3d_attempted,spatial_think_3d_attempted_pcnt,g2_math_overall_score,g2_math_overall_score_pcnt,g2_math_overall_score_pcnt80,_merge_Master_G2,strata3,stage3,fpc3,wt3,wt123,sum_wt123,wt3_scale,wt_stage3,g2_orf_bm,wealthindex,q_wealthindex,timepoint,year,g2_orf_comp_bm,sh_1_1_new,sh_4_8,sh_11_new,sh_12_new,sh_13_new,sh_14_new,sh_15_new_1,sh_15_new_2,sh_15_new_3,sh_15_new_4,sh_15_new_777,sh_15_new_888,sh_15_other,archived,l10_new,l11_new_1,l11_new_2,l11_new_777,l11_new_888,l12_new,l13_new,l14_new,l15_new,l16_new_1,l16_new_2,l16_new_3,l16_new_4,l16_new_5,l16_new_777,l16_new_000,l16_new_888,i11_other,l16_other,l11_other,tq_33_new,tq_34_new_1,tq_34_new_2,tq_34_new_3,tq_34_new_4,tq_34_new_5,tq_34_new_6,tq_34_new_7,tq_34_new_000,tq_34_new_888,tq_35_new,tq_36_new,tq_37_new,tq_38_new,tq_39_new_1,tq_39_new_2,tq_39_new_3,tq_39_new_4,tq_39_new_5,tq_39_new_6,tq_39_new_000,tq_39_new_888,tq_40_new,tq_41_new,tq_42_new,tq_25_other,tq_34_new_777,tq_34_other,tq_39_new_777,tq_39_other,tq_20_other,location_schooldistrict_parent,location_schooldistrict_label,location_schooldistrict_id,location_schooldistrict_level,location_schoolschool_parent,location_schoolschool_id,location_schoolschool_level,ci_,invent_worditem_at_time,oral_readitem_at_time,sil_readitem_at_time,userprofileitem1female,strata1
1,Osh,Араванский,1S32310502,Kyrgyz,Kyrgyz,Rural,KRU,СШ им.С.Шарипова,Control,KRU,Kyrgyz,Russian,Uzbek,No,1S32310502-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,28,1,Mixed,5,5,2nd,NaN,8883,8677,50,17560,28,22,1,1,1,4/28/21 2:30,4/28/21 2:41,08:30,IISIEVA,40.5202934,72.4959869,3.900000095,Исиева,Инабат,Yes,0,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,Other,0,"Менторства бар. Сабактарга катышуу,алдынкы иш ...",Lesson planning,Methods of teaching mathematics,0,0,0,Use of new information technologies in teaching,0,Additional training and use of training mater...,0,0,NaN,0,0,Library,Internet,Joint meeting of teachers,0,0,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,0,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a year,2021-04-28,08:41,0,2021,4/28/2021,4/28/2021,Wed,4,28,11,Matched (3),1,4/28/21 4:00,4/28/21 4:06,IISIEVA,41,72,4,Yes,Female,YES,YES,20,YES,0,0,3rd grade,4th grade,0,Once every six months,Once a year,YES,Once a week,10:06,10:00,2021,4/28/2021,4/28/2021,Wed,4,28,6,Matched (3),74,5,297,1,4,1,4/28/21 2:54,4/28/21 3:10,08:54,IISIEVA,41,72,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),16-25 years,No,999,999,999,999,Once a week,0,0,0,0,0,0,None of the above,0,No,999,999,999,999,999,999,999,999,999,999,0,Oral assessment,Observations during the lesson,0,0,0,NaN,To assess,0,To plan / change further learning,0,0,0,0,Count to 20,0,Addition and subtraction of simple numbers up...,0,0,Solving Problems from Simple Life,0,0,End of 2nd grade,2nd grade,No,999,999,999,999,999,999,999,999,NaN,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,0,0,0,0,Geometric figures,Visual aids,0,0,Every lesson,NaN,No,999,999,999,999,999,999,999,999,999,NaN,999,NaN,0,Textbook,0,0,Online resources,0,0,0,0,I will show the solution of the problem / problem,Elementary school students can solve new probl...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,09:10,2021,4/28/2021,4/28/2021,Wed,4,28,16,In Both,1,4/28/21 4:14,4/28/21 4:21,10:14,IISIEVA,41,72,6,Kyrgyz,12,16,Blackboard,Chalk or whiteboard marker,0,0,Notebook,0,0,0,0,37,12,0,2,Yes,No,Yes,Row,10:21,NaN,2021,4/28/2021,4/28/2021,Wed,4,28,6,In Both,2nd,1S32310502-Kyr_2,1,1,5,4,1,No,No,Correct,888,Incorrect,Incorrect,888,1,20,Proportion > 0 Correct,5,20,2021,April,4/28/2021,MXGYEW,Female,8,4/28/21 4:08,4/28/21 4:34,Yes,0,3,No,No,Incorrect,Incorrect,Incorrect,Incorrect,Incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0,Proportion = 0 Correct,Yes,5,0,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,Incorrect,Incorrect,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,5,Proportion > 0 Correct,No,9,33,NaN,NaN,NaN,NaN,NaN,0,0,Proportion = 0 Correct,0,0,Correct,No Answer,Incorrect,No Answer,No Answer,1,20,Proportion > 0 Correct,5,20,Incorrect,Correct,Incorrect,Correct,Incorrect,No Answer,Incorrect,Correct,Incorrect,Incorrect,3,30,Proportion > 0 Correct,10,30,Correct,Correct,Correct,Incorrect,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Incorrect,Incorrect,3,60,Proportion > 0 Correct,5,60,10:08,MUHAMMET,40.5201917,72.4956256,7.504000187,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,1,In the mind / mouth (the student is thinking o...,0,In the mind / mouth (the student is thinking o...,Answers in a different way (I just figured it ...,No,In writing,Issued the report in column form (for example ...,No,Correct,Incorrect,Correct,NaN,Incorrect,Correct,Correct,999,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,48,Answers in a different way (I just liked it),No,Incorrect,18,Answers in a different way (I just liked it),No,Incorrect,87,Correct,999,Correct,999,Incorrect,8,Incorrect,4,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,Uzbek,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,2-3 times a week,Yes,TV,0,0,Toilet inside the house,Smartphone,0,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,10:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/28/2021,Wed,28,26,3,50,Score>0,5,60,2,40,Score>0,5,40,2,50,Score>0,4,50,17,49,No,Matched (3),Female,MXGYEW,16,3,15,8314,1,16,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz
2,Osh_city,г. Ош,013RTICODE,Kyrgyz,Kyrgyz,Urban,KR,№2 К. Маркса,Control,KR,Kyrgyz,Russian,No,No,013RTICODE-Kyr-2021,278,G2 Assessed,G4 Assessed,10,10,8883,5,5,1,37,1,Mixed,7,3,2nd,NaN,8883,8677,81,17560,37,44,1,1,1,4/22/21 4:51,4/22/21 4:59,10:51,JTOKTOSHEVA,40.5064858,72.8229702,7.074999809,Мамасадыковна,Жамила,Yes,1,Head of the Department of Primary Education,NaN,Once a week,Advice on teaching methods,0,0,0,0,0,NaN,0,0,Methods of teaching literature,0,0,0,0,0,Other,0,Каллиграфии б ча кайрылышат,0,0,Library,Internet,0,0,School administration,0,0,NaN,Yes,Once a week,Yes,Lesson plans improved,Teachers started to apply new strategies for ...,0,Content of teaching materials improved,Teachers began to use additional resource mat...,0,Yes,Once a quarter,2021-04-22,10:59,0,2021,4/22/2021,4/22/2021,Thu,4,22,9,Matched (3),1,4/22/21 5:40,4/22/21 5:43,JTOKTOSHEVA,41,73,7,Yes,Female,YES,YES,40,YES,1st grade,2nd grade,3rd grade,4th grade,0,Once a week,Once a month,YES,Once a month,11:43,11:40,2021,4/22/2021,4/22/2021,Thu,4,22,3,Matched (3),74,3,297,1,3,1,4/22/21 5:18,4/22/21 5:35,11:18,JTOKTOSHEVA,41,73,4,Yes,Female,Kyrgyz,NaN,Higher education (professional diploma),9-15 years,No,999,999,999,999,Once a month,Improving lesson plans,New strategies for teaching mathematics,New strategies for teaching literature,0,0,0,0,0,No,999,999,999,999,999,999,999,999,999,999,Written tests,Oral assessment,Observations during the lesson,Homework,0,0,NaN,To assess,To assess the student's mastery of the subject,0,Feedback to the student,0,0,Count to 10,0,0,0,0,0,0,0,0,End of 3rd grade,2nd grade,Yes,0,Literary reading competitions and festivals,0,0,0,0,Other,0,Энелердин майрамы,0,Children's books (additional study materials),0,Video lessons from the Internet / YouTube,0,0,0,NaN,Yes,Counting sticks,0,0,Geometric board,Geometric figures,Visual aids,0,0,Every lesson,NaN,Yes,0,Children's books,Visual aids,0,0,Didactic materials,0,0,0,NaN,Twice a week,NaN,0,Textbook,Information literature,Guidelines for teachers,Online resources,Lesson plans for other teachers,0,0,0,I will explain the new topic,Primary school students should always be shown...,Getting the right answer is the most important...,Some students are naturally better at math tha...,Accounting / manipulative tools can be used in...,Discussion of incorrect answers is important.,Students should ask a question if they do not ...,11:35,2021,4/22/2021,4/22/2021,Thu,4,22,17,In Both,1,4/22/21 4:36,4/22/21 4:40,10:36,JTOKTOSHEVA,41,73,5,Kyrgyz,15,20,Blackboard,Chalk or whiteboard marker,0,Pencil or pencil,Notebook,0,0,Lesson plan / lesson results,0,54,14,2,24,Yes,Yes,Yes,Row,10:40,NaN,2021,4/22/2021,4/22/2021,Thu,4,22,4,In Both,2nd,013RTICODE-Kyr_2,1,1,3,3,1,No,No,Correct,Correct,Incorrect,Incorrect,Incorrect,2,40,Proportion > 0 Correct,5,40,2021,April,4/22/2021,AQSAQP,Male,8,4/22/21 4:45,4/22/21 5:09,Yes,31,30,No,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,0,62,Proportion > 0 Correct,No,32,97,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,0,54,Proportion > 0 Correct,No,30,100,Correct,Correct,NaN,NaN,NaN,2,40,Proportion > 0 Correct,2,100,Correct,Correct,Incorrect,Correct,Correct,4,80,Proportion > 0 Correct,5,80,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Correct,Incorrect,9,90,Proportion > 0 Correct,10,90,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,Correct,Correct,Correct,Correct,Correct,5,100,Proportion > 0 Correct,5,100,10:45,GDOSMATOVA,40.5065752,72.8232433,4.288000107,In writing,Issued the report in column form (for example ...,No,2,In the mind / mouth (the student is thinking o...,0,In writing,Divides numbers into components in some way,No,In writing,Issued the report in column form (for example ...,No,Correct,Correct,Correct,Correct,Correct,Correct,Correct,999,Correct,999,Reflected using numbers,No,Correct,999,Add / subtract numbers in the order given in t...,No,Correct,999,Add / subtract numbers in the order given in t...,No,Incorrect,26,Correct,999,Correct,999,Correct,999,Correct,999,60,5,60,10,180,Yes,Yes,in Kyrgyz,0,0,0,0,0,0,0,NaN,NaN,Praises me,0,Gives a good grade,0,0,0,0,NaN,0,0,0,0,0,Gives a bad grade,0,0,0,0,0,0,0,NaN,Yes,Yes,Once a week,Yes,TV,Bicycle,Car,Toilet inside the house,Smartphone,Computer,Internet,Washing machine,Electric heater,0,From a tap inside the house,NaN,11:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,Thu,22,24,6,100,Score>0,6,100,4,80,Score>0,5,80,4,100,Score>0,4,100,33,94,Yes,Matched (3),Male,AQSAQP,15,3,9,8314,1,9,orf<40,1,Highest,Baseline,2021,orf<40 and/or read comp <80%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021--Comparison Kyrgyz

In [27]:
#Let's get this ordered alphabetically
base.sort_values(by='region',ascending=True,inplace=True)

<ipython-input-27-ce4a05c3bb33>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base.sort_values(by='region',ascending=True,inplace=True)

In [28]:
base['oral_read_score_pcnt'] = base['oral_read_score_pcnt'].fillna(0).round().astype(int)
base['oral_read_score_pcnt'].value_counts('')

<ipython-input-28-0d27f7ab883d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['oral_read_score_pcnt'] = base['oral_read_score_pcnt'].fillna(0).round().astype(int)

oral_read_score_pcnt
100    424
98     226
96     120
70      58
94      50
      ...
69       3
31       3
56       2
97       2
33       2
Name: count, Length: 95, dtype: int64

oral_read_score_pcnt	- DONE
g2_math_overall_score_pcnt - DONE

Now let's do some coding to clean up these remaining items that either could have NaN or odd numbers. let's go one by one.

oral_read_attempted_pcnt
read_comp_score_pcnt
word_score
word_score_pcnt
invent_word_score_pcnt

In [29]:
base['oral_read_attempted_pcnt'].value_counts('')
#same issue

oral_read_attempted_pcnt
100.0    571
100      399
98       205
98       134
96       134
        ...
66         1
63         1
47         1
36.0       1
38.0       1
Name: count, Length: 121, dtype: int64

In [30]:
base['oral_read_attempted_pcnt'] = base['oral_read_attempted_pcnt'].fillna(0).round().astype(int)
base['oral_read_attempted_pcnt'].value_counts()

<ipython-input-30-d097bc5717a9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['oral_read_attempted_pcnt'] = base['oral_read_attempted_pcnt'].fillna(0).round().astype(int)

oral_read_attempted_pcnt
100    970
98     339
96     202
97     116
95     115
      ...
29       1
45       1
49       1
66       1
36       1
Name: count, Length: 71, dtype: int64

In [31]:
base['read_comp_score_pcnt'].value_counts()

read_comp_score_pcnt
100.0    290
20       265
80.0     265
40.0     262
60       251
0.0      225
80       197
20       179
100      174
60       168
0        161
40       143
Name: count, dtype: int64

In [32]:
base['read_comp_score_pcnt'] = base['read_comp_score_pcnt'].fillna(0).round().astype(int)
base['read_comp_score_pcnt'].value_counts()
#looks cleaner to me!
base['list_comp_score_pcnt'] = base['list_comp_score_pcnt'].fillna(0).round().astype(int)
base['list_comp_score_pcnt'].value_counts()

<ipython-input-32-4d165f29d670>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['read_comp_score_pcnt'] = base['read_comp_score_pcnt'].fillna(0).round().astype(int)

read_comp_score_pcnt
100    464
80     462
20     444
60     419
40     405
0      388
Name: count, dtype: int64

<ipython-input-32-4d165f29d670>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['list_comp_score_pcnt'] = base['list_comp_score_pcnt'].fillna(0).round().astype(int)

list_comp_score_pcnt
100    661
80     589
60     517
40     343
0      257
20     215
Name: count, dtype: int64

In [33]:
base['word_score'].value_counts()
#what is going on here.
base['word_score'].dtype

word_score
4    308
3    288
6    274
5    272
2    206
3    196
2    186
1    173
4    172
5    171
1    142
6    127
0     38
0     29
Name: count, dtype: int64

dtype('O')

In [34]:
base['word_score'] = base['word_score'].fillna(0).round().astype(int)
base['word_score'].value_counts() #better!

<ipython-input-34-b759158afdb2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['word_score'] = base['word_score'].fillna(0).round().astype(int)

word_score
3    484
4    480
5    443
6    401
2    392
1    315
0     67
Name: count, dtype: int64

In [35]:
base['word_score_pcnt'].value_counts()

word_score_pcnt
67     308
50     288
100    274
83     272
33     206
50     196
33     186
17     173
67     172
83     171
17     142
100    127
0       38
0       29
Name: count, dtype: int64

In [36]:
base['word_score_pcnt'] = base['word_score_pcnt'].fillna(0).round().astype(int)
base['word_score_pcnt'].value_counts() #much cleaner!

<ipython-input-36-6d9ff4f1bd4b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['word_score_pcnt'] = base['word_score_pcnt'].fillna(0).round().astype(int)

word_score_pcnt
50     484
67     480
83     443
100    401
33     392
17     315
0       67
Name: count, dtype: int64

In [37]:
base['invent_word_score_pcnt'].value_counts()

invent_word_score_pcnt
46.0    52
62      50
94      46
48.0    46
54      45
        ..
10       8
2        7
4        7
8.0      7
6        6
Name: count, Length: 102, dtype: int64

In [38]:
base['invent_word_score_pcnt'] = base['invent_word_score_pcnt'].fillna(0).round().astype(int)
base['invent_word_score_pcnt'].value_counts() #fixed!

<ipython-input-38-0719fad180d7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['invent_word_score_pcnt'] = base['invent_word_score_pcnt'].fillna(0).round().astype(int)

invent_word_score_pcnt
46     78
64     76
56     75
60     75
62     73
54     72
98     70
52     69
44     68
42     67
48     67
66     67
40     67
38     67
34     66
100    66
70     65
50     64
68     63
58     62
94     60
76     58
96     58
32     58
74     57
36     56
72     53
30     52
80     48
82     47
84     45
92     42
26     39
88     39
0      38
78     37
86     37
22     36
24     36
18     36
90     35
28     34
14     32
20     28
16     25
4      25
12     22
10     21
2      19
8      17
6      15
Name: count, dtype: int64

In [39]:
base['invent_word_score'] = base['invent_word_score'].fillna(0).round().astype(int)
base['word_score'] = base['word_score'].fillna(0).round().astype(int)
base['oral_read_score'] = base['oral_read_score'].fillna(0).round().astype(int)

<ipython-input-39-8c860fde7447>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['invent_word_score'] = base['invent_word_score'].fillna(0).round().astype(int)
<ipython-input-39-8c860fde7447>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['word_score'] = base['word_score'].fillna(0).round().astype(int)
<ipython-input-39-8c860fde7447>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['oral_read_score'] = base['oral_read_score'].fillna(0).round().astype(int)

In [40]:
 #subset
 base = base[[
    'region',
    'district',
    'language',
    'urbanrural',
    'female',
    'age',
    'g2_year',
    'oral_read_score',
    'oral_read_score_pcnt',
    'read_comp_score_pcnt',
    'word_score',
    'word_score_pcnt',
    'invent_word_score',
    'invent_word_score_pcnt',
    'list_comp_score_pcnt',
    ]]
base

,region,district,language,urbanrural,female,age,g2_year,oral_read_score,oral_read_score_pcnt,read_comp_score_pcnt,word_score,word_score_pcnt,invent_word_score,invent_word_score_pcnt,list_comp_score_pcnt
385,Batken,Кадамжайский,Kyrgyz,Rural,Female,8,2021,55,98,100,2,33,48,96,40
1136,Batken,Баткенский,Kyrgyz,Rural,Female,9,2021,26,46,40,2,33,24,48,60
1138,Batken,Баткенский,Kyrgyz,Rural,Female,9,2021,56,100,100,3,50,23,46,80
272,Batken,Кадамжайский,Kyrgyz,Rural,Female,8,2021,56,100,100,2,33,48,96,100
1140,Batken,Баткенский,Kyrgyz,Rural,Female,8,2021,29,52,40,4,67,20,40,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,Talas,Бакай-Атинский,Russian,Rural,Female,9,2021,23,43,20,1,17,22,44,0
1642,Talas,Кара-Бууринский,Kyrgyz,Rural,Male,8,2021,21,38,20,6,100,18,36,60
799,Talas,Бакай-Атинский,Russian,Rural,Male,7,2021,37,70,20,5,83,35,70,40
778,Talas,Кара-Бууринский,Russian,Rural,Female,7,2021,45,85,80,4,67,26,52,80
550,Talas,Бакай-Атинский,Kyrgyz,Rural,Female,8,2021,47,84,80,5,83,20,40,40

# EGRA Initial Tables and Graphs

##Sample Distribution by region and language
1. By Region, we have a relatively healthy sample size that is repreresentative enough to compare between regions. All good here!
2. By language, a few items jump out as concerns.
  **Osh City** having only 10 uzbek test takers. This makes it unlikely (this is one school) that we can make any statements on the Uzbek/Osh City grouping.  Were uzbek grade 2 students making the choice to do Kyrgyz or Russian instead of their native language - and did that bring scores down in this region?
  **Osh** only having 40 test takers in Uzbek. This is enough, but at the same time this isn't seemingly representative of the demographic breakdown. Did individuals who speak Uzbek at home take tests in Kyrgyz and Russian?
  **Naryn** having only 16 test takers in Russian means it isn't likely we can review this language/region group

3. Noting, in the EGRA 2021 Baselinereport the team indicates that all Uzbek language schools were visited in country, and this would be a first time assessment of Uzbek schools. The authors warn about drawing larger representative conclusions on Uzbek performance compared to Kyrgyz and Russian due to the change in sample size. Batken however has a sizeable and appropriate sample size, as does Jalal-Abad, and to a much lesser extent, Osh. The literature further indicates that in the south, as a result of the reduction of status of Uzbek language in the country (removal from NST testing options, reduced uzbek language options, focus on krygyz as official language over Russian, while Russian being a language of economic opportunity) - more uzbek students speak uzbek at home, but take classes in other languages.

In [41]:
baselinecount = base.groupby(by=['region','language']).size().rename('count')
baselinecount

region      language
Batken      Kyrgyz      140
            Russian      38
            Tajik        30
            Uzbek        93
Bishkek     Kyrgyz      129
            Russian     189
Chui        Kyrgyz      197
            Russian     144
Issyk-Kul   Kyrgyz      166
            Russian      64
Jalal-Abad  Kyrgyz      311
            Russian     159
            Uzbek       110
Naryn       Kyrgyz       80
            Russian      16
Osh         Kyrgyz      283
            Russian     114
            Uzbek        40
Osh_city    Kyrgyz       19
            Russian     110
            Uzbek        10
Talas       Kyrgyz      100
            Russian      40
Name: count, dtype: int64

In [42]:
title = "Sample Distribution by Region & Language"

# Saving the DataFrame to a CSV file
filename = 'baselinecount_with_title.csv'
with open(filename, 'w') as f:
    f.write(title + '\n')  # Add the title first
    baselinecount.to_csv(f, index=True)

41

In [43]:
files.download('baselinecount_with_title.csv')

##Average Score by Region & Language, Pivot Table
A bunch of interesting items pop out here.
1. Oral Reading Subtask + Benchmark Percentages
2. Reading Comprehension + Benchmark Percentages
3. Silent Reading:
4. Invented Word Score:
5. Listening Score:

In [86]:
oral_read_score_gt_30 = base[base['oral_read_score'] > 30].groupby(['region', 'language']).size() / base.groupby(['region', 'language']).size()

read_comp_score_80 = base[base['read_comp_score_pcnt'] >= 80].groupby(['region', 'language']).size() / base.groupby(['region', 'language']).size()

# Create the pivot table
baselinemean = base.pivot_table(
    index=['region', 'language'],
    values=[
        'oral_read_score_pcnt',
        'read_comp_score_pcnt',
        'word_score_pcnt',

    ],
    aggfunc='mean'
)

# Add the proportions as new columns to the pivot table
baselinemean['oral_read_score_gt_30'] = oral_read_score_gt_30
baselinemean['read_comp_score_80'] = read_comp_score_80

# Round the results
baselinemean = baselinemean.round(2)
baselinemean

                     oral_read_score_pcnt  read_comp_score_pcnt  \
region     language
Batken     Kyrgyz                   78.71                 64.14
           Russian                  54.21                 27.37
           Tajik                    65.70                 41.33
           Uzbek                    83.20                 82.80
Bishkek    Kyrgyz                   78.66                 63.41
           Russian                  90.30                 79.89
Chui       Kyrgyz                   71.76                 58.88
           Russian                  72.76                 46.11
Issyk-Kul  Kyrgyz                   76.13                 59.64
           Russian                  70.05                 58.75
Jalal-Abad Kyrgyz                   58.68                 45.72
           Russian                  61.77                 34.72
           Uzbek                    46.75                 40.00
Naryn      Kyrgyz                   70.55                 56.50
           Russian                  83.12                 60.00
Osh        Kyrgyz                   54.58                 37.95
           Russian                  48.84                 18.95
           Uzbek                    70.62                 66.00
Osh_city   Kyrgyz                   69.84                 61.05
           Russian                  71.86                 46.36
           Uzbek                    45.60                 46.00
Talas      Kyrgyz                   74.49                 56.00
           Russian                  73.95                 49.00

                     word_score_pcnt  oral_read_score_gt_30  \
region     language
Batken     Kyrgyz              54.16                   0.77
           Russian             37.34                   0.37
           Tajik               72.23                   0.70
           Uzbek               87.72                   0.83
Bishkek    Kyrgyz              57.89                   0.80
           Russian             65.68                   0.95
Chui       Kyrgyz              78.37                   0.71
           Russian             48.86                   0.74
Issyk-Kul  Kyrgyz              54.92                   0.77
           Russian             56.52                   0.72
Jalal-Abad Kyrgyz              60.85                   0.56
           Russian             47.72                   0.55
           Uzbek               61.69                   0.43
Naryn      Kyrgyz              62.06                   0.68
           Russian             70.81                   0.94
Osh        Kyrgyz              48.19                   0.50
           Russian             33.39                   0.38
           Uzbek               88.30                   0.70
Osh_city   Kyrgyz              78.05                   0.63
           Russian             55.32                   0.75
           Uzbek               55.10                   0.30
Talas      Kyrgyz              64.80                   0.76
           Russian             53.30                   0.72

                     read_comp_score_80
region     language
Batken     Kyrgyz                  0.51
           Russian                 0.05
           Tajik                   0.23
           Uzbek                   0.71
Bishkek    Kyrgyz                  0.52
           Russian                 0.74
Chui       Kyrgyz                  0.46
           Russian                 0.20
Issyk-Kul  Kyrgyz                  0.46
           Russian                 0.34
Jalal-Abad Kyrgyz                  0.32
           Russian                 0.16
           Uzbek                   0.14
Naryn      Kyrgyz                  0.39
           Russian                 0.25
Osh        Kyrgyz                  0.25
           Russian                 0.05
           Uzbek                   0.42
Osh_city   Kyrgyz                  0.53
           Russian                 0.22
           Uzbek                   0.10
Talas      Kyrgyz                  0.41
           Russian                 0.25

In [87]:
# prompt: organize baseline mean columns as such: Oral_read_score_pcnt, oral_read_score_gt_40, read_comp_score_pcnt, read_comp_score_80, word_score_pcnt

# Reorder columns in baselinemean DataFrame
baselinemean = baselinemean[[
    'oral_read_score_pcnt',
    'oral_read_score_gt_30',
    'read_comp_score_pcnt',
    'read_comp_score_80',
    'word_score_pcnt'
]]

baselinemean

                     oral_read_score_pcnt  oral_read_score_gt_30  \
region     language
Batken     Kyrgyz                   78.71                   0.77
           Russian                  54.21                   0.37
           Tajik                    65.70                   0.70
           Uzbek                    83.20                   0.83
Bishkek    Kyrgyz                   78.66                   0.80
           Russian                  90.30                   0.95
Chui       Kyrgyz                   71.76                   0.71
           Russian                  72.76                   0.74
Issyk-Kul  Kyrgyz                   76.13                   0.77
           Russian                  70.05                   0.72
Jalal-Abad Kyrgyz                   58.68                   0.56
           Russian                  61.77                   0.55
           Uzbek                    46.75                   0.43
Naryn      Kyrgyz                   70.55                   0.68
           Russian                  83.12                   0.94
Osh        Kyrgyz                   54.58                   0.50
           Russian                  48.84                   0.38
           Uzbek                    70.62                   0.70
Osh_city   Kyrgyz                   69.84                   0.63
           Russian                  71.86                   0.75
           Uzbek                    45.60                   0.30
Talas      Kyrgyz                   74.49                   0.76
           Russian                  73.95                   0.72

                     read_comp_score_pcnt  read_comp_score_80  word_score_pcnt
region     language
Batken     Kyrgyz                   64.14                0.51            54.16
           Russian                  27.37                0.05            37.34
           Tajik                    41.33                0.23            72.23
           Uzbek                    82.80                0.71            87.72
Bishkek    Kyrgyz                   63.41                0.52            57.89
           Russian                  79.89                0.74            65.68
Chui       Kyrgyz                   58.88                0.46            78.37
           Russian                  46.11                0.20            48.86
Issyk-Kul  Kyrgyz                   59.64                0.46            54.92
           Russian                  58.75                0.34            56.52
Jalal-Abad Kyrgyz                   45.72                0.32            60.85
           Russian                  34.72                0.16            47.72
           Uzbek                    40.00                0.14            61.69
Naryn      Kyrgyz                   56.50                0.39            62.06
           Russian                  60.00                0.25            70.81
Osh        Kyrgyz                   37.95                0.25            48.19
           Russian                  18.95                0.05            33.39
           Uzbek                    66.00                0.42            88.30
Osh_city   Kyrgyz                   61.05                0.53            78.05
           Russian                  46.36                0.22            55.32
           Uzbek                    46.00                0.10            55.10
Talas      Kyrgyz                   56.00                0.41            64.80
           Russian                  49.00                0.25            53.30

##Violin Charts - Distribution by Subtask

In [111]:
# Define the subtask (column name)
subtask = "oral_read_score_pcnt"

# Filter dataframe for only this subtask
oralread = base[["region", subtask]].dropna()  # Remove missing values

# Create violin plot with embedded boxplots
fig = px.violin(
    oralread,
    x="region",
    y=subtask,
    color="region",
    box=True,               # show internal boxplot
    points="all",           # show all datapoints
)
# 🧠 Here's the working hack to add black outlines to the boxplots
for trace in fig.data:
    if trace.type == 'violin':
        trace.box = dict(line=dict(color='black'))

fig.update_layout(
    yaxis_title="Score",
    paper_bgcolor="white",
    font=dict(color="black"),  # Global font color for all text elements
    legend=dict(
        font=dict(size=20),         # Increase legend item font size
    ),
    xaxis=dict(
        tickfont=dict(size=20),     # Increase y-axis tick label font size
    )
)

In [112]:
# Define the subtask (column name)
subtask2 = "read_comp_score_pcnt"

# Filter dataframe for only this subtask
readcomp = base[["region", subtask2]].dropna()

# Create the violin plot
fig = px.violin(readcomp, x="region", y=subtask2, color="region",
                box=True,
                points="all",
                title=f"Score Distribution for {subtask2} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)
# 🧠 Here's the working hack to add black outlines to the boxplots
for trace in fig.data:
    if trace.type == 'violin':
        trace.box = dict(line=dict(color='black'))

fig.update_layout(
    yaxis_title="Score",
    paper_bgcolor="white",
    font=dict(color="black"),  # Global font color for all text elements
    legend=dict(
        font=dict(size=20),         # Increase legend item font size
    ),
    xaxis=dict(
        tickfont=dict(size=20),     # Increase y-axis tick label font size
    )
)

In [113]:
# Define the subtask (column name)
subtask3 = "word_score_pcnt"

# Filter dataframe for only this subtask
wordscore = base[["region", subtask3]].dropna()  # Remove missing values

# Create the violin plot
fig = px.violin(wordscore, x="region", y=subtask3, color="region",
                box=True,  # Adds a mini box plot inside
                points="all",  # Show all data points
                title=f"Score Distribution for {subtask3} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)
# 🧠 Here's the working hack to add black outlines to the boxplots
for trace in fig.data:
    if trace.type == 'violin':
        trace.box = dict(line=dict(color='black'))

fig.update_layout(
    yaxis_title="Score",
    paper_bgcolor="white",
    font=dict(color="black"),  # Global font color for all text elements
    legend=dict(
        font=dict(size=20),         # Increase legend item font size
    ),
    xaxis=dict(
        tickfont=dict(size=20),     # Increase y-axis tick label font size
    )
)

In [48]:
# Define the subtask (column name)
subtask4 = "invent_word_score_pcnt"

# Filter dataframe for only this subtask
inventwordscore = base[["region", subtask4]].dropna()  # Remove missing values

# Create the violin plot
fig = px.violin(inventwordscore, x="region", y=subtask4, color="region",
                box=True,  # Adds a mini box plot inside
                points="all",  # Show all data points
                title=f"Score Distribution for {subtask4} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

In [49]:
# Define the subtask (column name)
subtask5 = 'list_comp_score_pcnt'


# Filter dataframe for only this subtask
wordscore = base[["region", subtask5]].dropna()  # Remove missing values

# Create the violin plot
fig = px.violin(wordscore, x="region", y=subtask5, color="region",
                box=True,  # Adds a mini box plot inside
                points="all",  # Show all data points
                title=f"Score Distribution for {subtask5} Across Regions")

# Customize appearance
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Score",
    legend_title="Region",
    paper_bgcolor="white",
    font=dict(color="black")
)

**Oral Reading Score**
We can see that Bishkek has one heck of a tail at the upper end, almost looks like a glassblowers pipe! And the box plot is super tight!

Other regions have similar candles, with the distribution towards the top.
The interesting outliers here appear to be Jalal-Abad, Osh, and Osh City. These three , in reviewing the box plot, have a much wider range and we can see don't have the "tail" appearing at the end of the violin chart. Definitely something up with these three regions as a whole!

**Invented Word**
Aside from Bishkek, we're seeing a pretty standard distribution across the board.

**Reading Comp Score Review**
Reading comprehension followed the story/oral reading score.
If students did not fail to read the first line of words, they would be asked questions. If they did not reach certain parts of the story in time, they might not be asked certain questions.
We would expect, as a result, the results might be a bit smoother as some students wouldn't get as far along to receive the next reading comprehension question.

Osh, Talas, and Jalal Abad show a strong concentration and grouping at the bottom of the violin chart. Osh especially is showing some interesting, and perhaps troubling, results. The other regions appear to have a more normal distribution in comparison.

**Word Score Pcnt**
This subtask involved silent reading comprehension.
We're seeing similar patterns to the prior two. However, a really, really interesting note is that the students in Chui seemed to have done a bit better, with a wider distribution than all the other regions, even Bishkek, which did an amazing job on the oral reading and oral reading comprehension questions compared to the other regions. Interesting!

#Statistics

##Two Way ANOVA - between region and language

To summarize the tests run below; a two way ANOVA run on each subtask shows that 1. Region is significant 2. Language is significant. and 3, and most importantly: the interaction between region and language is significant, and differs by region. This is true for all subtasks.

This means I need to follow up digging into each region to see where language is, and isn't, significant.

###Oral Reading Score Two Way ANOVA

In [115]:
# Fit the two-way ANOVA model
model = ols('oral_read_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Convert the ANOVA table into a DataFrame (if it's not already)
anovaoralreadtwo = pd.DataFrame(anova_table)
anovaoralreadtwo

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 8, but rank is 3

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 3, but rank is 2

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 24, but rank is 11

                             sum_sq      df          F        PR(>F)
C(region)              1.521914e+05     8.0  25.881604  1.723810e-16
C(language)            3.910900e+04     3.0  17.735627  2.240837e-08
C(region):C(language)  1.617795e+05    24.0   9.170720  2.674677e-16
Residual               1.880959e+06  2559.0        NaN           NaN

###Reading Comprehension Two Way ANOVA

In [116]:
# Fit the two-way ANOVA model
model = ols('read_comp_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Convert the ANOVA table into a DataFrame (if it's not already)
anovareadcomptwo = pd.DataFrame(anova_table)
anovareadcomptwo

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 8, but rank is 3

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 3, but rank is 2

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 24, but rank is 11

                             sum_sq      df          F        PR(>F)
C(region)              2.573905e+05     8.0  34.018029  1.485599e-21
C(language)            1.137836e+05     3.0  40.101912  7.100919e-18
C(region):C(language)  3.066201e+05    24.0  13.508152  1.808191e-25
Residual               2.420270e+06  2559.0        NaN           NaN

###Silent Reading Comprehension Two Way ANOVA

In [117]:
# Fit the two-way ANOVA model
model = ols('word_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

silentreadcomptwo = pd.DataFrame(anova_table)
silentreadcomptwo

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 8, but rank is 3

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 3, but rank is 2

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 24, but rank is 11

                             sum_sq      df          F        PR(>F)
C(region)              1.242209e+05     8.0  23.806973  3.408629e-15
C(language)            1.781513e+05     3.0  91.047306  6.340733e-39
C(region):C(language)  3.112415e+05    24.0  19.883171  5.565458e-39
Residual               1.669056e+06  2559.0        NaN           NaN

###Invented Word Score Two Way ANOVA

In [53]:
# Fit the two-way ANOVA model
model = ols('invent_word_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

                             sum_sq      df          F        PR(>F)
C(region)              7.180573e+04     8.0  15.407385  6.198169e-10
C(language)            1.381784e+04     3.0   7.906397  3.774511e-04
C(region):C(language)  6.565134e+04    24.0   4.695611  3.761868e-07
Residual               1.490769e+06  2559.0        NaN           NaN

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 8, but rank is 3

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 3, but rank is 2

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 24, but rank is 11

###List Comp Score Two Way ANOVA

In [54]:
# Fit the two-way ANOVA model
model = ols('list_comp_score_pcnt ~ C(region) + C(language) + C(region):C(language)', data=base).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Print the ANOVA table
print(anova_table)

                             sum_sq      df           F        PR(>F)
C(region)              4.338827e+04     8.0    7.343190  6.714720e-05
C(language)            4.100092e+05     3.0  185.043889  8.746655e-76
C(region):C(language)  3.580294e+05    24.0   20.198068  1.204970e-39
Residual               1.890026e+06  2559.0         NaN           NaN

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 8, but rank is 3

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 3, but rank is 2

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:1894: ValueWarning:

covariance of constraints does not have full rank. The number of constraints is 24, but rank is 11

##Tukey Test - Significance Between Regions (not reviewing language)

###Oral Reading Score - Regions - Tukey Test

In [55]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['oral_read_score_pcnt'], base['region'])

# Print results
print(tukey_results)
oralregtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
oralregtukey

     Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================
  group1     group2   meandiff p-adj   lower    upper   reject
--------------------------------------------------------------
    Batken    Bishkek   9.8677 0.0003   2.9797  16.7556   True
    Batken       Chui  -3.5262 0.7963 -10.3002   3.2478  False
    Batken  Issyk-Kul  -1.2718 0.9999  -8.7732   6.2295  False
    Batken Jalal-Abad -18.4454    0.0   -24.53 -12.3609   True
    Batken      Naryn  -3.0651 0.9901 -13.1047   6.9745  False
    Batken        Osh -21.1572    0.0 -27.5729 -14.7415   True
    Batken   Osh_city  -6.0131 0.4561 -14.7968   2.7705  False
    Batken      Talas  -1.3752 0.9999 -10.1374   7.3869  False
   Bishkek       Chui -13.3939    0.0  -20.071  -6.7167   True
   Bishkek  Issyk-Kul -11.1395 0.0001 -18.5535  -3.7255   True
   Bishkek Jalal-Abad -28.3131    0.0 -34.2897 -22.3365   True
   Bishkek      Naryn -12.9328 0.0019 -22.9073  -2.9583   True
   Bishkek        Osh -31.0248    0.0 -37.3382 -24.7115   True
   Bishkek   Osh_city -15.8808    0.0   -24.59  -7.1716   True
   Bishkek      Talas -11.2429  0.002 -19.9304  -2.5554   True
      Chui  Issyk-Kul   2.2544 0.9894  -5.0539   9.5627  False
      Chui Jalal-Abad -14.9192    0.0 -20.7642  -9.0743   True
      Chui      Naryn   0.4611    1.0  -9.4351  10.3573  False
      Chui        Osh  -17.631    0.0 -23.8199 -11.4421   True
      Chui   Osh_city  -2.4869 0.9932 -11.1063   6.1325  False
      Chui      Talas    2.151 0.9975  -6.4465  10.7484  False
 Issyk-Kul Jalal-Abad -17.1736    0.0 -23.8479 -10.4993   True
 Issyk-Kul      Naryn  -1.7933 0.9998 -12.2009   8.6143  False
 Issyk-Kul        Osh -19.8854    0.0 -26.8628 -12.9079   True
 Issyk-Kul   Osh_city  -4.7413 0.8054 -13.9433   4.4607  False
 Issyk-Kul      Talas  -0.1034    1.0  -9.2849   9.0781  False
Jalal-Abad      Naryn  15.3803    0.0   5.9427   24.818   True
Jalal-Abad        Osh  -2.7117 0.8307  -8.1373   2.7138  False
Jalal-Abad   Osh_city  12.4323 0.0001   4.3435  20.5211   True
Jalal-Abad      Talas  17.0702    0.0   9.0048  25.1356   True
     Naryn        Osh -18.0921    0.0 -27.7465  -8.4376   True
     Naryn   Osh_city   -2.948 0.9967 -14.3146   8.4186  False
     Naryn      Talas   1.6899 0.9999  -9.6601  13.0399  False
       Osh   Osh_city  15.1441    0.0   6.8034  23.4848   True
       Osh      Talas  19.7819    0.0  11.4639     28.1   True
  Osh_city      Talas   4.6379 0.8967   -5.618  14.8937  False
--------------------------------------------------------------

        group1      group2  meandiff   p-adj    lower    upper  reject
0       Batken     Bishkek    9.8677  0.0003   2.9797  16.7556    True
1       Batken        Chui   -3.5262  0.7963 -10.3002   3.2478   False
2       Batken   Issyk-Kul   -1.2718  0.9999  -8.7732   6.2295   False
3       Batken  Jalal-Abad  -18.4454  0.0000 -24.5300 -12.3609    True
4       Batken       Naryn   -3.0651  0.9901 -13.1047   6.9745   False
5       Batken         Osh  -21.1572  0.0000 -27.5729 -14.7415    True
6       Batken    Osh_city   -6.0131  0.4561 -14.7968   2.7705   False
7       Batken       Talas   -1.3752  0.9999 -10.1374   7.3869   False
8      Bishkek        Chui  -13.3939  0.0000 -20.0710  -6.7167    True
9      Bishkek   Issyk-Kul  -11.1395  0.0001 -18.5535  -3.7255    True
10     Bishkek  Jalal-Abad  -28.3131  0.0000 -34.2897 -22.3365    True
11     Bishkek       Naryn  -12.9328  0.0019 -22.9073  -2.9583    True
12     Bishkek         Osh  -31.0248  0.0000 -37.3382 -24.7115    True
13     Bishkek    Osh_city  -15.8808  0.0000 -24.5900  -7.1716    True
14     Bishkek       Talas  -11.2429  0.0020 -19.9304  -2.5554    True
15        Chui   Issyk-Kul    2.2544  0.9894  -5.0539   9.5627   False
16        Chui  Jalal-Abad  -14.9192  0.0000 -20.7642  -9.0743    True
17        Chui       Naryn    0.4611  1.0000  -9.4351  10.3573   False
18        Chui         Osh  -17.6310  0.0000 -23.8199 -11.4421    True
19        Chui    Osh_city   -2.4869  0.9932 -11.1063   6.1325   False
20        Chui       Talas    2.1510  0.9975  -6.4465  10.7484   False
21   Issyk-Kul  Jalal-Abad  -17.1736  0.0000 -23.8479 -10.4993    True
22   Issyk-Kul       Naryn   -1.7933  0.9998 -12.2009   8.6143   False
23   Issyk-Kul         Osh  -19.8854  0.0000 -26.8628 -12.9079    True
24   Issyk-Kul    Osh_city   -4.7413  0.8054 -13.9433   4.4607   False
25   Issyk-Kul       Talas   -0.1034  1.0000  -9.2849   9.0781   False
26  Jalal-Abad       Naryn   15.3803  0.0000   5.9427  24.8180    True
27  Jalal-Abad         Osh   -2.7117  0.8307  -8.1373   2.7138   False
28  Jalal-Abad    Osh_city   12.4323  0.0001   4.3435  20.5211    True
29  Jalal-Abad       Talas   17.0702  0.0000   9.0048  25.1356    True
30       Naryn         Osh  -18.0921  0.0000 -27.7465  -8.4376    True
31       Naryn    Osh_city   -2.9480  0.9967 -14.3146   8.4186   False
32       Naryn       Talas    1.6899  0.9999  -9.6601  13.0399   False
33         Osh    Osh_city   15.1441  0.0000   6.8034  23.4848    True
34         Osh       Talas   19.7819  0.0000  11.4639  28.1000    True
35    Osh_city       Talas    4.6379  0.8967  -5.6180  14.8937   False

####Oral Reading Score Between Regions, Significance
1. Batken outperformed Osh and Jalal-Abad (Significant as they are the other areas in the south)

2. Bishkek outperformed Chui, issyk kul, jalal abad,naryn, osh, osh-city, talas, and Batken on average. Bishkek a clear leader in oral reading test scores and did significantly better than all other regions, regardless of language.

3. Osh City did not outperform any other region in a significant way.

###Reading Comp Score - Regions - Tukey Test

In [56]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['read_comp_score_pcnt'], base['region'])

# Print results
print(tukey_results)
readregtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
readregtukey

     Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================
  group1     group2   meandiff p-adj   lower    upper   reject
--------------------------------------------------------------
    Batken    Bishkek  10.2175 0.0024   2.2178  18.2172   True
    Batken       Chui  -9.5003 0.0057 -17.3677  -1.6329   True
    Batken  Issyk-Kul  -3.5987 0.9366 -12.3109   5.1134  False
    Batken Jalal-Abad -21.3693    0.0  -28.436 -14.3027   True
    Batken      Naryn  -5.9067 0.8198 -17.5668   5.7534  False
    Batken        Osh -27.4294    0.0 -34.8806 -19.9781   True
    Batken   Osh_city -14.6447 0.0003 -24.8461  -4.4433   True
    Batken      Talas    -8.99 0.1336 -19.1665   1.1864  False
   Bishkek       Chui -19.7178    0.0 -27.4727 -11.9629   True
   Bishkek  Issyk-Kul -13.8162    0.0 -22.4269  -5.2056   True
   Bishkek Jalal-Abad -31.5869    0.0 -38.5281 -24.6456   True
   Bishkek      Naryn -16.1242 0.0005 -27.7087  -4.5398   True
   Bishkek        Osh -37.6469    0.0 -44.9793 -30.3145   True
   Bishkek   Osh_city -24.8622    0.0 -34.9771 -14.7473   True
   Bishkek      Talas -19.2075    0.0 -29.2973  -9.1178   True
      Chui  Issyk-Kul   5.9016 0.4335  -2.5864  14.3895  False
      Chui Jalal-Abad  -11.869    0.0 -18.6574  -5.0807   True
      Chui      Naryn   3.5936 0.9884  -7.8999  15.0871  False
      Chui        Osh -17.9291    0.0 -25.1169 -10.7413   True
      Chui   Osh_city  -5.1444 0.8077  -15.155   4.8662  False
      Chui      Talas   0.5103    1.0  -9.4749  10.4954  False
 Issyk-Kul Jalal-Abad -17.7706    0.0 -25.5222  -10.019   True
 Issyk-Kul      Naryn   -2.308 0.9996 -14.3954   9.7795  False
 Issyk-Kul        Osh -23.8307    0.0 -31.9344  -15.727   True
 Issyk-Kul   Osh_city  -11.046 0.0364 -21.7332  -0.3587   True
 Issyk-Kul      Talas  -5.3913 0.8214 -16.0548   5.2721  False
Jalal-Abad      Naryn  15.4626 0.0004   4.5017  26.4236   True
Jalal-Abad        Osh    -6.06 0.0705 -12.3614   0.2413  False
Jalal-Abad   Osh_city   6.7246 0.3914  -2.6697   16.119  False
Jalal-Abad      Talas  12.3793 0.0014    3.012  21.7466   True
     Naryn        Osh -21.5227    0.0 -32.7354 -10.3099   True
     Naryn   Osh_city   -8.738 0.5049 -21.9393   4.4633  False
     Naryn      Talas  -3.0833 0.9984 -16.2653  10.0987  False
       Osh   Osh_city  12.7847 0.0014   3.0977  22.4717   True
       Osh      Talas  18.4394    0.0   8.7787     28.1   True
  Osh_city      Talas   5.6547 0.8678  -6.2565  17.5659  False
--------------------------------------------------------------

        group1      group2  meandiff   p-adj    lower    upper  reject
0       Batken     Bishkek   10.2175  0.0024   2.2178  18.2172    True
1       Batken        Chui   -9.5003  0.0057 -17.3677  -1.6329    True
2       Batken   Issyk-Kul   -3.5987  0.9366 -12.3109   5.1134   False
3       Batken  Jalal-Abad  -21.3693  0.0000 -28.4360 -14.3027    True
4       Batken       Naryn   -5.9067  0.8198 -17.5668   5.7534   False
5       Batken         Osh  -27.4294  0.0000 -34.8806 -19.9781    True
6       Batken    Osh_city  -14.6447  0.0003 -24.8461  -4.4433    True
7       Batken       Talas   -8.9900  0.1336 -19.1665   1.1864   False
8      Bishkek        Chui  -19.7178  0.0000 -27.4727 -11.9629    True
9      Bishkek   Issyk-Kul  -13.8162  0.0000 -22.4269  -5.2056    True
10     Bishkek  Jalal-Abad  -31.5869  0.0000 -38.5281 -24.6456    True
11     Bishkek       Naryn  -16.1242  0.0005 -27.7087  -4.5398    True
12     Bishkek         Osh  -37.6469  0.0000 -44.9793 -30.3145    True
13     Bishkek    Osh_city  -24.8622  0.0000 -34.9771 -14.7473    True
14     Bishkek       Talas  -19.2075  0.0000 -29.2973  -9.1178    True
15        Chui   Issyk-Kul    5.9016  0.4335  -2.5864  14.3895   False
16        Chui  Jalal-Abad  -11.8690  0.0000 -18.6574  -5.0807    True
17        Chui       Naryn    3.5936  0.9884  -7.8999  15.0871   False
18        Chui         Osh  -17.9291  0.0000 -25.1169 -10.7413    True
19        Chui    Osh_city   -5.1444  0.8077 -15.1550   4.8662   False
20        Chui       Talas    0.5103  1.0000  -9.4749  10.4954   False
21   Issyk-Kul  Jalal-Abad  -17.7706  0.0000 -25.5222 -10.0190    True
22   Issyk-Kul       Naryn   -2.3080  0.9996 -14.3954   9.7795   False
23   Issyk-Kul         Osh  -23.8307  0.0000 -31.9344 -15.7270    True
24   Issyk-Kul    Osh_city  -11.0460  0.0364 -21.7332  -0.3587    True
25   Issyk-Kul       Talas   -5.3913  0.8214 -16.0548   5.2721   False
26  Jalal-Abad       Naryn   15.4626  0.0004   4.5017  26.4236    True
27  Jalal-Abad         Osh   -6.0600  0.0705 -12.3614   0.2413   False
28  Jalal-Abad    Osh_city    6.7246  0.3914  -2.6697  16.1190   False
29  Jalal-Abad       Talas   12.3793  0.0014   3.0120  21.7466    True
30       Naryn         Osh  -21.5227  0.0000 -32.7354 -10.3099    True
31       Naryn    Osh_city   -8.7380  0.5049 -21.9393   4.4633   False
32       Naryn       Talas   -3.0833  0.9984 -16.2653  10.0987   False
33         Osh    Osh_city   12.7847  0.0014   3.0977  22.4717    True
34         Osh       Talas   18.4394  0.0000   8.7787  28.1000    True
35    Osh_city       Talas    5.6547  0.8678  -6.2565  17.5659   False

####Reading Comp Score - Regions - Tukey Test
Bishkek outperformed all other regions, significantly, on this subtask

###Silent Reading - Regions - Tukey Test

In [57]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['word_score_pcnt'], base['region'])

# Print results
print(tukey_results)
wordregtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
wordregtukey

     Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================
  group1     group2   meandiff p-adj   lower    upper   reject
--------------------------------------------------------------
    Batken    Bishkek  -1.6873 0.9978  -8.5852   5.2106  False
    Batken       Chui   1.6998 0.9974  -5.0841   8.4836  False
    Batken  Issyk-Kul  -8.8441  0.008 -16.3563  -1.3318   True
    Batken Jalal-Abad  -6.8007 0.0158 -12.8941  -0.7073   True
    Batken      Naryn  -0.6885    1.0 -10.7426   9.3657  False
    Batken        Osh -16.2093    0.0 -22.6343  -9.7843   True
    Batken   Osh_city  -5.7992 0.5106 -14.5956   2.9972  False
    Batken      Talas   -2.695 0.9897 -11.4699   6.0799  False
   Bishkek       Chui   3.3871 0.8199  -3.2998  10.0739  False
   Bishkek  Issyk-Kul  -7.1568 0.0691 -14.5815    0.268  False
   Bishkek Jalal-Abad  -5.1134 0.1659 -11.0986   0.8718  False
   Bishkek      Naryn   0.9988    1.0  -8.9901  10.9878  False
   Bishkek        Osh  -14.522    0.0 -20.8445  -8.1995   True
   Bishkek   Osh_city  -4.1119 0.8723 -12.8337   4.6099  False
   Bishkek      Talas  -1.0077    1.0  -9.7078   7.6924  False
      Chui  Issyk-Kul -10.5439 0.0003 -17.8628   -3.225   True
      Chui Jalal-Abad  -8.5005 0.0002 -14.3539  -2.6471   True
      Chui      Naryn  -2.3883 0.9981 -12.2988   7.5223  False
      Chui        Osh -17.9091    0.0 -24.1069 -11.7112   True
      Chui   Osh_city   -7.499 0.1492 -16.1309   1.1329  False
      Chui      Talas  -4.3948 0.8135 -13.0048   4.2151  False
 Issyk-Kul Jalal-Abad   2.0434   0.99  -4.6406   8.7274  False
 Issyk-Kul      Naryn   8.1556 0.2684   -2.267  18.5783  False
 Issyk-Kul        Osh  -7.3652 0.0298 -14.3528  -0.3776   True
 Issyk-Kul   Osh_city   3.0449 0.9835  -6.1705  12.2602  False
 Issyk-Kul      Talas   6.1491 0.4901  -3.0457  15.3439  False
Jalal-Abad      Naryn   6.1122 0.5381  -3.3391  15.5635  False
Jalal-Abad        Osh  -9.4086    0.0 -14.8421  -3.9752   True
Jalal-Abad   Osh_city   1.0015    1.0  -7.0991    9.102  False
Jalal-Abad      Talas   4.1057  0.817  -3.9715  12.1828  False
     Naryn        Osh -15.5208    0.0 -25.1893  -5.8524   True
     Naryn   Osh_city  -5.1108 0.9005 -16.4938   6.2723  False
     Naryn      Talas  -2.0065 0.9998  -13.373   9.3599  False
       Osh   Osh_city  10.4101 0.0036   2.0573  18.7629   True
       Osh      Talas  13.5143    0.0   5.1841  21.8444   True
  Osh_city      Talas   3.1042 0.9908  -7.1665  13.3749  False
--------------------------------------------------------------

        group1      group2  meandiff   p-adj    lower    upper  reject
0       Batken     Bishkek   -1.6873  0.9978  -8.5852   5.2106   False
1       Batken        Chui    1.6998  0.9974  -5.0841   8.4836   False
2       Batken   Issyk-Kul   -8.8441  0.0080 -16.3563  -1.3318    True
3       Batken  Jalal-Abad   -6.8007  0.0158 -12.8941  -0.7073    True
4       Batken       Naryn   -0.6885  1.0000 -10.7426   9.3657   False
5       Batken         Osh  -16.2093  0.0000 -22.6343  -9.7843    True
6       Batken    Osh_city   -5.7992  0.5106 -14.5956   2.9972   False
7       Batken       Talas   -2.6950  0.9897 -11.4699   6.0799   False
8      Bishkek        Chui    3.3871  0.8199  -3.2998  10.0739   False
9      Bishkek   Issyk-Kul   -7.1568  0.0691 -14.5815   0.2680   False
10     Bishkek  Jalal-Abad   -5.1134  0.1659 -11.0986   0.8718   False
11     Bishkek       Naryn    0.9988  1.0000  -8.9901  10.9878   False
12     Bishkek         Osh  -14.5220  0.0000 -20.8445  -8.1995    True
13     Bishkek    Osh_city   -4.1119  0.8723 -12.8337   4.6099   False
14     Bishkek       Talas   -1.0077  1.0000  -9.7078   7.6924   False
15        Chui   Issyk-Kul  -10.5439  0.0003 -17.8628  -3.2250    True
16        Chui  Jalal-Abad   -8.5005  0.0002 -14.3539  -2.6471    True
17        Chui       Naryn   -2.3883  0.9981 -12.2988   7.5223   False
18        Chui         Osh  -17.9091  0.0000 -24.1069 -11.7112    True
19        Chui    Osh_city   -7.4990  0.1492 -16.1309   1.1329   False
20        Chui       Talas   -4.3948  0.8135 -13.0048   4.2151   False
21   Issyk-Kul  Jalal-Abad    2.0434  0.9900  -4.6406   8.7274   False
22   Issyk-Kul       Naryn    8.1556  0.2684  -2.2670  18.5783   False
23   Issyk-Kul         Osh   -7.3652  0.0298 -14.3528  -0.3776    True
24   Issyk-Kul    Osh_city    3.0449  0.9835  -6.1705  12.2602   False
25   Issyk-Kul       Talas    6.1491  0.4901  -3.0457  15.3439   False
26  Jalal-Abad       Naryn    6.1122  0.5381  -3.3391  15.5635   False
27  Jalal-Abad         Osh   -9.4086  0.0000 -14.8421  -3.9752    True
28  Jalal-Abad    Osh_city    1.0015  1.0000  -7.0991   9.1020   False
29  Jalal-Abad       Talas    4.1057  0.8170  -3.9715  12.1828   False
30       Naryn         Osh  -15.5208  0.0000 -25.1893  -5.8524    True
31       Naryn    Osh_city   -5.1108  0.9005 -16.4938   6.2723   False
32       Naryn       Talas   -2.0065  0.9998 -13.3730   9.3599   False
33         Osh    Osh_city   10.4101  0.0036   2.0573  18.7629    True
34         Osh       Talas   13.5143  0.0000   5.1841  21.8444    True
35    Osh_city       Talas    3.1042  0.9908  -7.1665  13.3749   False

####Silent reading -regions - tukey test
Now THIS is interesting.
1. Bishkek did *not* outperform in the silent reading subtask, as opposed to the others! Let's look into this a bit more
2. Every region did better, significantly, than Osh. However, the Uzbek students in Osh had *the highest* average scores on silent reading. If the sample was more aligned to the demographics in the region, i.e., more students took the test in uzbek, would this significance be the same?

###Invented Word Score - Regions - Tukey Test

In [58]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['invent_word_score_pcnt'], base['region'])

# Print results
print(tukey_results)
inventregtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
inventregtukey

     Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================
  group1     group2   meandiff p-adj   lower    upper   reject
--------------------------------------------------------------
    Batken    Bishkek  12.9953    0.0   6.9114  19.0792   True
    Batken       Chui   0.6003    1.0   -5.383   6.5836  False
    Batken  Issyk-Kul  -1.2951 0.9996  -7.9208   5.3306  False
    Batken Jalal-Abad  -12.951    0.0 -18.3254  -7.5767   True
    Batken      Naryn  -1.7779 0.9995 -10.6456   7.0898  False
    Batken        Osh -14.8878    0.0 -20.5546   -9.221   True
    Batken   Osh_city  -1.7705 0.9987  -9.5289   5.9878  False
    Batken      Talas  -1.3249 0.9998  -9.0643   6.4145  False
   Bishkek       Chui  -12.395    0.0 -18.2927  -6.4972   True
   Bishkek  Issyk-Kul -14.2904    0.0  -20.839  -7.7418   True
   Bishkek Jalal-Abad -25.9463    0.0 -31.2252 -20.6674   True
   Bishkek      Naryn -14.7732    0.0 -23.5834   -5.963   True
   Bishkek        Osh -27.8831    0.0 -33.4595 -22.3067   True
   Bishkek   Osh_city -14.7658    0.0 -22.4584  -7.0733   True
   Bishkek      Talas -14.3202    0.0 -21.9936  -6.6468   True
      Chui  Issyk-Kul  -1.8954 0.9924  -8.3507   4.5598  False
      Chui Jalal-Abad -13.5514    0.0  -18.714  -8.3887   True
      Chui      Naryn  -2.3782 0.9955 -11.1192   6.3628  False
      Chui        Osh -15.4881    0.0 -20.9546 -10.0217   True
      Chui   Osh_city  -2.3709 0.9887  -9.9841   5.2423  False
      Chui      Talas  -1.9253 0.9972  -9.5192   5.6686  False
 Issyk-Kul Jalal-Abad -11.6559    0.0 -17.5511  -5.7607   True
 Issyk-Kul      Naryn  -0.4828    1.0  -9.6755   8.7099  False
 Issyk-Kul        Osh -13.5927    0.0 -19.7557  -7.4297   True
 Issyk-Kul   Osh_city  -0.4754    1.0  -8.6033   7.6524  False
 Issyk-Kul      Talas  -0.0298    1.0  -8.1395   8.0799  False
Jalal-Abad      Naryn  11.1731 0.0011   2.8371  19.5091   True
Jalal-Abad        Osh  -1.9368  0.944   -6.729   2.8555  False
Jalal-Abad   Osh_city  11.1805    0.0   4.0359  18.3251   True
Jalal-Abad      Talas  11.6261    0.0   4.5021  18.7501   True
     Naryn        Osh -13.1099 0.0001 -21.6374  -4.5824   True
     Naryn   Osh_city   0.0073    1.0 -10.0324  10.0471  False
     Naryn      Talas    0.453    1.0  -9.5722  10.4781  False
       Osh   Osh_city  13.1172    0.0   5.7501  20.4843   True
       Osh      Talas  13.5629    0.0   6.2157    20.91   True
  Osh_city      Talas   0.4456    1.0   -8.613   9.5043  False
--------------------------------------------------------------

        group1      group2  meandiff   p-adj    lower    upper  reject
0       Batken     Bishkek   12.9953  0.0000   6.9114  19.0792    True
1       Batken        Chui    0.6003  1.0000  -5.3830   6.5836   False
2       Batken   Issyk-Kul   -1.2951  0.9996  -7.9208   5.3306   False
3       Batken  Jalal-Abad  -12.9510  0.0000 -18.3254  -7.5767    True
4       Batken       Naryn   -1.7779  0.9995 -10.6456   7.0898   False
5       Batken         Osh  -14.8878  0.0000 -20.5546  -9.2210    True
6       Batken    Osh_city   -1.7705  0.9987  -9.5289   5.9878   False
7       Batken       Talas   -1.3249  0.9998  -9.0643   6.4145   False
8      Bishkek        Chui  -12.3950  0.0000 -18.2927  -6.4972    True
9      Bishkek   Issyk-Kul  -14.2904  0.0000 -20.8390  -7.7418    True
10     Bishkek  Jalal-Abad  -25.9463  0.0000 -31.2252 -20.6674    True
11     Bishkek       Naryn  -14.7732  0.0000 -23.5834  -5.9630    True
12     Bishkek         Osh  -27.8831  0.0000 -33.4595 -22.3067    True
13     Bishkek    Osh_city  -14.7658  0.0000 -22.4584  -7.0733    True
14     Bishkek       Talas  -14.3202  0.0000 -21.9936  -6.6468    True
15        Chui   Issyk-Kul   -1.8954  0.9924  -8.3507   4.5598   False
16        Chui  Jalal-Abad  -13.5514  0.0000 -18.7140  -8.3887    True
17        Chui       Naryn   -2.3782  0.9955 -11.1192   6.3628   False
18        Chui         Osh  -15.4881  0.0000 -20.9546 -10.0217    True
19        Chui    Osh_city   -2.3709  0.9887  -9.9841   5.2423   False
20        Chui       Talas   -1.9253  0.9972  -9.5192   5.6686   False
21   Issyk-Kul  Jalal-Abad  -11.6559  0.0000 -17.5511  -5.7607    True
22   Issyk-Kul       Naryn   -0.4828  1.0000  -9.6755   8.7099   False
23   Issyk-Kul         Osh  -13.5927  0.0000 -19.7557  -7.4297    True
24   Issyk-Kul    Osh_city   -0.4754  1.0000  -8.6033   7.6524   False
25   Issyk-Kul       Talas   -0.0298  1.0000  -8.1395   8.0799   False
26  Jalal-Abad       Naryn   11.1731  0.0011   2.8371  19.5091    True
27  Jalal-Abad         Osh   -1.9368  0.9440  -6.7290   2.8555   False
28  Jalal-Abad    Osh_city   11.1805  0.0000   4.0359  18.3251    True
29  Jalal-Abad       Talas   11.6261  0.0000   4.5021  18.7501    True
30       Naryn         Osh  -13.1099  0.0001 -21.6374  -4.5824    True
31       Naryn    Osh_city    0.0073  1.0000 -10.0324  10.0471   False
32       Naryn       Talas    0.4530  1.0000  -9.5722  10.4781   False
33         Osh    Osh_city   13.1172  0.0000   5.7501  20.4843    True
34         Osh       Talas   13.5629  0.0000   6.2157  20.9100    True
35    Osh_city       Talas    0.4456  1.0000  -8.6130   9.5043   False

#### Invented Word - Regions - Tukey Test
1. Back to Bishkek outperforming all other regions significantly
2. Osh being outperformed by other regions. Osh City outperforming Osh

###Listening Comp Score - Regions - Tukey Test

In [59]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['list_comp_score_pcnt'], base['region'])

# Print results
print(tukey_results)
listregtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
listregtukey

     Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================
  group1     group2   meandiff p-adj   lower    upper   reject
--------------------------------------------------------------
    Batken    Bishkek   3.7997 0.8507  -4.0062  11.6056  False
    Batken       Chui   -4.997 0.5289 -12.6739   2.6798  False
    Batken  Issyk-Kul   0.0742    1.0  -8.4269   8.5754  False
    Batken Jalal-Abad -10.0997 0.0002 -16.9952  -3.2041   True
    Batken      Naryn   -6.558 0.6894 -17.9357   4.8197  False
    Batken        Osh -21.5413    0.0 -28.8121 -14.2705   True
    Batken   Osh_city  -8.6608 0.1478 -18.6152   1.2935  False
    Batken      Talas  -8.2425 0.1968 -18.1725   1.6875  False
   Bishkek       Chui  -8.7967 0.0095 -16.3638  -1.2297   True
   Bishkek  Issyk-Kul  -3.7255 0.9068 -12.1276   4.6767  False
   Bishkek Jalal-Abad -13.8994    0.0 -20.6725  -7.1263   True
   Bishkek      Naryn -10.3577 0.1032 -21.6616   0.9462  False
   Bishkek        Osh  -25.341    0.0 -32.4958 -18.1862   True
   Bishkek   Osh_city -12.4605 0.0029 -22.3304  -2.5906   True
   Bishkek      Talas -12.0422 0.0047 -21.8876  -2.1969   True
      Chui  Issyk-Kul   5.0713 0.6132  -3.2111  13.3536  False
      Chui Jalal-Abad  -5.1026 0.2889 -11.7266   1.5213  False
      Chui      Naryn   -1.561    1.0 -12.7761   9.6542  False
      Chui        Osh -16.5443    0.0  -23.558  -9.5306   True
      Chui   Osh_city  -3.6638 0.9638 -13.4319   6.1044  False
      Chui      Talas  -3.2455 0.9826 -12.9888   6.4978  False
 Issyk-Kul Jalal-Abad -10.1739  0.001 -17.7377  -2.6101   True
 Issyk-Kul      Naryn  -6.6322  0.718 -18.4269   5.1624  False
 Issyk-Kul        Osh -21.6156    0.0  -29.523 -13.7081   True
 Issyk-Kul   Osh_city  -8.7351 0.1868 -19.1635   1.6934  False
 Issyk-Kul      Talas  -8.3168 0.2415 -18.7219   2.0884  False
Jalal-Abad      Naryn   3.5417 0.9832  -7.1538  14.2371  False
Jalal-Abad        Osh -11.4416    0.0 -17.5903   -5.293   True
Jalal-Abad   Osh_city   1.4388 0.9999   -7.728  10.6057  False
Jalal-Abad      Talas   1.8571 0.9994  -7.2832  10.9975  False
     Naryn        Osh -14.9833 0.0007 -25.9245  -4.0421   True
     Naryn   Osh_city  -2.1028 0.9999 -14.9843  10.7787  False
     Naryn      Talas  -1.6845    1.0 -14.5472  11.1782  False
       Osh   Osh_city  12.8805 0.0008   3.4282  22.3328   True
       Osh      Talas  13.2988 0.0004   3.8721  22.7255   True
  Osh_city      Talas   0.4183    1.0 -11.2044   12.041  False
--------------------------------------------------------------

        group1      group2  meandiff   p-adj    lower    upper  reject
0       Batken     Bishkek    3.7997  0.8507  -4.0062  11.6056   False
1       Batken        Chui   -4.9970  0.5289 -12.6739   2.6798   False
2       Batken   Issyk-Kul    0.0742  1.0000  -8.4269   8.5754   False
3       Batken  Jalal-Abad  -10.0997  0.0002 -16.9952  -3.2041    True
4       Batken       Naryn   -6.5580  0.6894 -17.9357   4.8197   False
5       Batken         Osh  -21.5413  0.0000 -28.8121 -14.2705    True
6       Batken    Osh_city   -8.6608  0.1478 -18.6152   1.2935   False
7       Batken       Talas   -8.2425  0.1968 -18.1725   1.6875   False
8      Bishkek        Chui   -8.7967  0.0095 -16.3638  -1.2297    True
9      Bishkek   Issyk-Kul   -3.7255  0.9068 -12.1276   4.6767   False
10     Bishkek  Jalal-Abad  -13.8994  0.0000 -20.6725  -7.1263    True
11     Bishkek       Naryn  -10.3577  0.1032 -21.6616   0.9462   False
12     Bishkek         Osh  -25.3410  0.0000 -32.4958 -18.1862    True
13     Bishkek    Osh_city  -12.4605  0.0029 -22.3304  -2.5906    True
14     Bishkek       Talas  -12.0422  0.0047 -21.8876  -2.1969    True
15        Chui   Issyk-Kul    5.0713  0.6132  -3.2111  13.3536   False
16        Chui  Jalal-Abad   -5.1026  0.2889 -11.7266   1.5213   False
17        Chui       Naryn   -1.5610  1.0000 -12.7761   9.6542   False
18        Chui         Osh  -16.5443  0.0000 -23.5580  -9.5306    True
19        Chui    Osh_city   -3.6638  0.9638 -13.4319   6.1044   False
20        Chui       Talas   -3.2455  0.9826 -12.9888   6.4978   False
21   Issyk-Kul  Jalal-Abad  -10.1739  0.0010 -17.7377  -2.6101    True
22   Issyk-Kul       Naryn   -6.6322  0.7180 -18.4269   5.1624   False
23   Issyk-Kul         Osh  -21.6156  0.0000 -29.5230 -13.7081    True
24   Issyk-Kul    Osh_city   -8.7351  0.1868 -19.1635   1.6934   False
25   Issyk-Kul       Talas   -8.3168  0.2415 -18.7219   2.0884   False
26  Jalal-Abad       Naryn    3.5417  0.9832  -7.1538  14.2371   False
27  Jalal-Abad         Osh  -11.4416  0.0000 -17.5903  -5.2930    True
28  Jalal-Abad    Osh_city    1.4388  0.9999  -7.7280  10.6057   False
29  Jalal-Abad       Talas    1.8571  0.9994  -7.2832  10.9975   False
30       Naryn         Osh  -14.9833  0.0007 -25.9245  -4.0421    True
31       Naryn    Osh_city   -2.1028  0.9999 -14.9843  10.7787   False
32       Naryn       Talas   -1.6845  1.0000 -14.5472  11.1782   False
33         Osh    Osh_city   12.8805  0.0008   3.4282  22.3328    True
34         Osh       Talas   13.2988  0.0004   3.8721  22.7255    True
35    Osh_city       Talas    0.4183  1.0000 -11.2044  12.0410   False

####Listening Comp -Regions-Tukey Test
1. Bishkek outperformed only half of the regions this time. Chui, Jalal-Abad, Osh, and Osh City

##ANOVA - one way test - Language within a region by subtask

###Oral Reading Score Score - between languages within a region

In [60]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('oral_read_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

ANOVA for Region: Batken
                    sum_sq     df          F        PR(>F)
C(language)   27057.548323    3.0  13.419231  3.091704e-08
Residual     199616.305498  297.0        NaN           NaN


ANOVA for Region: Bishkek
                    sum_sq     df          F    PR(>F)
C(language)   10392.732819    1.0  24.361557  0.000001
Residual     134806.801772  316.0        NaN       NaN


ANOVA for Region: Chui
                    sum_sq     df         F    PR(>F)
C(language)      83.601680    1.0  0.118575  0.730799
Residual     239013.759024  339.0       NaN       NaN


ANOVA for Region: Issyk-Kul
                    sum_sq     df         F    PR(>F)
C(language)    1710.704114    1.0  2.477204  0.116894
Residual     157451.943712  228.0       NaN       NaN


ANOVA for Region: Jalal-Abad
                    sum_sq     df         F    PR(>F)
C(language)   16005.042902    2.0  8.860669  0.000162
Residual     521118.067443  577.0       NaN       NaN


ANOVA for Region: Naryn
                   sum_sq    df         F    PR(>F)
C(language)   2108.408333   1.0  2.836983  0.095435
Residual     69859.550000  94.0       NaN       NaN


ANOVA for Region: Osh
                    sum_sq     df         F    PR(>F)
C(language)   14050.654789    2.0  7.497214  0.000629
Residual     406683.331481  434.0       NaN       NaN


ANOVA for Region: Osh_city
                   sum_sq     df         F    PR(>F)
C(language)   6323.428491    2.0  5.826475  0.003734
Residual     73799.880861  136.0       NaN       NaN


ANOVA for Region: Talas
                   sum_sq     df         F    PR(>F)
C(language)      8.331429    1.0  0.014626  0.903916
Residual     78608.890000  138.0       NaN       NaN

Takeaways of ANOVA test within regions for the oral reading  subtask score - did language matter within the region?

1. Batken - significant as p <= .05
2. Bishkek - significant as p <= .05
3. Chui - not significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - significant as p <= .05
9. Talas - not significant as p > .05

###Reading Comprehension - between languages within a region

In [61]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('read_comp_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

ANOVA for Region: Batken
                    sum_sq     df          F        PR(>F)
C(language)   98955.200191    3.0  38.820759  3.400542e-21
Residual     252353.769909  297.0        NaN           NaN


ANOVA for Region: Bishkek
                    sum_sq     df         F        PR(>F)
C(language)   20831.193483    1.0  26.74821  4.122955e-07
Residual     246097.108404  316.0       NaN           NaN


ANOVA for Region: Chui
                    sum_sq     df          F    PR(>F)
C(language)   13570.677133    1.0  13.644068  0.000257
Residual     337176.536943  339.0        NaN       NaN


ANOVA for Region: Issyk-Kul
                    sum_sq     df         F    PR(>F)
C(language)      36.469356    1.0  0.037748  0.846124
Residual     220278.313253  228.0       NaN       NaN


ANOVA for Region: Jalal-Abad
                    sum_sq     df         F    PR(>F)
C(language)   13102.068924    2.0  6.306486  0.001953
Residual     599374.482800  577.0       NaN       NaN


ANOVA for Region: Naryn
                   sum_sq    df         F    PR(>F)
C(language)    163.333333   1.0  0.156316  0.693467
Residual     98220.000000  94.0       NaN       NaN


ANOVA for Region: Osh
                    sum_sq     df         F        PR(>F)
C(language)   70142.651390    2.0  33.79093  2.296656e-14
Residual     450444.991631  434.0       NaN           NaN


ANOVA for Region: Osh_city
                   sum_sq     df         F    PR(>F)
C(language)   3555.022547    2.0  2.427992  0.092029
Residual     99564.401914  136.0       NaN       NaN


ANOVA for Region: Talas
               sum_sq     df         F    PR(>F)
C(language)    1400.0    1.0  1.654676  0.200478
Residual     116760.0  138.0       NaN       NaN

Oral Reading Comprehension  subtask, significance of language within regions
1. Batken - significant as p <= .05
2. Bishkek -  significant as p >= .05
3. Chui -  significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - not significant as p >= .05
9. Talas - not significant as p > .05

###Silent Reading Comprehension - between languages within a region

In [62]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('word_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

ANOVA for Region: Batken
                    sum_sq     df          F        PR(>F)
C(language)   94895.942044    3.0  65.745064  1.251100e-32
Residual     142895.871910  297.0        NaN           NaN


ANOVA for Region: Bishkek
                    sum_sq     df         F    PR(>F)
C(language)    4653.912911    1.0  6.647983  0.010379
Residual     221215.433001  316.0       NaN       NaN


ANOVA for Region: Chui
                    sum_sq     df           F        PR(>F)
C(language)   72443.010357    1.0  116.787349  1.371596e-23
Residual     210281.171461  339.0         NaN           NaN


ANOVA for Region: Issyk-Kul
                    sum_sq     df         F    PR(>F)
C(language)     117.355436    1.0  0.146141  0.702606
Residual     183089.966303  228.0       NaN       NaN


ANOVA for Region: Jalal-Abad
                    sum_sq     df          F        PR(>F)
C(language)   20632.504730    2.0  15.301226  3.349587e-07
Residual     389019.652166  577.0        NaN           NaN


ANOVA for Region: Naryn
                   sum_sq    df         F    PR(>F)
C(language)   1020.833333   1.0  1.525494  0.219868
Residual     62903.125000  94.0       NaN       NaN


ANOVA for Region: Osh
                    sum_sq     df          F        PR(>F)
C(language)   89291.288953    2.0  66.288163  7.554285e-26
Residual     292302.711047  434.0        NaN           NaN


ANOVA for Region: Osh_city
                   sum_sq     df         F    PR(>F)
C(language)   8491.914894    2.0  6.639976  0.001772
Residual     86965.711005  136.0       NaN       NaN


ANOVA for Region: Talas
                   sum_sq     df         F    PR(>F)
C(language)   3778.571429    1.0  6.487028  0.011963
Residual     80382.400000  138.0       NaN       NaN

Word Score Percent subtask, significance of language within regions
1. Batken - significant as p <= .05
2. Bishkek - not significant as p >= .05
3. Chui -  significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - significant as p <= .05
9. Talas - not significant as p > .05

###Invented Word Score - between languages within a region

In [63]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('invent_word_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

ANOVA for Region: Batken
                    sum_sq     df        F    PR(>F)
C(language)    7494.583537    3.0  4.47693  0.004307
Residual     165730.479586  297.0      NaN       NaN


ANOVA for Region: Bishkek
                    sum_sq     df          F    PR(>F)
C(language)    8195.408011    1.0  16.791331  0.000053
Residual     154231.308970  316.0        NaN       NaN


ANOVA for Region: Chui
                    sum_sq     df         F    PR(>F)
C(language)     574.067017    1.0  0.890813  0.345929
Residual     218461.827411  339.0       NaN       NaN


ANOVA for Region: Issyk-Kul
                    sum_sq     df         F   PR(>F)
C(language)       7.357255    1.0  0.012344  0.91163
Residual     135886.903614  228.0       NaN      NaN


ANOVA for Region: Jalal-Abad
                    sum_sq     df         F    PR(>F)
C(language)   10205.082087    2.0  8.288309  0.000283
Residual     355219.159292  577.0       NaN       NaN


ANOVA for Region: Naryn
                   sum_sq    df         F    PR(>F)
C(language)   2025.408333   1.0  3.371165  0.069508
Residual     56475.550000  94.0       NaN       NaN


ANOVA for Region: Osh
                    sum_sq     df         F    PR(>F)
C(language)    5303.034092    2.0  4.151272  0.016374
Residual     277206.201606  434.0       NaN       NaN


ANOVA for Region: Osh_city
                   sum_sq     df         F    PR(>F)
C(language)   3325.230195    2.0  3.898963  0.022567
Residual     57993.791388  136.0       NaN       NaN


ANOVA for Region: Talas
                   sum_sq     df         F    PR(>F)
C(language)    211.382857    1.0  0.419337  0.518344
Residual     69564.160000  138.0       NaN       NaN

Takeaways of ANOVA test within regions for the invented word subtask score - did language matter within the region?

1. Batken - significant as p <= .05
2. Bishkek - significant as p <= .05
3. Chui - not significant as p > .05
4. Issyk-Kul - not significant as p > .05
5. Jalal-Abad - significant as p <= .05
6. Naryn - not significant as p >= .05
7. Osh - significant as p <= .05
8. Osh City - significant as p <= .05
9. Talas - not significant as p > .05

###List Comp Score - between languages within a region

In [64]:
# List of regions
regions = base['region'].unique()

# Loop through regions and run ANOVA for each region
for region in regions:
    subset = base[base['region'] == region]
    model = ols('list_comp_score_pcnt ~ C(language)', data=subset).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    print(f"ANOVA for Region: {region}")
    print(anova_table)
    print("\n")

ANOVA for Region: Batken
                    sum_sq     df           F        PR(>F)
C(language)  166955.871637    3.0  113.566731  5.288427e-49
Residual     145541.138330  297.0         NaN           NaN


ANOVA for Region: Bishkek
                    sum_sq     df          F    PR(>F)
C(language)    9940.834999    1.0  16.274167  0.000069
Residual     193023.944875  316.0        NaN       NaN


ANOVA for Region: Chui
                    sum_sq     df          F        PR(>F)
C(language)   65526.596570    1.0  88.290836  8.617193e-19
Residual     251594.811055  339.0        NaN           NaN


ANOVA for Region: Issyk-Kul
                    sum_sq     df         F    PR(>F)
C(language)     267.365767    1.0  0.329287  0.566645
Residual     185125.677711  228.0       NaN       NaN


ANOVA for Region: Jalal-Abad
                    sum_sq     df           F        PR(>F)
C(language)  155007.103297    2.0  104.437859  1.948187e-39
Residual     428192.896703  577.0         NaN           NaN


ANOVA for Region: Naryn
                   sum_sq    df         F    PR(>F)
C(language)   2520.833333   1.0  2.798445  0.097681
Residual     84675.000000  94.0       NaN       NaN


ANOVA for Region: Osh
                    sum_sq     df           F        PR(>F)
C(language)  193900.072720    2.0  105.166683  5.731477e-38
Residual     400091.689294  434.0         NaN           NaN


ANOVA for Region: Osh_city
                    sum_sq     df         F    PR(>F)
C(language)   14576.919211    2.0  8.520461  0.000326
Residual     116335.311005  136.0       NaN       NaN


ANOVA for Region: Talas
                   sum_sq     df          F        PR(>F)
C(language)  16871.142857    1.0  27.247826  6.432738e-07
Residual     85446.000000  138.0        NaN           NaN

##Tukey Test - One Way Significant Results Within Region

In [65]:
baselinemean = base.pivot_table(index=
 ['region', 'language'],
 values=[
     'oral_read_score_pcnt',
     'read_comp_score_pcnt',
     'word_score_pcnt',
     'invent_word_score_pcnt',
     'list_comp_score_pcnt'],
aggfunc='mean')
baselinemean.round(2)

                     invent_word_score_pcnt  list_comp_score_pcnt  \
region     language
Batken     Kyrgyz                     62.86                 59.86
           Russian                    47.37                 26.32
           Tajik                      56.33                 89.33
           Uzbek                      60.04                 97.20
Bishkek    Kyrgyz                     66.23                 67.13
           Russian                    76.57                 78.52
Chui       Kyrgyz                     58.87                 76.95
           Russian                    61.50                 48.89
Issyk-Kul  Kyrgyz                     57.98                 70.84
           Russian                    58.38                 68.44
Jalal-Abad Kyrgyz                     46.47                 63.86
           Russian                    51.51                 36.23
           Uzbek                      38.98                 83.45
Naryn      Kyrgyz                     55.55                 61.25
           Russian                    67.88                 75.00
Osh        Kyrgyz                     43.06                 52.93
           Russian                    44.25                 20.35
           Uzbek                      55.35                 98.00
Osh_city   Kyrgyz                     54.53                 81.05
           Russian                    59.64                 56.18
           Uzbek                      41.20                 82.00
Talas      Kyrgyz                     57.28                 68.80
           Russian                    60.00                 44.50

                     oral_read_score_pcnt  read_comp_score_pcnt  \
region     language
Batken     Kyrgyz                   78.71                 64.14
           Russian                  54.21                 27.37
           Tajik                    65.70                 41.33
           Uzbek                    83.20                 82.80
Bishkek    Kyrgyz                   78.66                 63.41
           Russian                  90.30                 79.89
Chui       Kyrgyz                   71.76                 58.88
           Russian                  72.76                 46.11
Issyk-Kul  Kyrgyz                   76.13                 59.64
           Russian                  70.05                 58.75
Jalal-Abad Kyrgyz                   58.68                 45.72
           Russian                  61.77                 34.72
           Uzbek                    46.75                 40.00
Naryn      Kyrgyz                   70.55                 56.50
           Russian                  83.12                 60.00
Osh        Kyrgyz                   54.58                 37.95
           Russian                  48.84                 18.95
           Uzbek                    70.62                 66.00
Osh_city   Kyrgyz                   69.84                 61.05
           Russian                  71.86                 46.36
           Uzbek                    45.60                 46.00
Talas      Kyrgyz                   74.49                 56.00
           Russian                  73.95                 49.00

                     word_score_pcnt
region     language
Batken     Kyrgyz              54.16
           Russian             37.34
           Tajik               72.23
           Uzbek               87.72
Bishkek    Kyrgyz              57.89
           Russian             65.68
Chui       Kyrgyz              78.37
           Russian             48.86
Issyk-Kul  Kyrgyz              54.92
           Russian             56.52
Jalal-Abad Kyrgyz              60.85
           Russian             47.72
           Uzbek               61.69
Naryn      Kyrgyz              62.06
           Russian             70.81
Osh        Kyrgyz              48.19
           Russian             33.39
           Uzbek               88.30
Osh_city   Kyrgyz              78.05
           Russian             55.32
           Uzbek               55.10
Talas      Kyrgyz              64.80
           Russian             53.30

Significance of Language *within* a region
1. Oral Reading: Batken, Bishkek, Jalal-Abad, Osh, Osh City
2. Reading Comprehension: Batken, Bishkek, Chui, Jalal-Abad, Osh, Osh City
3. Silent Reading: Batken, Bishkek, Chui, Jalal-Abad, Osh, Osh City, Talas
4. Invented Word: Batken, Bishkek, Jalal-Abad, Osh, Osh City
5. Listening Comp:Batken, Bishkek, Chui, Jalal-Abad, Osh, Osh City, Talas

In [66]:
# Create a combined category for region and language
base['Region_Language'] = base['region'] + "_" + base['language']

<ipython-input-66-136fc0f7eed0>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

###Oral Reading Tukey Test, Language within region

In [67]:
oralreadonewayanova = ['Batken', 'Bishkek', 'Jalal-Abad', 'Osh', 'Osh_city']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in oralreadonewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['oral_read_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

Tukey HSD Results for Region: Batken
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
========================================================
 group1  group2 meandiff p-adj   lower    upper   reject
--------------------------------------------------------
 Kyrgyz Russian -24.5038    0.0 -36.7557 -12.2518   True
 Kyrgyz   Tajik -13.0143 0.0627   -26.49   0.4614  False
 Kyrgyz   Uzbek     4.49  0.567  -4.4703  13.4503  False
Russian   Tajik  11.4895 0.2685  -4.8694  27.8483  False
Russian   Uzbek  28.9938    0.0  16.0978  41.8897   True
  Tajik   Uzbek  17.5043 0.0078   3.4405  31.5681   True
--------------------------------------------------------


Tukey HSD Results for Region: Bishkek
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1  group2 meandiff p-adj lower   upper  reject
---------------------------------------------------
Kyrgyz Russian  11.6427   0.0 7.0016 16.2837   True
---------------------------------------------------


Tukey HSD Results for Region: Jalal-Abad
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian   3.0951 0.5416  -3.7894  9.9797  False
 Kyrgyz   Uzbek -11.9239 0.0011 -19.7577 -4.0901   True
Russian   Uzbek  -15.019 0.0002 -23.7767 -6.2614   True
-------------------------------------------------------


Tukey HSD Results for Region: Osh
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian  -5.7409 0.2099 -13.7269  2.2451  False
 Kyrgyz   Uzbek   16.042 0.0058   3.8813 28.2027   True
Russian   Uzbek  21.7829 0.0004   8.5529 35.0128   True
-------------------------------------------------------


Tukey HSD Results for Region: Osh_city
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian   2.0215  0.935 -11.6925 15.7355  False
 Kyrgyz   Uzbek -24.2421 0.0234 -45.8079 -2.6763   True
Russian   Uzbek -26.2636 0.0024 -44.4958 -8.0315   True
-------------------------------------------------------

####Oral Reading Tukey Test Analysis:

Oral Reading:
1. Batken - Kyrgyz did better, significantly so, in comparison to Russian (Does not align with hypothesis). Uzbek outperformed Russian and Tajik.

2. Bishkek - Russian did significantly better compared to Kyrgyz (aligns with hypothesis)

3. Jalal-Abad - Kyrgyz and Russian both outperformed Uzbek results. Russian did not outperform Kyrgyz

4. Osh - Uzbek outperformed Kyrgyz and Russian in Osh - which aligns with the regional demographics

5. Osh_City: Kyrgyz and Russian outperformed Uzbek. However due to sample size of Only 10 uzbeks in Osh_City,  not likely this is significant.

###Reading Comp Tukey Test - Language within region

In [68]:
readcomponewayanova = ['Batken', 'Bishkek', 'Chui','Jalal-Abad', 'Osh', 'Osh_city']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in readcomponewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['read_comp_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

Tukey HSD Results for Region: Batken
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
========================================================
 group1  group2 meandiff p-adj   lower    upper   reject
--------------------------------------------------------
 Kyrgyz Russian -36.7744    0.0 -50.5501 -22.9988   True
 Kyrgyz   Tajik -22.8095 0.0007 -37.9611   -7.658   True
 Kyrgyz   Uzbek  18.6528    0.0   8.5782  28.7275   True
Russian   Tajik  13.9649  0.205  -4.4284  32.3582  False
Russian   Uzbek  55.4273    0.0  40.9275   69.927   True
  Tajik   Uzbek  41.4624    0.0  25.6496  57.2751   True
--------------------------------------------------------


Tukey HSD Results for Region: Bishkek
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1  group2 meandiff p-adj  lower  upper  reject
---------------------------------------------------
Kyrgyz Russian  16.4833   0.0 10.2127 22.754   True
---------------------------------------------------


Tukey HSD Results for Region: Chui
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
group1  group2 meandiff p-adj   lower    upper  reject
------------------------------------------------------
Kyrgyz Russian -12.7721 0.0003 -19.5735 -5.9708   True
------------------------------------------------------


Tukey HSD Results for Region: Jalal-Abad
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian -11.0065 0.0014 -18.3899 -3.6231   True
 Kyrgyz   Uzbek  -5.7235 0.2461 -14.1249  2.6779  False
Russian   Uzbek    5.283 0.3836  -4.1092 14.6752  False
-------------------------------------------------------


Tukey HSD Results for Region: Osh
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj  lower    upper   reject
-------------------------------------------------------
 Kyrgyz Russian -19.0032   0.0 -27.4079 -10.5985   True
 Kyrgyz   Uzbek  28.0495   0.0  15.2512  40.8477   True
Russian   Uzbek  47.0526   0.0  33.1291  60.9762   True
-------------------------------------------------------


Tukey HSD Results for Region: Osh_city
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian  -14.689 0.0773  -30.618    1.24  False
 Kyrgyz   Uzbek -15.0526 0.3314 -40.1016  9.9963  False
Russian   Uzbek  -0.3636 0.9991 -21.5405 20.8132  False
-------------------------------------------------------

####Reading Comp Tukey Analysis

1. Batken: Russian did poor! Signifcant differnece in results with Kyrgyz and Uzbek outperforming Russian. (does not fit hypothesis!)
2. Bishkek, Russian outperformed Kyrgyz  (fits hypothesis)
3. Chui, Kyrgyz outperformed Russian. (does not fit hypothesis)
4. in Jalal-Abad - kyrgyz outperformed Russian significantly. average scores were however poor. No other significance found.
5. In Osh, Uzbek far outperformed Russian, as did Kyrgyz. significant differences found and students who selected Russian did substantially worse than their peers in osh on reading copmrehension.
6. No significance found within Osh city between languages.

###Silent Reading Tukey Test - Language within Region

In [69]:
wordscoreonewayanova = ['Batken', 'Bishkek', 'Chui','Jalal-Abad', 'Osh', 'Osh_city','Talas']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in wordscoreonewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['word_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

Tukey HSD Results for Region: Batken
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian -16.8222 0.0002 -27.1883  -6.456   True
 Kyrgyz   Tajik   18.069 0.0003   6.6675 29.4706   True
 Kyrgyz   Uzbek  33.5561    0.0   25.975 41.1373   True
Russian   Tajik  34.8912    0.0  21.0503 48.7321   True
Russian   Uzbek  50.3783    0.0  39.4673 61.2893   True
  Tajik   Uzbek  15.4871 0.0048    3.588 27.3862   True
-------------------------------------------------------


Tukey HSD Results for Region: Bishkek
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1  group2 meandiff p-adj  lower   upper  reject
----------------------------------------------------
Kyrgyz Russian   7.7911 0.0104 1.8459 13.7363   True
----------------------------------------------------


Tukey HSD Results for Region: Chui
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
group1  group2 meandiff p-adj  lower    upper   reject
------------------------------------------------------
Kyrgyz Russian -29.5094   0.0 -34.8806 -24.1383   True
------------------------------------------------------


Tukey HSD Results for Region: Jalal-Abad
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian -13.1319    0.0 -19.0802 -7.1836   True
 Kyrgyz   Uzbek    0.842  0.954  -5.9264  7.6105  False
Russian   Uzbek  13.9739 0.0001   6.4072 21.5406   True
-------------------------------------------------------


Tukey HSD Results for Region: Osh
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
 group1  group2 meandiff p-adj  lower   upper  reject
-----------------------------------------------------
 Kyrgyz Russian -14.7925   0.0 -21.563 -8.0221   True
 Kyrgyz   Uzbek  40.1127   0.0  29.803 50.4224   True
Russian   Uzbek  54.9053   0.0  43.689 66.1215   True
-----------------------------------------------------


Tukey HSD Results for Region: Osh_city
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian -22.7344 0.0012 -37.6216 -7.8473   True
 Kyrgyz   Uzbek -22.9526  0.056 -46.3632  0.4579  False
Russian   Uzbek  -0.2182 0.9996 -20.0099 19.5735  False
-------------------------------------------------------


Tukey HSD Results for Region: Talas
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1  group2 meandiff p-adj  lower    upper  reject
-----------------------------------------------------
Kyrgyz Russian    -11.5 0.012 -20.4279 -2.5721   True
-----------------------------------------------------

####Silent Reading Tukey Analysis

1. Batken: Significance between all languages, with Kyrgyz, Tajik, and Uzbek outperforming Russian.  Interestingly, the minority languages (uzbek and tajik) outperformed Kyrgyz in this region!
2. Bishkek: Russian outperformed Kyrgyz significantly
3. Chui: Kyrgyz outperformed Russian significantly
4. Jalal-Abad: Kyrgyz and Uzbek outperformed Russian significantly
5. Osh Kyrgyz outperformed Russian. Uzbek outperformed Kyrgyz + Russian
6. Osh City - Kyrgyz outperformed Russian, no other significance found (osh city simple size for uzbek isnt helping! :-( )
7. Talas - Kyrgyz outperformed Russian

###Invented Word Score - Language within Region

In [70]:
inventwordoneway = ['Batken', 'Bishkek','Jalal-Abad', 'Osh', 'Osh_city']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in inventwordoneway:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['invent_word_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

Tukey HSD Results for Region: Batken
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian -15.4887 0.0022 -26.6524  -4.325   True
 Kyrgyz   Tajik  -6.5238 0.5175 -18.8026  5.7549  False
 Kyrgyz   Uzbek  -2.8141 0.8098 -10.9786  5.3503  False
Russian   Tajik   8.9649 0.4068  -5.9409 23.8707  False
Russian   Uzbek  12.6746 0.0288   0.9241 24.4251   True
  Tajik   Uzbek   3.7097 0.8775  -9.1049 16.5243  False
-------------------------------------------------------


Tukey HSD Results for Region: Bishkek
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1  group2 meandiff p-adj  lower  upper  reject
---------------------------------------------------
Kyrgyz Russian  10.3389 0.0001 5.3747 15.303   True
---------------------------------------------------


Tukey HSD Results for Region: Jalal-Abad
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian     5.04 0.0941  -0.6441  10.724  False
 Kyrgyz   Uzbek  -7.4876 0.0184 -13.9554 -1.0199   True
Russian   Uzbek -12.5276 0.0002 -19.7581 -5.2971   True
-------------------------------------------------------


Tukey HSD Results for Region: Osh
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
 group1  group2 meandiff p-adj   lower   upper  reject
------------------------------------------------------
 Kyrgyz Russian   1.1855 0.9062 -5.4078  7.7788  False
 Kyrgyz   Uzbek  12.2899 0.0116    2.25 22.3299   True
Russian   Uzbek  11.1044 0.0453  0.1816 22.0271   True
------------------------------------------------------


Tukey HSD Results for Region: Osh_city
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian     5.11 0.5806   -7.047 17.2671  False
 Kyrgyz   Uzbek -13.3263 0.2277 -32.4437   5.791  False
Russian   Uzbek -18.4364  0.021 -34.5986 -2.2742   True
-------------------------------------------------------

####Invented Word Score Tukey Analysis
1. Batken: Kyrgyz outperformed Russian, and uzbek outperformed Russian, significantly
2. Bishkek: Russian outperformed kyrgyz, significance
3. Jalal-Abad: Kyrgyz and Russian both significantly outperformed Uzbek
4. Osh - Kyrgyz and Russian were both outperformed by Uzbek
5. Osh City - nothing of significance to report due to small size of Uzbek population smapled

###Listening Comprehension Score - Language within Region

In [71]:
listcomponewayanova = ['Batken', 'Bishkek', 'Chui','Jalal-Abad', 'Osh', 'Osh_city','Talas']

# Loop through each region and perform Tukey HSD test for language comparisons within each region
for region in listcomponewayanova:
    # Filter the data for the current region
    subset = base[base['region'] == region]

    # Run Tukey HSD Test within the region for language differences
    tukey = pairwise_tukeyhsd(subset['list_comp_score_pcnt'], subset['language'], alpha=0.05)

    # Print the results for each region
    print(f"Tukey HSD Results for Region: {region}")
    print(tukey.summary())
    print("\n")

Tukey HSD Results for Region: Batken
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
 group1  group2 meandiff p-adj  lower   upper   reject
------------------------------------------------------
 Kyrgyz Russian -33.5414   0.0 -44.003 -23.0797   True
 Kyrgyz   Tajik  29.4762   0.0 17.9696  40.9828   True
 Kyrgyz   Uzbek  37.3472   0.0 29.6962  44.9982   True
Russian   Tajik  63.0175   0.0 49.0491   76.986   True
Russian   Uzbek  70.8885   0.0  59.877  81.9001   True
  Tajik   Uzbek    7.871 0.329 -4.1377  19.8797  False
------------------------------------------------------


Tukey HSD Results for Region: Bishkek
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1  group2 meandiff p-adj  lower   upper  reject
----------------------------------------------------
Kyrgyz Russian  11.3867 0.0001 5.8333 16.9402   True
----------------------------------------------------


Tukey HSD Results for Region: Chui
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
group1  group2 meandiff p-adj  lower    upper   reject
------------------------------------------------------
Kyrgyz Russian -28.0654   0.0 -33.9405 -22.1903   True
------------------------------------------------------


Tukey HSD Results for Region: Jalal-Abad
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj  lower    upper   reject
-------------------------------------------------------
 Kyrgyz Russian -27.6321   0.0 -33.8727 -21.3915   True
 Kyrgyz   Uzbek   19.596   0.0   12.495  26.6971   True
Russian   Uzbek  47.2281   0.0  39.2896  55.1666   True
-------------------------------------------------------


Tukey HSD Results for Region: Osh
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
 group1  group2 meandiff p-adj  lower   upper  reject
-----------------------------------------------------
 Kyrgyz Russian  -32.582   0.0 -40.503 -24.661   True
 Kyrgyz   Uzbek  45.0671   0.0 33.0054 57.1289   True
Russian   Uzbek  77.6491   0.0 64.5268 90.7714   True
-----------------------------------------------------


Tukey HSD Results for Region: Osh_city
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
 Kyrgyz Russian -24.8708 0.0023 -42.0892 -7.6524   True
 Kyrgyz   Uzbek   0.9474 0.9962 -26.1292 28.0239  False
Russian   Uzbek  25.8182 0.0228   2.9272 48.7092   True
-------------------------------------------------------


Tukey HSD Results for Region: Talas
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
group1  group2 meandiff p-adj  lower    upper   reject
------------------------------------------------------
Kyrgyz Russian    -24.3   0.0 -33.5048 -15.0952   True
------------------------------------------------------

####Listening Comp Score - Tukey Analysis
1. Batken: Kyrgyz outperformed Russian, but Tajik and Uzbek completely outperformed Kyrgyz and russian
2. Bishkek outperformed in RUssian compared to Kyrgyz
3. Kyrgyz outperformed Russian significantly
4. Jalal-Abad: Kyrgyz outperformed Russian, Uzbek outperformed Russian, UZbek outperformed Kyrgyz
5. Osh: Kyrgyz outperformed Russian, Uzbek outperformed Kyrgyz and Russian
6. Osh_City - Kyrgyz outperformed Russian, significant. Uzbek sample size is small but outperformed Russian significantly.
7. Talas: Kyrgyz outperformed russian significantly.

##Tukey Test - Two Way Group Pairings - Region Language Pairs

###Oral Reading Score Tukey Test

In [72]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['oral_read_score_pcnt'], base['Region_Language'])

# Print results
print(tukey_results)
oraltukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
oraltukey

             Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================================
      group1             group2       meandiff p-adj   lower    upper   reject
------------------------------------------------------------------------------
     Batken_Kyrgyz     Batken_Russian -24.5038 0.0002 -42.4541  -6.5534   True
     Batken_Kyrgyz       Batken_Tajik -13.0143 0.7398 -32.7575   6.7289  False
     Batken_Kyrgyz       Batken_Uzbek     4.49 0.9999  -8.6377  17.6178  False
     Batken_Kyrgyz     Bishkek_Kyrgyz  -0.0554    1.0  -12.032  11.9213  False
     Batken_Kyrgyz    Bishkek_Russian  11.5873 0.0239   0.6447  22.5299   True
     Batken_Kyrgyz        Chui_Kyrgyz  -6.9529 0.7847 -17.8005   3.8948  False
     Batken_Kyrgyz       Chui_Russian  -5.9504 0.9726 -17.5979   5.6971  False
     Batken_Kyrgyz   Issyk-Kul_Kyrgyz  -2.5818    1.0 -13.8423   8.6788  False
     Batken_Kyrgyz  Issyk-Kul_Russian  -8.6674 0.8945 -23.4748     6.14  False
     Batken_Kyrgyz  Jalal-Abad_Kyrgyz -20.0358    0.0 -30.0235 -10.0482   True
     Batken_Kyrgyz Jalal-Abad_Russian -16.9407    0.0 -28.3141  -5.5673   True
     Batken_Kyrgyz   Jalal-Abad_Uzbek -31.9597    0.0 -44.4631 -19.4564   True
     Batken_Kyrgyz       Naryn_Kyrgyz  -8.1643  0.881  -21.918   5.5894  False
     Batken_Kyrgyz      Naryn_Russian   4.4107    1.0 -21.4867  30.3081  False
     Batken_Kyrgyz         Osh_Kyrgyz -24.1312    0.0 -34.2711 -13.9914   True
     Batken_Kyrgyz        Osh_Russian -29.8722    0.0 -42.2521 -17.4922   True
     Batken_Kyrgyz          Osh_Uzbek  -8.0893 0.9922 -25.6831   9.5045  False
     Batken_Kyrgyz    Osh_city_Kyrgyz  -8.8722 0.9997 -32.8647  15.1203  False
     Batken_Kyrgyz   Osh_city_Russian  -6.8506 0.9429  -19.354   5.6527  False
     Batken_Kyrgyz     Osh_city_Uzbek -33.1143 0.0342 -65.2361  -0.9925   True
     Batken_Kyrgyz       Talas_Kyrgyz  -4.2243 0.9999  -17.073   8.6244  False
     Batken_Kyrgyz      Talas_Russian  -4.7643    1.0 -22.3581  12.8295  False
    Batken_Russian       Batken_Tajik  11.4895 0.9869 -12.4779  35.4568  False
    Batken_Russian       Batken_Uzbek  28.9938    0.0  10.0999  47.8876   True
    Batken_Russian     Bishkek_Kyrgyz  24.4484 0.0003   6.3354  42.5614   True
    Batken_Russian    Bishkek_Russian  36.0911    0.0  18.6446  53.5376   True
    Batken_Russian        Chui_Kyrgyz  17.5509 0.0446   0.1638   34.938   True
    Batken_Russian       Chui_Russian  18.5534 0.0318   0.6563  36.4504   True
    Batken_Russian   Issyk-Kul_Kyrgyz   21.922 0.0016   4.2743  39.5697   True
    Batken_Russian  Issyk-Kul_Russian  15.8363  0.379  -4.2609  35.9336  False
    Batken_Russian  Jalal-Abad_Kyrgyz   4.4679    1.0  -12.396  21.3319  False
    Batken_Russian Jalal-Abad_Russian   7.5631 0.9971 -10.1568  25.2829  False
    Batken_Russian   Jalal-Abad_Uzbek   -7.456 0.9987 -25.9215  11.0095  False
    Batken_Russian       Naryn_Kyrgyz  16.3395 0.2443  -2.9946  35.6735  False
    Batken_Russian      Naryn_Russian  28.9145 0.0572  -0.3313  58.1603  False
    Batken_Russian         Osh_Kyrgyz   0.3725    1.0  -16.582   17.327  False
    Batken_Russian        Osh_Russian  -5.3684    1.0 -23.7505  13.0137  False
    Batken_Russian          Osh_Uzbek  16.4145 0.5172  -5.8157  38.6447  False
    Batken_Russian    Osh_city_Kyrgyz  15.6316 0.9209 -11.9416  43.2048  False
    Batken_Russian   Osh_city_Russian  17.6531 0.0829  -0.8124  36.1186  False
    Batken_Russian     Osh_city_Uzbek  -8.6105    1.0 -43.4882  26.2671  False
    Batken_Russian       Talas_Kyrgyz  20.2795  0.017   1.5784  38.9805   True
    Batken_Russian      Talas_Russian  19.7395 0.1665  -2.4907  41.9697  False
      Batken_Tajik       Batken_Uzbek  17.5043 0.2353  -3.1005  38.1091  False
      Batken_Tajik     Bishkek_Kyrgyz  12.9589 0.7592  -6.9323  32.8501  False
      Batken_Tajik    Bishkek_Russian  24.6016 0.0009   5.3153  43.8879   True
      Batken_Tajik        Chui_Kyrgyz   6.0614    1.0 -13.1711   25.294  False
      Batken_Tajik       Chui_Russian   7.0639 0.9998 -12.6309  26.7587  False
      Batken_Tajik   Issyk-Kul_Kyrgyz  10.4325 0.9544  -9.0359   29.901  False
      Batken_Tajik  Issyk-Kul_Russian   4.3469    1.0 -17.3667  26.0605  False
      Batken_Tajik  Jalal-Abad_Kyrgyz  -7.0215 0.9996 -25.7825  11.7394  False
      Batken_Tajik Jalal-Abad_Russian  -3.9264    1.0 -23.4604  15.6075  False
      Batken_Tajik   Jalal-Abad_Uzbek -18.9455 0.1014 -39.1582   1.2673  False
      Batken_Tajik       Naryn_Kyrgyz     4.85    1.0 -16.1592  25.8592  False
      Batken_Tajik      Naryn_Russian   17.425 0.9119 -12.9542  47.8042  False
      Batken_Tajik         Osh_Kyrgyz  -11.117 0.8871 -29.9594   7.7254  False
      Batken_Tajik        Osh_Russian -16.8579  0.261 -36.9945   3.2787  False
      Batken_Tajik          Osh_Uzbek    4.925    1.0 -18.7765  28.6265  False
      Batken_Tajik    Osh_city_Kyrgyz   4.1421    1.0 -24.6305  32.9147  False
      Batken_Tajik   Osh_city_Russian   6.1636    1.0 -14.0491  26.3764  False
      Batken_Tajik     Osh_city_Uzbek    -20.1 0.9284 -55.9334  15.7334  False
      Batken_Tajik       Talas_Kyrgyz     8.79 0.9968 -11.6382  29.2182  False
      Batken_Tajik      Talas_Russian     8.25 0.9999 -15.4515  31.9515  False
      Batken_Uzbek     Bishkek_Kyrgyz  -4.5454 0.9999 -17.8947   8.8039  False
      Batken_Uzbek    Bishkek_Russian   7.0973 0.9155  -5.3327  19.5273  False
      Batken_Uzbek        Chui_Kyrgyz -11.4429 0.1132 -23.7893   0.9036  False
      Batken_Uzbek       Chui_Russian -10.4404 0.3487 -23.4952   2.6144  False
      Batken_Uzbek   Issyk-Kul_Kyrgyz  -7.0718 0.9338 -19.7826    5.639  False
      Batken_Uzbek  Issyk-Kul_Russian -13.1574 0.2867 -29.0955   2.7807  False
      Batken_Uzbek  Jalal-Abad_Kyrgyz -24.5258    0.0  -36.124 -12.9277   True
      Batken_Uzbek Jalal-Abad_Russian -21.4307    0.0 -34.2416  -8.6199   True
      Batken_Uzbek   Jalal-Abad_Uzbek -36.4498    0.0 -50.2736 -22.6259   True
      Batken_Uzbek       Naryn_Kyrgyz -12.6543 0.2432 -27.6185   2.3099  False
      Batken_Uzbek      Naryn_Russian  -0.0793    1.0 -26.6394  26.4808  False
      Batken_Uzbek         Osh_Kyrgyz -28.6213    0.0 -40.3507 -16.8918   True
      Batken_Uzbek        Osh_Russian -34.3622    0.0 -48.0745 -20.6499   True
      Batken_Uzbek          Osh_Uzbek -12.5793 0.6901 -31.1348   5.9762  False
      Batken_Uzbek    Osh_city_Kyrgyz -13.3622 0.9499 -38.0686  11.3442  False
      Batken_Uzbek   Osh_city_Russian -11.3407 0.2986 -25.1645   2.4832  False
      Batken_Uzbek     Osh_city_Uzbek -37.6043 0.0066 -70.2627  -4.9459   True
      Batken_Uzbek       Talas_Kyrgyz  -8.7143 0.8386 -22.8512   5.4226  False
      Batken_Uzbek      Talas_Russian  -9.2543 0.9791 -27.8098   9.3012  False
    Bishkek_Kyrgyz    Bishkek_Russian  11.6427  0.031   0.4352  22.8501   True
    Bishkek_Kyrgyz        Chui_Kyrgyz  -6.8975   0.83 -18.0122   4.2172  False
    Bishkek_Kyrgyz       Chui_Russian   -5.895 0.9806 -17.7916   6.0016  False
    Bishkek_Kyrgyz   Issyk-Kul_Kyrgyz  -2.5264    1.0 -14.0445   8.9917  False
    Bishkek_Kyrgyz  Issyk-Kul_Russian   -8.612 0.9114 -23.6162   6.3921  False
    Bishkek_Kyrgyz  Jalal-Abad_Kyrgyz -19.9805    0.0 -30.2575  -9.7034   True
    Bishkek_Kyrgyz Jalal-Abad_Russian -16.8853    0.0 -28.5138  -5.2569   True
    Bishkek_Kyrgyz   Jalal-Abad_Uzbek -31.9044    0.0 -44.6402 -19.1686   True
    Bishkek_Kyrgyz       Naryn_Kyrgyz  -8.1089 0.9017 -22.0742   5.8564  False
    Bishkek_Kyrgyz      Naryn_Russian   4.4661    1.0 -21.5443  30.4765  False
    Bishkek_Kyrgyz         Osh_Kyrgyz -24.0759    0.0 -34.5009 -13.6508   True
    Bishkek_Kyrgyz        Osh_Russian -29.8168    0.0 -42.4314 -17.2022   True
    Bishkek_Kyrgyz          Osh_Uzbek  -8.0339 0.9937 -25.7937   9.7258  False
    Bishkek_Kyrgyz    Osh_city_Kyrgyz  -8.8168 0.9997 -32.9313  15.2976  False
    Bishkek_Kyrgyz   Osh_city_Russian  -6.7953 0.9564 -19.5311   5.9405  False
    Bishkek_Kyrgyz     Osh_city_Uzbek -33.0589 0.0363 -65.2719   -0.846   True
    Bishkek_Kyrgyz       Talas_Kyrgyz  -4.1689    1.0 -17.2439   8.9061  False
    Bishkek_Kyrgyz      Talas_Russian  -4.7089    1.0 -22.4687  13.0508  False
   Bishkek_Russian        Chui_Kyrgyz -18.5402    0.0 -28.5321  -8.5483   True
   Bishkek_Russian       Chui_Russian -17.5377    0.0 -28.3927  -6.6827   True
   Bishkek_Russian   Issyk-Kul_Kyrgyz -14.1691 0.0002 -24.6078  -3.7303   True
   Bishkek_Russian  Issyk-Kul_Russian -20.2547 0.0001 -34.4472  -6.0623   True
   Bishkek_Russian  Jalal-Abad_Kyrgyz -31.6231    0.0  -40.674 -22.5722   True
   Bishkek_Russian Jalal-Abad_Russian  -28.528    0.0 -39.0884 -17.9677   True
   Bishkek_Russian   Jalal-Abad_Uzbek  -43.547    0.0 -55.3157 -31.7784   True
   Bishkek_Russian       Naryn_Kyrgyz -19.7516    0.0 -32.8409  -6.6622   True
   Bishkek_Russian      Naryn_Russian  -7.1766    1.0 -32.7274  18.3742  False
   Bishkek_Russian         Osh_Kyrgyz -35.7185    0.0 -44.9371 -26.4999   True
   Bishkek_Russian        Osh_Russian -41.4595    0.0 -53.0969 -29.8221   True
   Bishkek_Russian          Osh_Uzbek -19.6766 0.0065 -36.7561  -2.5971   True
   Bishkek_Russian    Osh_city_Kyrgyz -20.4595 0.2033 -44.0774   3.1585  False
   Bishkek_Russian   Osh_city_Russian  -18.438    0.0 -30.2066  -6.6693   True
   Bishkek_Russian     Osh_city_Uzbek -44.7016 0.0001 -76.5446 -12.8586   True
   Bishkek_Russian       Talas_Kyrgyz -15.8116 0.0006 -27.9465  -3.6767   True
   Bishkek_Russian      Talas_Russian -16.3516 0.0816 -33.4311   0.7279  False
       Chui_Kyrgyz       Chui_Russian   1.0025    1.0  -9.7568  11.7617  False
       Chui_Kyrgyz   Issyk-Kul_Kyrgyz   4.3711 0.9975   -5.968  14.7102  False
       Chui_Kyrgyz  Issyk-Kul_Russian  -1.7145    1.0 -15.8339  12.4048  False
       Chui_Kyrgyz  Jalal-Abad_Kyrgyz  -13.083    0.0 -22.0188  -4.1471   True
       Chui_Kyrgyz Jalal-Abad_Russian  -9.9878 0.0841 -20.4498   0.4741  False
       Chui_Kyrgyz   Jalal-Abad_Uzbek -25.0069    0.0 -36.6873 -13.3265   True
       Chui_Kyrgyz       Naryn_Kyrgyz  -1.2114    1.0 -14.2215  11.7987  False
       Chui_Kyrgyz      Naryn_Russian  11.3636 0.9948 -14.1467  36.8738  False
       Chui_Kyrgyz         Osh_Kyrgyz -17.1784    0.0 -26.2841  -8.0727   True
       Chui_Kyrgyz        Osh_Russian -22.9193    0.0 -34.4675 -11.3712   True
       Chui_Kyrgyz          Osh_Uzbek  -1.1364    1.0 -18.1552  15.8824  False
       Chui_Kyrgyz    Osh_city_Kyrgyz  -1.9193    1.0 -25.4934  21.6548  False
       Chui_Kyrgyz   Osh_city_Russian   0.1022    1.0 -11.5782  11.7826  False
       Chui_Kyrgyz     Osh_city_Uzbek -26.1614 0.2938 -57.9719   5.6491  False
       Chui_Kyrgyz       Talas_Kyrgyz   2.7286    1.0  -9.3208  14.7779  False
       Chui_Kyrgyz      Talas_Russian   2.1886    1.0 -14.8302  19.2074  False
      Chui_Russian   Issyk-Kul_Kyrgyz   3.3686    1.0  -7.8068  14.5441  False
      Chui_Russian  Issyk-Kul_Russian   -2.717    1.0 -17.4598  12.0257  False
      Chui_Russian  Jalal-Abad_Kyrgyz -14.0854 0.0001 -23.9769  -4.1939   True
      Chui_Russian Jalal-Abad_Russian -10.9903 0.0681 -22.2794   0.2988  False
      Chui_Russian   Jalal-Abad_Uzbek -26.0093    0.0 -38.4361 -13.5826   True
      Chui_Russian       Naryn_Kyrgyz  -2.2139    1.0  -15.898  11.4702  False
      Chui_Russian      Naryn_Russian  10.3611 0.9988 -15.4994  36.2216  False
      Chui_Russian         Osh_Kyrgyz -18.1809    0.0  -28.226  -8.1357   True
      Chui_Russian        Osh_Russian -23.9218    0.0 -36.2243 -11.6193   True
      Chui_Russian          Osh_Uzbek  -2.1389    1.0 -19.6783  15.4006  False
      Chui_Russian    Osh_city_Kyrgyz  -2.9218    1.0 -26.8744  21.0309  False
      Chui_Russian   Osh_city_Russian  -0.9003    1.0  -13.327  11.5265  False
      Chui_Russian     Osh_city_Uzbek -27.1639 0.2416 -59.2559   4.9281  False
      Chui_Russian       Talas_Kyrgyz   1.7261    1.0  -11.048  14.5003  False
      Chui_Russian      Talas_Russian   1.1861    1.0 -16.3533  18.7256  False
  Issyk-Kul_Kyrgyz  Issyk-Kul_Russian  -6.0857 0.9976 -20.5247   8.3534  False
  Issyk-Kul_Kyrgyz  Jalal-Abad_Kyrgyz -17.4541    0.0 -26.8869  -8.0212   True
  Issyk-Kul_Kyrgyz Jalal-Abad_Russian -14.3589 0.0004 -25.2484  -3.4695   True
  Issyk-Kul_Kyrgyz   Jalal-Abad_Uzbek  -29.378    0.0 -41.4428 -17.3131   True
  Issyk-Kul_Kyrgyz       Naryn_Kyrgyz  -5.5825 0.9978 -18.9388   7.7738  False
  Issyk-Kul_Kyrgyz      Naryn_Russian   6.9925    1.0 -18.6961   32.681  False
  Issyk-Kul_Kyrgyz         Osh_Kyrgyz -21.5495    0.0 -31.1434 -11.9556   True
  Issyk-Kul_Kyrgyz        Osh_Russian -27.2904    0.0 -39.2273 -15.3536   True
  Issyk-Kul_Kyrgyz          Osh_Uzbek  -5.5075    1.0 -22.7925  11.7774  False
  Issyk-Kul_Kyrgyz    Osh_city_Kyrgyz  -6.2904    1.0 -30.0574  17.4765  False
  Issyk-Kul_Kyrgyz   Osh_city_Russian  -4.2689 0.9998 -16.3338    7.796  False
  Issyk-Kul_Kyrgyz     Osh_city_Uzbek -30.5325 0.0833 -62.4862   1.4211  False
  Issyk-Kul_Kyrgyz       Talas_Kyrgyz  -1.6425    1.0 -14.0649  10.7799  False
  Issyk-Kul_Kyrgyz      Talas_Russian  -2.1825    1.0 -19.4675  15.1024  False
 Issyk-Kul_Russian  Jalal-Abad_Kyrgyz -11.3684 0.2466 -24.8383   2.1015  False
 Issyk-Kul_Russian Jalal-Abad_Russian  -8.2733 0.9175 -22.8005   6.2539  False
 Issyk-Kul_Russian   Jalal-Abad_Uzbek -23.2923    0.0 -38.7202  -7.8644   True
 Issyk-Kul_Russian       Naryn_Kyrgyz   0.5031    1.0 -15.9544  16.9606  False
 Issyk-Kul_Russian      Naryn_Russian  13.0781 0.9878 -14.3511  40.5073  False
 Issyk-Kul_Russian         Osh_Kyrgyz -15.4638  0.008  -29.047  -1.8807   True
 Issyk-Kul_Russian        Osh_Russian -21.2048 0.0001 -36.5328  -5.8768   True
 Issyk-Kul_Russian          Osh_Uzbek   0.5781    1.0 -19.2013  20.3576  False
 Issyk-Kul_Russian    Osh_city_Kyrgyz  -0.2048    1.0 -25.8431  25.4336  False
 Issyk-Kul_Russian   Osh_city_Russian   1.8168    1.0 -13.6111  17.2446  False
 Issyk-Kul_Russian     Osh_city_Uzbek -24.4469 0.5339 -57.8159   8.9222  False
 Issyk-Kul_Russian       Talas_Kyrgyz   4.4431    1.0 -11.2659  20.1522  False
 Issyk-Kul_Russian      Talas_Russian   3.9031    1.0 -15.8763  23.6826  False
 Jalal-Abad_Kyrgyz Jalal-Abad_Russian   3.0951    1.0  -6.4721  12.6624  False
 Jalal-Abad_Kyrgyz   Jalal-Abad_Uzbek -11.9239 0.0147 -22.8103  -1.0376   True
 Jalal-Abad_Kyrgyz       Naryn_Kyrgyz  11.8715  0.075  -0.4306  24.1737  False
 Jalal-Abad_Kyrgyz      Naryn_Russian  24.4465 0.0695    -0.71  49.6031  False
 Jalal-Abad_Kyrgyz         Osh_Kyrgyz  -4.0954 0.9743 -12.1573   3.9665  False
 Jalal-Abad_Kyrgyz        Osh_Russian  -9.8364 0.1271 -20.5807    0.908  False
 Jalal-Abad_Kyrgyz          Osh_Uzbek  11.9465 0.5569  -4.5374  28.4305  False
 Jalal-Abad_Kyrgyz    Osh_city_Kyrgyz  11.1636 0.9862 -12.0273  34.3546  False
 Jalal-Abad_Kyrgyz   Osh_city_Russian  13.1852 0.0027   2.2988  24.0715   True
 Jalal-Abad_Kyrgyz     Osh_city_Uzbek -13.0785 0.9981  -44.606  18.4491  False
 Jalal-Abad_Kyrgyz       Talas_Kyrgyz  15.8115 0.0001   4.5303  27.0928   True
 Jalal-Abad_Kyrgyz      Talas_Russian  15.2715 0.1136  -1.2124  31.7555  False
Jalal-Abad_Russian   Jalal-Abad_Uzbek  -15.019 0.0018 -27.1893  -2.8488   True
Jalal-Abad_Russian       Naryn_Kyrgyz   8.7764 0.7568  -4.6752   22.228  False
Jalal-Abad_Russian      Naryn_Russian  21.3514 0.2776  -4.3868  47.0896  False
Jalal-Abad_Russian         Osh_Kyrgyz  -7.1905 0.5146 -16.9166   2.5355  False
Jalal-Abad_Russian        Osh_Russian -12.9315 0.0197 -24.9749  -0.8881   True
Jalal-Abad_Russian          Osh_Uzbek   8.8514 0.9732  -8.5072  26.2101  False
Jalal-Abad_Russian    Osh_city_Kyrgyz   8.0685 0.9999 -15.7521  31.8891  False
Jalal-Abad_Russian   Osh_city_Russian  10.0901 0.2787  -2.0802  22.2603  False
Jalal-Abad_Russian     Osh_city_Uzbek -16.1736 0.9757 -48.1672    15.82  False
Jalal-Abad_Russian       Talas_Kyrgyz  12.7164 0.0416   0.1917  25.2412   True
Jalal-Abad_Russian      Talas_Russian  12.1764 0.6242  -5.1822  29.5351  False
  Jalal-Abad_Uzbek       Naryn_Kyrgyz  23.7955    0.0   9.3758  38.2151   True
  Jalal-Abad_Uzbek      Naryn_Russian  36.3705 0.0001  10.1133  62.6276   True
  Jalal-Abad_Uzbek         Osh_Kyrgyz   7.8285 0.5996  -3.1977  18.8547  False
  Jalal-Abad_Uzbek        Osh_Russian   2.0876    1.0 -11.0282  15.2033  False
  Jalal-Abad_Uzbek          Osh_Uzbek  23.8705 0.0005   5.7513  41.9896   True
  Jalal-Abad_Uzbek    Osh_city_Kyrgyz  23.0876 0.0914  -1.2928  47.4679  False
  Jalal-Abad_Uzbek   Osh_city_Russian  25.1091    0.0  11.8767  38.3414   True
  Jalal-Abad_Uzbek     Osh_city_Uzbek  -1.1545    1.0  -33.567  31.2579  False
  Jalal-Abad_Uzbek       Talas_Kyrgyz  27.7355    0.0  14.1763  41.2946   True
  Jalal-Abad_Uzbek      Talas_Russian  27.1955    0.0   9.0763  45.3146   True
      Naryn_Kyrgyz      Naryn_Russian   12.575 0.9903    -14.3    39.45  False
      Naryn_Kyrgyz         Osh_Kyrgyz  -15.967 0.0008  -28.393  -3.5409   True
      Naryn_Kyrgyz        Osh_Russian -21.7079    0.0 -36.0206  -7.3952   True
      Naryn_Kyrgyz          Osh_Uzbek    0.075    1.0 -18.9285  19.0785  False
      Naryn_Kyrgyz    Osh_city_Kyrgyz  -0.7079    1.0 -25.7525  24.3367  False
      Naryn_Kyrgyz   Osh_city_Russian   1.3136    1.0  -13.106  15.7332  False
      Naryn_Kyrgyz     Osh_city_Uzbek   -24.95  0.461  -57.865    7.965  False
      Naryn_Kyrgyz       Talas_Kyrgyz     3.94    1.0 -10.7801  18.6601  False
      Naryn_Kyrgyz      Talas_Russian      3.4    1.0 -15.6035  22.4035  False
     Naryn_Russian         Osh_Kyrgyz  -28.542 0.0088 -53.7594  -3.3246   True
     Naryn_Russian        Osh_Russian -34.2829 0.0005 -60.4814  -8.0843   True
     Naryn_Russian          Osh_Uzbek    -12.5 0.9967 -41.5283  16.5283  False
     Naryn_Russian    Osh_city_Kyrgyz -13.2829 0.9989 -46.5807  20.0149  False
     Naryn_Russian   Osh_city_Russian -11.2614 0.9969 -37.5185  14.9958  False
     Naryn_Russian     Osh_city_Uzbek  -37.525 0.0899 -77.0839   2.0339  False
     Naryn_Russian       Talas_Kyrgyz   -8.635    1.0 -35.0583  17.7883  False
     Naryn_Russian      Talas_Russian   -9.175    1.0 -38.2033  19.8533  False
        Osh_Kyrgyz        Osh_Russian  -5.7409 0.9614 -16.6269   5.1451  False
        Osh_Kyrgyz          Osh_Uzbek   16.042 0.0727  -0.5347  32.6186  False
        Osh_Kyrgyz    Osh_city_Kyrgyz  15.2591 0.7476  -7.9978   38.516  False
        Osh_Kyrgyz   Osh_city_Russian  17.2806    0.0   6.2544  28.3068   True
        Osh_Kyrgyz     Osh_city_Uzbek   -8.983    1.0 -40.5592  22.5931  False
        Osh_Kyrgyz       Talas_Kyrgyz   19.907    0.0   8.4907  31.3232   True
        Osh_Kyrgyz      Talas_Russian   19.367 0.0051   2.7903  35.9436   True
       Osh_Russian          Osh_Uzbek  21.7829 0.0028   3.7487  39.8171   True
       Osh_Russian    Osh_city_Kyrgyz     21.0 0.2082  -3.3173  45.3173  False
       Osh_Russian   Osh_city_Russian  23.0215    0.0   9.9058  36.1373   True
       Osh_Russian     Osh_city_Uzbek  -3.2421    1.0 -35.6072   29.123  False
       Osh_Russian       Talas_Kyrgyz  25.6479    0.0  12.2025  39.0933   True
       Osh_Russian      Talas_Russian  25.1079 0.0001   7.0737  43.1421   True
         Osh_Uzbek    Osh_city_Kyrgyz  -0.7829    1.0 -28.1253  26.5595  False
         Osh_Uzbek   Osh_city_Russian   1.2386    1.0 -16.8805  19.3578  False
         Osh_Uzbek     Osh_city_Uzbek  -25.025 0.5669 -59.7205   9.6705  False
         Osh_Uzbek       Talas_Kyrgyz    3.865    1.0 -14.4941  22.2241  False
         Osh_Uzbek      Talas_Russian    3.325    1.0 -18.6184  25.2684  False
   Osh_city_Kyrgyz   Osh_city_Russian   2.0215    1.0 -22.3588  26.4019  False
   Osh_city_Kyrgyz     Osh_city_Uzbek -24.2421 0.8046 -62.5811  14.0968  False
   Osh_city_Kyrgyz       Talas_Kyrgyz   4.6479    1.0 -19.9113  29.2071  False
   Osh_city_Kyrgyz      Talas_Russian   4.1079    1.0 -23.2345  31.4503  False
  Osh_city_Russian     Osh_city_Uzbek -26.2636 0.3225 -58.6761   6.1489  False
  Osh_city_Russian       Talas_Kyrgyz   2.6264    1.0 -10.9328  16.1855  False

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-24.5038,0.0002,-42.4541,-6.5534,True
1,Batken_Kyrgyz,Batken_Tajik,-13.0143,0.7398,-32.7575,6.7289,False
2,Batken_Kyrgyz,Batken_Uzbek,4.4900,0.9999,-8.6377,17.6178,False
3,Batken_Kyrgyz,Bishkek_Kyrgyz,-0.0554,1.0000,-12.0320,11.9213,False
4,Batken_Kyrgyz,Bishkek_Russian,11.5873,0.0239,0.6447,22.5299,True
...,...,...,...,...,...,...,...
248,Osh_city_Russian,Talas_Kyrgyz,2.6264,1.0000,-10.9328,16.1855,False
249,Osh_city_Russian,Talas_Russian,2.0864,1.0000,-16.0328,20.2055,False
250,Osh_city_Uzbek,Talas_Kyrgyz,28.8900,0.1670,-3.6573,61.4373,False
251,Osh_city_Uzbek,Talas_Russian,28.3500,0.3062,-6.3455,63.0455,False
252,Talas_Kyrgyz,Talas_Russian,-0.5400,1.0000,-18.8991,17.8191,False

###Reading Comprehension Score Tukey Test

In [73]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['read_comp_score_pcnt'], base['Region_Language'])

# Print results
readcomptukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])
readcomptukey

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-36.7744,0.0000,-57.1362,-16.4127,True
1,Batken_Kyrgyz,Batken_Tajik,-22.8095,0.0400,-45.2050,-0.4141,True
2,Batken_Kyrgyz,Batken_Uzbek,18.6528,0.0014,3.7615,33.5441,True
3,Batken_Kyrgyz,Bishkek_Kyrgyz,-0.7320,1.0000,-14.3176,12.8536,False
4,Batken_Kyrgyz,Bishkek_Russian,15.7513,0.0010,3.3387,28.1639,True
...,...,...,...,...,...,...,...
248,Osh_city_Russian,Talas_Kyrgyz,9.6364,0.8174,-5.7442,25.0170,False
249,Osh_city_Russian,Talas_Russian,2.6364,1.0000,-17.9168,23.1896,False
250,Osh_city_Uzbek,Talas_Kyrgyz,10.0000,1.0000,-26.9196,46.9196,False
251,Osh_city_Uzbek,Talas_Russian,3.0000,1.0000,-36.3564,42.3564,False
252,Talas_Kyrgyz,Talas_Russian,-7.0000,0.9999,-27.8254,13.8254,False

###Silent Reading Score Tukey Test

In [74]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['word_score_pcnt'], base['Region_Language'])
wordscoretukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Print results
print(tukey_results)
wordscoretukey

             Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================================
      group1             group2       meandiff p-adj   lower    upper   reject
------------------------------------------------------------------------------
     Batken_Kyrgyz     Batken_Russian -16.8222 0.0531 -33.7312   0.0868  False
     Batken_Kyrgyz       Batken_Tajik   18.069 0.0696  -0.5288  36.6669  False
     Batken_Kyrgyz       Batken_Uzbek  33.5561    0.0  21.1899  45.9223   True
     Batken_Kyrgyz     Bishkek_Kyrgyz   3.7272 0.9999  -7.5547  15.0091  False
     Batken_Kyrgyz    Bishkek_Russian  11.5183 0.0108   1.2104  21.8261   True
     Batken_Kyrgyz        Chui_Kyrgyz  24.2063    0.0  13.9879  34.4246   True
     Batken_Kyrgyz       Chui_Russian  -5.3032 0.9856  -16.275   5.6686  False
     Batken_Kyrgyz   Issyk-Kul_Kyrgyz   0.7574    1.0  -9.8499  11.3647  False
     Batken_Kyrgyz  Issyk-Kul_Russian   2.3513    1.0 -11.5971  16.2998  False
     Batken_Kyrgyz  Jalal-Abad_Kyrgyz   6.6846 0.5982  -2.7236  16.0928  False
     Batken_Kyrgyz Jalal-Abad_Russian  -6.4473 0.8667 -17.1609   4.2663  False
     Batken_Kyrgyz   Jalal-Abad_Uzbek   7.5266 0.7892  -4.2514  19.3047  False
     Batken_Kyrgyz       Naryn_Kyrgyz   7.8982  0.852  -5.0576  20.8541  False
     Batken_Kyrgyz      Naryn_Russian  16.6482 0.6777  -7.7469  41.0433  False
     Batken_Kyrgyz         Osh_Kyrgyz   -5.977  0.819 -15.5286   3.5746  False
     Batken_Kyrgyz        Osh_Russian -20.7695    0.0 -32.4313  -9.1078   True
     Batken_Kyrgyz          Osh_Uzbek  34.1357    0.0  17.5625  50.7089   True
     Batken_Kyrgyz    Osh_city_Kyrgyz  23.8883 0.0245   1.2877   46.489   True
     Batken_Kyrgyz   Osh_city_Russian   1.1539    1.0 -10.6242   12.932  False
     Batken_Kyrgyz     Osh_city_Uzbek   0.9357    1.0 -29.3227  31.1941  False
     Batken_Kyrgyz       Talas_Kyrgyz  10.6357 0.1815  -1.4676  22.7391  False
     Batken_Kyrgyz      Talas_Russian  -0.8643    1.0 -17.4375  15.7089  False
    Batken_Russian       Batken_Tajik  34.8912    0.0  12.3142  57.4682   True
    Batken_Russian       Batken_Uzbek  50.3783    0.0  32.5805  68.1761   True
    Batken_Russian     Bishkek_Kyrgyz  20.5494  0.003   3.4871  37.6116   True
    Batken_Russian    Bishkek_Russian  28.3404    0.0   11.906  44.7748   True
    Batken_Russian        Chui_Kyrgyz  41.0285    0.0    24.65  57.4069   True
    Batken_Russian       Chui_Russian   11.519 0.6755  -5.3398  28.3778  False
    Batken_Russian   Issyk-Kul_Kyrgyz  17.5796 0.0244   0.9557  34.2035   True
    Batken_Russian  Issyk-Kul_Russian  19.1735 0.0429   0.2421  38.1049   True
    Batken_Russian  Jalal-Abad_Kyrgyz  23.5068    0.0   7.6211  39.3924   True
    Batken_Russian Jalal-Abad_Russian  10.3749  0.828  -6.3171  27.0668  False
    Batken_Russian   Jalal-Abad_Uzbek  24.3488 0.0001   6.9545  41.7431   True
    Batken_Russian       Naryn_Kyrgyz  24.7204 0.0002    6.508  42.9328   True
    Batken_Russian      Naryn_Russian  33.4704 0.0025   5.9212  61.0196   True
    Batken_Russian         Osh_Kyrgyz  10.8452 0.6871  -5.1258  26.8161  False
    Batken_Russian        Osh_Russian  -3.9474    1.0 -21.2631  13.3684  False
    Batken_Russian          Osh_Uzbek  50.9579    0.0  30.0173  71.8985   True
    Batken_Russian    Osh_city_Kyrgyz  40.7105    0.0  14.7369  66.6842   True
    Batken_Russian   Osh_city_Russian  17.9761 0.0332   0.5818  35.3704   True
    Batken_Russian     Osh_city_Uzbek  17.7579 0.9502 -15.0964  50.6122  False
    Batken_Russian       Talas_Kyrgyz  27.4579    0.0   9.8417  45.0741   True
    Batken_Russian      Talas_Russian  15.9579 0.4496  -4.9827  36.8985  False
      Batken_Tajik       Batken_Uzbek  15.4871 0.3533  -3.9224  34.8966  False
      Batken_Tajik     Bishkek_Kyrgyz -14.3419 0.4402 -33.0792   4.3954  False
      Batken_Tajik    Bishkek_Russian  -6.5508 0.9998 -24.7183  11.6167  False
      Batken_Tajik        Chui_Kyrgyz   6.1372 0.9999 -11.9796  24.2541  False
      Batken_Tajik       Chui_Russian -23.3722 0.0012 -41.9245    -4.82   True
      Batken_Tajik   Issyk-Kul_Kyrgyz -17.3116 0.0944 -35.6507   1.0274  False
      Batken_Tajik  Issyk-Kul_Russian -15.7177 0.4318 -36.1717   4.7362  False
      Batken_Tajik  Jalal-Abad_Kyrgyz -11.3845  0.777 -29.0571   6.2881  False
      Batken_Tajik Jalal-Abad_Russian -24.5164 0.0004 -42.9171  -6.1156   True
      Batken_Tajik   Jalal-Abad_Uzbek -10.5424 0.9368 -29.5826   8.4978  False
      Batken_Tajik       Naryn_Kyrgyz -10.1708 0.9708 -29.9612   9.6196  False
      Batken_Tajik      Naryn_Russian  -1.4208    1.0 -30.0377   27.196  False
      Batken_Tajik         Osh_Kyrgyz -24.0461 0.0002 -41.7954  -6.2967   True
      Batken_Tajik        Osh_Russian -38.8386    0.0 -57.8071 -19.8701   True
      Batken_Tajik          Osh_Uzbek  16.0667 0.5717  -6.2599  38.3933  False
      Batken_Tajik    Osh_city_Kyrgyz   5.8193    1.0 -21.2841  32.9227  False
      Batken_Tajik   Osh_city_Russian -16.9152 0.1658 -35.9553    2.125  False
      Batken_Tajik     Osh_city_Uzbek -17.1333 0.9745  -50.888  16.6213  False
      Batken_Tajik       Talas_Kyrgyz  -7.4333 0.9993 -26.6764  11.8098  False
      Batken_Tajik      Talas_Russian -18.9333 0.2384 -41.2599   3.3933  False
      Batken_Uzbek     Bishkek_Kyrgyz  -29.829    0.0 -42.4038 -17.2541   True
      Batken_Uzbek    Bishkek_Russian -22.0379    0.0 -33.7468  -10.329   True
      Batken_Uzbek        Chui_Kyrgyz  -9.3499 0.3382 -20.9801   2.2804  False
      Batken_Uzbek       Chui_Russian -38.8593    0.0 -51.1568 -26.5619   True
      Batken_Uzbek   Issyk-Kul_Kyrgyz -32.7987    0.0 -44.7722 -20.8253   True
      Batken_Uzbek  Issyk-Kul_Russian -31.2048    0.0 -46.2183 -16.1913   True
      Batken_Uzbek  Jalal-Abad_Kyrgyz -26.8716    0.0 -37.7968 -15.9463   True
      Batken_Uzbek Jalal-Abad_Russian -40.0034    0.0 -52.0711 -27.9358   True
      Batken_Uzbek   Jalal-Abad_Uzbek -26.0295    0.0 -39.0514 -13.0076   True
      Batken_Uzbek       Naryn_Kyrgyz -25.6579    0.0 -39.7541 -11.5618   True
      Batken_Uzbek      Naryn_Russian -16.9079 0.6959 -41.9273   8.1114  False
      Batken_Uzbek         Osh_Kyrgyz -39.5332    0.0 -50.5822 -28.4841   True
      Batken_Uzbek        Osh_Russian -54.3257    0.0 -67.2425 -41.4089   True
      Batken_Uzbek          Osh_Uzbek   0.5796    1.0 -16.8995  18.0586  False
      Batken_Uzbek    Osh_city_Kyrgyz  -9.6678  0.998 -32.9409  13.6053  False
      Batken_Uzbek   Osh_city_Russian -32.4022    0.0 -45.4241 -19.3804   True
      Batken_Uzbek     Osh_city_Uzbek -32.6204 0.0235 -63.3843  -1.8566   True
      Batken_Uzbek       Talas_Kyrgyz -22.9204    0.0 -36.2373  -9.6036   True
      Batken_Uzbek      Talas_Russian -34.4204    0.0 -51.8995 -16.9414   True
    Bishkek_Kyrgyz    Bishkek_Russian   7.7911 0.5184  -2.7662  18.3483  False
    Bishkek_Kyrgyz        Chui_Kyrgyz  20.4791    0.0  10.0091   30.949   True
    Bishkek_Kyrgyz       Chui_Russian  -9.0304 0.3335 -20.2368   2.1761  False
    Bishkek_Kyrgyz   Issyk-Kul_Kyrgyz  -2.9698    1.0 -13.8197   7.8801  False
    Bishkek_Kyrgyz  Issyk-Kul_Russian  -1.3758    1.0 -15.5096  12.7579  False
    Bishkek_Kyrgyz  Jalal-Abad_Kyrgyz   2.9574    1.0  -6.7235  12.6383  False
    Bishkek_Kyrgyz Jalal-Abad_Russian -10.1745 0.1108 -21.1283   0.7794  False
    Bishkek_Kyrgyz   Jalal-Abad_Uzbek   3.7994    1.0  -8.1975  15.7964  False
    Bishkek_Kyrgyz       Naryn_Kyrgyz    4.171    1.0  -8.9842  17.3262  False
    Bishkek_Kyrgyz      Naryn_Russian   12.921 0.9614 -11.5805  37.4225  False
    Bishkek_Kyrgyz         Osh_Kyrgyz  -9.7042 0.0575 -19.5245   0.1161  False
    Bishkek_Kyrgyz        Osh_Russian -24.4967    0.0 -36.3796 -12.6139   True
    Bishkek_Kyrgyz          Osh_Uzbek  30.4085    0.0   13.679   47.138   True
    Bishkek_Kyrgyz    Osh_city_Kyrgyz  20.1612 0.1671  -2.5544  42.8767  False
    Bishkek_Kyrgyz   Osh_city_Russian  -2.5733    1.0 -14.5703   9.4237  False
    Bishkek_Kyrgyz     Osh_city_Uzbek  -2.7915    1.0 -33.1357  27.5528  False
    Bishkek_Kyrgyz       Talas_Kyrgyz   6.9085 0.9284   -5.408   19.225  False
    Bishkek_Kyrgyz      Talas_Russian  -4.5915    1.0  -21.321   12.138  False
   Bishkek_Russian        Chui_Kyrgyz   12.688 0.0003   3.2758  22.1003   True
   Bishkek_Russian       Chui_Russian -16.8214    0.0 -27.0467  -6.5962   True
   Bishkek_Russian   Issyk-Kul_Kyrgyz -10.7609 0.0149  -20.594  -0.9277   True
   Bishkek_Russian  Issyk-Kul_Russian  -9.1669 0.6688  -22.536   4.2022  False
   Bishkek_Russian  Jalal-Abad_Kyrgyz  -4.8337 0.9208 -13.3595   3.6922  False
   Bishkek_Russian Jalal-Abad_Russian -17.9656    0.0 -27.9133  -8.0178   True
   Bishkek_Russian   Jalal-Abad_Uzbek  -3.9916 0.9998 -15.0776   7.0943  False
   Bishkek_Russian       Naryn_Kyrgyz    -3.62    1.0 -15.9501     8.71  False
   Bishkek_Russian      Naryn_Russian     5.13    1.0 -18.9386  29.1985  False
   Bishkek_Russian         Osh_Kyrgyz -17.4953    0.0 -26.1791  -8.8114   True
   Bishkek_Russian        Osh_Russian -32.2878    0.0 -43.2501 -21.3255   True
   Bishkek_Russian          Osh_Uzbek  22.6175 0.0001   6.5288  38.7062   True
   Bishkek_Russian    Osh_city_Kyrgyz  12.3701 0.9341  -9.8777  34.6179  False
   Bishkek_Russian   Osh_city_Russian -10.3644  0.104 -21.4503   0.7216  False
   Bishkek_Russian     Osh_city_Uzbek -10.5825 0.9998 -40.5783  19.4132  False
   Bishkek_Russian       Talas_Kyrgyz  -0.8825    1.0 -12.3135  10.5484  False
   Bishkek_Russian      Talas_Russian -12.3825 0.4285 -28.4712   3.7062  False
       Chui_Kyrgyz       Chui_Russian -29.5094    0.0 -39.6445 -19.3744   True
       Chui_Kyrgyz   Issyk-Kul_Kyrgyz -23.4489    0.0 -33.1882 -13.7095   True
       Chui_Kyrgyz  Issyk-Kul_Russian -21.8549    0.0 -35.1552  -8.5546   True
       Chui_Kyrgyz  Jalal-Abad_Kyrgyz -17.5217    0.0 -25.9392  -9.1042   True
       Chui_Kyrgyz Jalal-Abad_Russian -30.6536    0.0 -40.5086 -20.7986   True
       Chui_Kyrgyz   Jalal-Abad_Uzbek -16.6796    0.0 -27.6825  -5.6768   True
       Chui_Kyrgyz       Naryn_Kyrgyz -16.3081 0.0004 -28.5634  -4.0527   True
       Chui_Kyrgyz      Naryn_Russian  -7.5581    1.0 -31.5884  16.4723  False
       Chui_Kyrgyz         Osh_Kyrgyz -30.1833    0.0 -38.7607 -21.6058   True
       Chui_Kyrgyz        Osh_Russian -44.9758    0.0 -55.8541 -34.0976   True
       Chui_Kyrgyz          Osh_Uzbek   9.9294 0.8325  -6.1021   25.961  False
       Chui_Kyrgyz    Osh_city_Kyrgyz  -0.3179    1.0 -22.5245  21.8886  False
       Chui_Kyrgyz   Osh_city_Russian -23.0524    0.0 -34.0552 -12.0496   True
       Chui_Kyrgyz     Osh_city_Uzbek -23.2706 0.4095 -53.2357   6.6946  False
       Chui_Kyrgyz       Talas_Kyrgyz -13.5706 0.0034 -24.9209  -2.2202   True
       Chui_Kyrgyz      Talas_Russian -25.0706    0.0 -41.1021   -9.039   True
      Chui_Russian   Issyk-Kul_Kyrgyz   6.0606 0.9089  -4.4665  16.5877  False
      Chui_Russian  Issyk-Kul_Russian   7.6545 0.9395   -6.233   21.542  False
      Chui_Russian  Jalal-Abad_Kyrgyz  11.9878 0.0008   2.6701  21.3055   True
      Chui_Russian Jalal-Abad_Russian  -1.1441    1.0 -11.7783   9.4901  False
      Chui_Russian   Jalal-Abad_Uzbek  12.8298 0.0145   1.1239  24.5357   True
      Chui_Russian       Naryn_Kyrgyz  13.2014 0.0373   0.3111  26.0916   True
      Chui_Russian      Naryn_Russian  21.9514 0.1467  -2.4089  46.3117  False
      Chui_Russian         Osh_Kyrgyz  -0.6738    1.0 -10.1363   8.7886  False
      Chui_Russian        Osh_Russian -15.4664 0.0003 -27.0552  -3.8775   True
      Chui_Russian          Osh_Uzbek  39.4389    0.0  22.9169  55.9608   True
      Chui_Russian    Osh_city_Kyrgyz  29.1915 0.0007   6.6284  51.7547   True
      Chui_Russian   Osh_city_Russian   6.4571  0.939  -5.2488  18.1629  False
      Chui_Russian     Osh_city_Uzbek   6.2389    1.0 -23.9915  36.4692  False
      Chui_Russian       Talas_Kyrgyz  15.9389 0.0004   3.9058   27.972   True
      Chui_Russian      Talas_Russian   4.4389    1.0 -12.0831  20.9608  False
  Issyk-Kul_Kyrgyz  Issyk-Kul_Russian   1.5939    1.0 -12.0075  15.1953  False
  Issyk-Kul_Kyrgyz  Jalal-Abad_Kyrgyz   5.9272 0.7193  -2.9585  14.8128  False
  Issyk-Kul_Kyrgyz Jalal-Abad_Russian  -7.2047 0.6216 -17.4625   3.0531  False
  Issyk-Kul_Kyrgyz   Jalal-Abad_Uzbek   6.7692 0.8776  -4.5957  18.1342  False
  Issyk-Kul_Kyrgyz       Naryn_Kyrgyz   7.1408   0.92  -5.4407  19.7223  False
  Issyk-Kul_Kyrgyz      Naryn_Russian  15.8908 0.7462  -8.3075  40.0892  False
  Issyk-Kul_Kyrgyz         Osh_Kyrgyz  -6.7344 0.4976 -15.7717   2.3029  False
  Issyk-Kul_Kyrgyz        Osh_Russian -21.5269    0.0 -32.7714 -10.2825   True
  Issyk-Kul_Kyrgyz          Osh_Uzbek  33.3783    0.0  17.0961  49.6605   True
  Issyk-Kul_Kyrgyz    Osh_city_Kyrgyz  23.1309 0.0333   0.7428  45.5191   True
  Issyk-Kul_Kyrgyz   Osh_city_Russian   0.3965    1.0 -10.9685  11.7615  False
  Issyk-Kul_Kyrgyz     Osh_city_Uzbek   0.1783    1.0 -29.9217  30.2783  False
  Issyk-Kul_Kyrgyz       Talas_Kyrgyz   9.8783 0.2462  -1.8234  21.5801  False
  Issyk-Kul_Kyrgyz      Talas_Russian  -1.6217    1.0 -17.9039  14.6605  False
 Issyk-Kul_Russian  Jalal-Abad_Kyrgyz   4.3332 0.9999  -8.3552  17.0217  False
 Issyk-Kul_Russian Jalal-Abad_Russian  -8.7986 0.7799 -22.4831   4.8858  False
 Issyk-Kul_Russian   Jalal-Abad_Uzbek   5.1753 0.9998  -9.3576  19.7082  False
 Issyk-Kul_Russian       Naryn_Kyrgyz   5.5469 0.9998  -9.9559  21.0497  False
 Issyk-Kul_Russian      Naryn_Russian  14.2969 0.9372 -11.5411  40.1349  False
 Issyk-Kul_Russian         Osh_Kyrgyz  -8.3283 0.7607 -21.1235   4.4668  False
 Issyk-Kul_Russian        Osh_Russian -23.1209    0.0 -37.5597  -8.6821   True
 Issyk-Kul_Russian          Osh_Uzbek  31.7844    0.0  13.1523  50.4164   True
 Issyk-Kul_Russian    Osh_city_Kyrgyz   21.537 0.1606  -2.6141  45.6881  False
 Issyk-Kul_Russian   Osh_city_Russian  -1.1974    1.0 -15.7303  13.3355  False
 Issyk-Kul_Russian     Osh_city_Uzbek  -1.4156    1.0 -32.8489  30.0177  False
 Issyk-Kul_Russian       Talas_Kyrgyz   8.2844 0.9297  -6.5134  23.0821  False
 Issyk-Kul_Russian      Talas_Russian  -3.2156    1.0 -21.8477  15.4164  False
 Jalal-Abad_Kyrgyz Jalal-Abad_Russian -13.1319    0.0 -22.1442  -4.1196   True
 Jalal-Abad_Kyrgyz   Jalal-Abad_Uzbek    0.842    1.0  -9.4128  11.0969  False
 Jalal-Abad_Kyrgyz       Naryn_Kyrgyz   1.2136    1.0 -10.3749  12.8021  False
 Jalal-Abad_Kyrgyz      Naryn_Russian   9.9636 0.9977 -13.7336  33.6609  False
 Jalal-Abad_Kyrgyz         Osh_Kyrgyz -12.6616    0.0 -20.2558  -5.0674   True
 Jalal-Abad_Kyrgyz        Osh_Russian -27.4541    0.0 -37.5752 -17.3331   True
 Jalal-Abad_Kyrgyz          Osh_Uzbek  27.4511    0.0  11.9234  42.9788   True
 Jalal-Abad_Kyrgyz    Osh_city_Kyrgyz  17.2038 0.3802  -4.6418  39.0494  False
 Jalal-Abad_Kyrgyz   Osh_city_Russian  -5.5307 0.9513 -15.7855   4.7241  False
 Jalal-Abad_Kyrgyz     Osh_city_Uzbek  -5.7489    1.0 -35.4475  23.9497  False
 Jalal-Abad_Kyrgyz       Talas_Kyrgyz   3.9511 0.9996  -6.6757   14.578  False
 Jalal-Abad_Kyrgyz      Talas_Russian  -7.5489 0.9845 -23.0766   7.9788  False
Jalal-Abad_Russian   Jalal-Abad_Uzbek  13.9739 0.0023   2.5097  25.4382   True
Jalal-Abad_Russian       Naryn_Kyrgyz  14.3455 0.0087   1.6743  27.0168   True
Jalal-Abad_Russian      Naryn_Russian  23.0955  0.086  -1.1496  47.3406  False
Jalal-Abad_Russian         Osh_Kyrgyz   0.4703    1.0  -8.6916   9.6322  False
Jalal-Abad_Russian        Osh_Russian -14.3222 0.0012  -25.667  -2.9775   True
Jalal-Abad_Russian          Osh_Uzbek   40.583    0.0  24.2314  56.9347   True
Jalal-Abad_Russian    Osh_city_Kyrgyz  30.3357 0.0002   7.8969  52.7744   True
Jalal-Abad_Russian   Osh_city_Russian   7.6012 0.7299   -3.863  19.0654  False
Jalal-Abad_Russian     Osh_city_Uzbek    7.383    1.0 -22.7546  37.5206  False
Jalal-Abad_Russian       Talas_Kyrgyz   17.083    0.0   5.2848  28.8812   True
Jalal-Abad_Russian      Talas_Russian    5.583 0.9999 -10.7686  21.9347  False
  Jalal-Abad_Uzbek       Naryn_Kyrgyz   0.3716    1.0 -13.2115  13.9547  False
  Jalal-Abad_Uzbek      Naryn_Russian   9.1216 0.9997 -15.6123  33.8555  False
  Jalal-Abad_Uzbek         Osh_Kyrgyz -13.5036 0.0006 -23.8902  -3.1171   True
  Jalal-Abad_Uzbek        Osh_Russian -28.2962    0.0 -40.6511 -15.9413   True
  Jalal-Abad_Uzbek          Osh_Uzbek  26.6091    0.0   9.5411  43.6771   True
  Jalal-Abad_Uzbek    Osh_city_Kyrgyz  16.3617 0.5926  -6.6043  39.3277  False
  Jalal-Abad_Uzbek   Osh_city_Russian  -6.3727 0.9724 -18.8374    6.092  False
  Jalal-Abad_Uzbek     Osh_city_Uzbek  -6.5909    1.0 -37.1231  23.9413  False
  Jalal-Abad_Uzbek       Talas_Kyrgyz   3.1091    1.0  -9.6634  15.8816  False
  Jalal-Abad_Uzbek      Talas_Russian  -8.3909 0.9823 -25.4589   8.6771  False
      Naryn_Kyrgyz      Naryn_Russian     8.75 0.9999  -16.566   34.066  False
      Naryn_Kyrgyz         Osh_Kyrgyz -13.8752  0.004 -25.5804    -2.17   True
      Naryn_Kyrgyz        Osh_Russian -28.6678    0.0 -42.1502 -15.1854   True
      Naryn_Kyrgyz          Osh_Uzbek  26.2375    0.0   8.3364  44.1386   True
      Naryn_Kyrgyz    Osh_city_Kyrgyz  15.9901 0.6905  -7.6016  39.5819  False
      Naryn_Kyrgyz   Osh_city_Russian  -6.7443 0.9802 -20.3274   6.8388  False
      Naryn_Kyrgyz     Osh_city_Uzbek  -6.9625    1.0 -37.9681  24.0431  False
      Naryn_Kyrgyz       Talas_Kyrgyz   2.7375    1.0 -11.1286  16.6036  False
      Naryn_Kyrgyz      Talas_Russian  -8.7625 0.9832 -26.6636   9.1386  False
     Naryn_Russian         Osh_Kyrgyz -22.6252 0.0861 -46.3797   1.1293  False
     Naryn_Russian        Osh_Russian -37.4178    0.0 -62.0965  -12.739   True
     Naryn_Russian          Osh_Uzbek  17.4875  0.788  -9.8569  44.8319  False
     Naryn_Russian    Osh_city_Kyrgyz   7.2401    1.0  -24.126  38.6063  False
     Naryn_Russian   Osh_city_Russian -15.4943 0.8176 -40.2282   9.2396  False
     Naryn_Russian     Osh_city_Uzbek -15.7125 0.9976 -52.9766  21.5516  False
     Naryn_Russian       Talas_Kyrgyz  -6.0125    1.0  -30.903   18.878  False
     Naryn_Russian      Talas_Russian -17.5125 0.7859 -44.8569   9.8319  False
        Osh_Kyrgyz        Osh_Russian -14.7925    0.0  -25.047  -4.5381   True
        Osh_Kyrgyz          Osh_Uzbek  40.1127    0.0  24.4977  55.7277   True
        Osh_Kyrgyz    Osh_city_Kyrgyz  29.8654 0.0002   7.9576  51.7731   True
        Osh_Kyrgyz   Osh_city_Russian   7.1309 0.6663  -3.2556  17.5174  False
        Osh_Kyrgyz     Osh_city_Uzbek   6.9127    1.0 -22.8316  36.6571  False
        Osh_Kyrgyz       Talas_Kyrgyz  16.6127    0.0   5.8587  27.3667   True
        Osh_Kyrgyz      Talas_Russian   5.1127    1.0 -10.5023  20.7277  False
       Osh_Russian          Osh_Uzbek  54.9053    0.0  37.9173  71.8932   True
       Osh_Russian    Osh_city_Kyrgyz  44.6579    0.0  21.7513  67.5645   True
       Osh_Russian   Osh_city_Russian  21.9234    0.0   9.5685  34.2783   True
       Osh_Russian     Osh_city_Uzbek  21.7053  0.594  -8.7823  52.1928  False
       Osh_Russian       Talas_Kyrgyz  31.4053    0.0  18.7399  44.0706   True
       Osh_Russian      Talas_Russian  19.9053 0.0049   2.9173  36.8932   True
         Osh_Uzbek    Osh_city_Kyrgyz -10.2474 0.9989 -36.0036  15.5089  False
         Osh_Uzbek   Osh_city_Russian -32.9818    0.0 -50.0498 -15.9138   True
         Osh_Uzbek     Osh_city_Uzbek    -33.2 0.0413 -65.8828  -0.5172   True
         Osh_Uzbek       Talas_Kyrgyz    -23.5 0.0002 -40.7941  -6.2059   True
         Osh_Uzbek      Talas_Russian    -35.0    0.0 -55.6704 -14.3296   True
   Osh_city_Kyrgyz   Osh_city_Russian -22.7344 0.0563 -45.7005   0.2316  False
   Osh_city_Kyrgyz     Osh_city_Uzbek -22.9526 0.7973 -59.0675  13.1622  False
   Osh_city_Kyrgyz       Talas_Kyrgyz -13.2526 0.9129 -36.3872   9.8819  False
   Osh_city_Kyrgyz      Talas_Russian -24.7526 0.0784 -50.5089   1.0036  False
  Osh_city_Russian     Osh_city_Uzbek  -0.2182    1.0 -30.7504   30.314  False
  Osh_city_Russian       Talas_Kyrgyz   9.4818 0.5058  -3.2907  22.2544  False

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-16.8222,0.0531,-33.7312,0.0868,False
1,Batken_Kyrgyz,Batken_Tajik,18.0690,0.0696,-0.5288,36.6669,False
2,Batken_Kyrgyz,Batken_Uzbek,33.5561,0.0000,21.1899,45.9223,True
3,Batken_Kyrgyz,Bishkek_Kyrgyz,3.7272,0.9999,-7.5547,15.0091,False
4,Batken_Kyrgyz,Bishkek_Russian,11.5183,0.0108,1.2104,21.8261,True
...,...,...,...,...,...,...,...
248,Osh_city_Russian,Talas_Kyrgyz,9.4818,0.5058,-3.2907,22.2544,False
249,Osh_city_Russian,Talas_Russian,-2.0182,1.0000,-19.0862,15.0498,False
250,Osh_city_Uzbek,Talas_Kyrgyz,9.7000,1.0000,-20.9592,40.3592,False
251,Osh_city_Uzbek,Talas_Russian,-1.8000,1.0000,-34.4828,30.8828,False
252,Talas_Kyrgyz,Talas_Russian,-11.5000,0.7248,-28.7941,5.7941,False

###Invented Word Score Tukey Test

In [75]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['invent_word_score_pcnt'], base['Region_Language'])
inventtukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Print results
print(tukey_results)
inventtukey

             Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================================
      group1             group2       meandiff p-adj   lower    upper   reject
------------------------------------------------------------------------------
     Batken_Kyrgyz     Batken_Russian -15.4887 0.0715 -31.4691   0.4917  False
     Batken_Kyrgyz       Batken_Tajik  -6.5238 0.9996 -24.1004  11.0527  False
     Batken_Kyrgyz       Batken_Uzbek  -2.8141    1.0 -14.5012    8.873  False
     Batken_Kyrgyz     Bishkek_Kyrgyz   3.3754    1.0  -7.2869  14.0377  False
     Batken_Kyrgyz    Bishkek_Russian  13.7143 0.0001   3.9725   23.456   True
     Batken_Kyrgyz        Chui_Kyrgyz   -3.984 0.9982 -13.6413   5.6732  False
     Batken_Kyrgyz       Chui_Russian  -1.3571    1.0 -11.7264   9.0121  False
     Batken_Kyrgyz   Issyk-Kul_Kyrgyz  -4.8812 0.9842 -14.9061   5.1436  False
     Batken_Kyrgyz  Issyk-Kul_Russian  -4.4821 0.9999 -17.6646   8.7003  False
     Batken_Kyrgyz  Jalal-Abad_Kyrgyz -16.3877    0.0 -25.2792  -7.4961   True
     Batken_Kyrgyz Jalal-Abad_Russian -11.3477 0.0103  -21.473  -1.2224   True
     Batken_Kyrgyz   Jalal-Abad_Uzbek -23.8753    0.0 -35.0066 -12.7441   True
     Batken_Kyrgyz       Naryn_Kyrgyz  -7.3071 0.8756 -19.5515   4.9372  False
     Batken_Kyrgyz      Naryn_Russian   5.0179    1.0 -18.0375  28.0732  False
     Batken_Kyrgyz         Osh_Kyrgyz -19.7971    0.0 -28.8241   -10.77   True
     Batken_Kyrgyz        Osh_Russian -18.6115    0.0 -29.6329  -7.5902   True
     Batken_Kyrgyz          Osh_Uzbek  -7.5071  0.987 -23.1702   8.1559  False
     Batken_Kyrgyz    Osh_city_Kyrgyz  -8.3308 0.9992 -29.6903  13.0287  False
     Batken_Kyrgyz   Osh_city_Russian  -3.2208    1.0  -14.352   7.9105  False
     Batken_Kyrgyz     Osh_city_Uzbek -21.6571 0.4629 -50.2538   6.9395  False
     Batken_Kyrgyz       Talas_Kyrgyz  -5.5771  0.984 -17.0158   5.8615  False
     Batken_Kyrgyz      Talas_Russian  -2.8571    1.0 -18.5202  12.8059  False
    Batken_Russian       Batken_Tajik   8.9649 0.9977 -12.3722   30.302  False
    Batken_Russian       Batken_Uzbek  12.6746 0.4737  -4.1458   29.495  False
    Batken_Russian     Bishkek_Kyrgyz  18.8641  0.005   2.7389  34.9893   True
    Batken_Russian    Bishkek_Russian   29.203    0.0  13.6711  44.7349   True
    Batken_Russian        Chui_Kyrgyz  11.5047 0.5032  -3.9743  26.9837  False
    Batken_Russian       Chui_Russian  14.1316 0.1681  -1.8014  30.0645  False
    Batken_Russian   Issyk-Kul_Kyrgyz  10.6075 0.6976  -5.1035  26.3185  False
    Batken_Russian  Issyk-Kul_Russian  11.0066 0.8411  -6.8851  28.8983  False
    Batken_Russian  Jalal-Abad_Kyrgyz   -0.899    1.0 -15.9122  14.1143  False
    Batken_Russian Jalal-Abad_Russian    4.141    1.0 -11.6342  19.9163  False
    Batken_Russian   Jalal-Abad_Uzbek  -8.3866  0.973 -24.8256   8.0524  False
    Batken_Russian       Naryn_Kyrgyz   8.1816 0.9882  -9.0307  25.3938  False
    Batken_Russian      Naryn_Russian  20.5066   0.38  -5.5297  46.5428  False
    Batken_Russian         Osh_Kyrgyz  -4.3084    1.0 -19.4022  10.7855  False
    Batken_Russian        Osh_Russian  -3.1228    1.0 -19.4876   13.242  False
    Batken_Russian          Osh_Uzbek   7.9816 0.9987  -11.809  27.7722  False
    Batken_Russian    Osh_city_Kyrgyz   7.1579    1.0 -17.3893  31.7051  False
    Batken_Russian   Osh_city_Russian  12.2679 0.4945  -4.1711   28.707  False
    Batken_Russian     Osh_city_Uzbek  -6.1684    1.0 -37.2185  24.8816  False
    Batken_Russian       Talas_Kyrgyz   9.9116 0.8781  -6.7372  26.5603  False
    Batken_Russian      Talas_Russian  12.6316  0.791   -7.159  32.4222  False
      Batken_Tajik       Batken_Uzbek   3.7097    1.0 -14.6339  22.0533  False
      Batken_Tajik     Bishkek_Kyrgyz   9.8992 0.9307  -7.8091  27.6075  False
      Batken_Tajik    Bishkek_Russian  20.2381 0.0044   3.0683  37.4079   True
      Batken_Tajik        Chui_Kyrgyz   2.5398    1.0 -14.5822  19.6617  False
      Batken_Tajik       Chui_Russian   5.1667    1.0 -12.3667  22.7001  False
      Batken_Tajik   Issyk-Kul_Kyrgyz   1.6426    1.0 -15.6894  18.9745  False
      Batken_Tajik  Issyk-Kul_Russian   2.0417    1.0  -17.289  21.3723  False
      Batken_Tajik  Jalal-Abad_Kyrgyz  -9.8639 0.8861 -26.5659   6.8382  False
      Batken_Tajik Jalal-Abad_Russian  -4.8239    1.0 -22.2141  12.5663  False
      Batken_Tajik   Jalal-Abad_Uzbek -17.3515 0.0756 -35.3461    0.643  False
      Batken_Tajik       Naryn_Kyrgyz  -0.7833    1.0 -19.4869  17.9202  False
      Batken_Tajik      Naryn_Russian  11.5417 0.9971 -15.5036   38.587  False
      Batken_Tajik         Osh_Kyrgyz -13.2733 0.3704 -30.0479   3.5013  False
      Batken_Tajik        Osh_Russian -12.0877    0.7 -30.0145    5.839  False
      Batken_Tajik          Osh_Uzbek  -0.9833    1.0 -22.0838  20.1171  False
      Batken_Tajik    Osh_city_Kyrgyz   -1.807    1.0  -27.422   23.808  False
      Batken_Tajik   Osh_city_Russian    3.303    1.0 -14.6915  21.2976  False
      Batken_Tajik     Osh_city_Uzbek -15.1333 0.9885 -47.0342  16.7676  False
      Batken_Tajik       Talas_Kyrgyz   0.9467    1.0 -17.2396   19.133  False
      Batken_Tajik      Talas_Russian   3.6667    1.0 -17.4338  24.7671  False
      Batken_Uzbek     Bishkek_Kyrgyz   6.1895 0.9662  -5.6948  18.0739  False
      Batken_Uzbek    Bishkek_Russian  16.5284    0.0   5.4625  27.5943   True
      Batken_Uzbek        Chui_Kyrgyz  -1.1699    1.0 -12.1614   9.8216  False
      Batken_Uzbek       Chui_Russian    1.457    1.0 -10.1651  13.0791  False
      Batken_Uzbek   Issyk-Kul_Kyrgyz  -2.0671    1.0  -13.383   9.2488  False
      Batken_Uzbek  Issyk-Kul_Russian   -1.668    1.0  -15.857   12.521  False
      Batken_Uzbek  Jalal-Abad_Kyrgyz -13.5736 0.0005 -23.8989  -3.2483   True
      Batken_Uzbek Jalal-Abad_Russian  -8.5336 0.4889 -19.9385   2.8714  False
      Batken_Uzbek   Jalal-Abad_Uzbek -21.0612    0.0  -33.368  -8.7544   True
      Batken_Uzbek       Naryn_Kyrgyz   -4.493 0.9999  -17.815    8.829  False
      Batken_Uzbek      Naryn_Russian    7.832 0.9999 -15.8133  31.4773  False
      Batken_Uzbek         Osh_Kyrgyz -16.9829    0.0 -27.4252  -6.5407   True
      Batken_Uzbek        Osh_Russian -15.7974 0.0007 -28.0048  -3.5899   True
      Batken_Uzbek          Osh_Uzbek   -4.693    1.0 -21.2122  11.8262  False
      Batken_Uzbek    Osh_city_Kyrgyz  -5.5167    1.0 -27.5117  16.4783  False
      Batken_Uzbek   Osh_city_Russian  -0.4066    1.0 -12.7134  11.9001  False
      Batken_Uzbek     Osh_city_Uzbek  -18.843 0.7676 -47.9174  10.2314  False
      Batken_Uzbek       Talas_Kyrgyz   -2.763    1.0 -15.3485   9.8225  False
      Batken_Uzbek      Talas_Russian   -0.043    1.0 -16.5622  16.4762  False
    Bishkek_Kyrgyz    Bishkek_Russian  10.3389  0.032   0.3614  20.3164   True
    Bishkek_Kyrgyz        Chui_Kyrgyz  -7.3595 0.5017 -17.2544   2.5355  False
    Bishkek_Kyrgyz       Chui_Russian  -4.7326 0.9946 -15.3236   5.8585  False
    Bishkek_Kyrgyz   Issyk-Kul_Kyrgyz  -8.2567  0.335 -18.5107   1.9974  False
    Bishkek_Kyrgyz  Issyk-Kul_Russian  -7.8576 0.8899 -21.2151      5.5  False
    Bishkek_Kyrgyz  Jalal-Abad_Kyrgyz -19.7631    0.0 -28.9123 -10.6139   True
    Bishkek_Kyrgyz Jalal-Abad_Russian -14.7231 0.0001 -25.0754  -4.3708   True
    Bishkek_Kyrgyz   Jalal-Abad_Uzbek -27.2507    0.0 -38.5889 -15.9126   True
    Bishkek_Kyrgyz       Naryn_Kyrgyz -10.6826 0.2164 -23.1153   1.7502  False
    Bishkek_Kyrgyz      Naryn_Russian   1.6424    1.0 -21.5135  24.7984  False
    Bishkek_Kyrgyz         Osh_Kyrgyz -23.1725    0.0 -32.4535 -13.8915   True
    Bishkek_Kyrgyz        Osh_Russian -21.9869    0.0 -33.2172 -10.7567   True
    Bishkek_Kyrgyz          Osh_Uzbek -10.8826 0.6615 -26.6933   4.9282  False
    Bishkek_Kyrgyz    Osh_city_Kyrgyz -11.7062 0.9456 -33.1743   9.7618  False
    Bishkek_Kyrgyz   Osh_city_Russian  -6.5962    0.9 -17.9343   4.7419  False
    Bishkek_Kyrgyz     Osh_city_Uzbek -25.0326 0.1915 -53.7104   3.6453  False
    Bishkek_Kyrgyz       Talas_Kyrgyz  -8.9526   0.43 -20.5927   2.6875  False
    Bishkek_Kyrgyz      Talas_Russian  -6.2326 0.9991 -22.0433   9.5782  False
   Bishkek_Russian        Chui_Kyrgyz -17.6983    0.0 -26.5937   -8.803   True
   Bishkek_Russian       Chui_Russian -15.0714    0.0 -24.7351  -5.4077   True
   Bishkek_Russian   Issyk-Kul_Kyrgyz -18.5955    0.0 -27.8887  -9.3024   True
   Bishkek_Russian  Issyk-Kul_Russian -18.1964    0.0 -30.8314  -5.5615   True
   Bishkek_Russian  Jalal-Abad_Kyrgyz  -30.102    0.0 -38.1596 -22.0443   True
   Bishkek_Russian Jalal-Abad_Russian  -25.062    0.0 -34.4634 -15.6606   True
   Bishkek_Russian   Jalal-Abad_Uzbek -37.5896    0.0 -48.0667 -27.1125   True
   Bishkek_Russian       Naryn_Kyrgyz -21.0214    0.0 -32.6743  -9.3685   True
   Bishkek_Russian      Naryn_Russian  -8.6964 0.9994 -31.4432  14.0503  False
   Bishkek_Russian         Osh_Kyrgyz -33.5114    0.0 -41.7183 -25.3044   True
   Bishkek_Russian        Osh_Russian -32.3258    0.0 -42.6861 -21.9655   True
   Bishkek_Russian          Osh_Uzbek -21.2214 0.0001 -36.4266  -6.0163   True
   Bishkek_Russian    Osh_city_Kyrgyz -22.0451 0.0274 -43.0712  -1.0191   True
   Bishkek_Russian   Osh_city_Russian -16.9351    0.0 -27.4122  -6.4579   True
   Bishkek_Russian     Osh_city_Uzbek -35.3714 0.0015 -63.7199   -7.023   True
   Bishkek_Russian       Talas_Kyrgyz -19.2914    0.0 -30.0946  -8.4882   True
   Bishkek_Russian      Talas_Russian -16.5714 0.0158 -31.7766  -1.3663   True
       Chui_Kyrgyz       Chui_Russian   2.6269    1.0  -6.9516  12.2054  False
       Chui_Kyrgyz   Issyk-Kul_Kyrgyz  -0.8972    1.0 -10.1017   8.3073  False
       Chui_Kyrgyz  Issyk-Kul_Russian  -0.4981    1.0  -13.068  12.0718  False
       Chui_Kyrgyz  Jalal-Abad_Kyrgyz -12.4036    0.0 -20.3589  -4.4484   True
       Chui_Kyrgyz Jalal-Abad_Russian  -7.3637 0.3721 -16.6775   1.9501  False
       Chui_Kyrgyz   Jalal-Abad_Uzbek -19.8913    0.0 -30.2898  -9.4927   True
       Chui_Kyrgyz       Naryn_Kyrgyz  -3.3231    1.0 -14.9054   8.2592  False
       Chui_Kyrgyz      Naryn_Russian   9.0019  0.999 -13.7088  31.7126  False
       Chui_Kyrgyz         Osh_Kyrgyz  -15.813    0.0 -23.9194  -7.7066   True
       Chui_Kyrgyz        Osh_Russian -14.6275 0.0001 -24.9083  -4.3466   True
       Chui_Kyrgyz          Osh_Uzbek  -3.5231    1.0 -18.6742   11.628  False
       Chui_Kyrgyz    Osh_city_Kyrgyz  -4.3468    1.0 -25.3338  16.6402  False
       Chui_Kyrgyz   Osh_city_Russian   0.7633    1.0  -9.6353  11.1618  False
       Chui_Kyrgyz     Osh_city_Uzbek -17.6731 0.8227 -45.9926  10.6464  False
       Chui_Kyrgyz       Talas_Kyrgyz  -1.5931    1.0 -12.3201   9.1339  False
       Chui_Kyrgyz      Talas_Russian   1.1269    1.0 -14.0242   16.278  False
      Chui_Russian   Issyk-Kul_Kyrgyz  -3.5241 0.9998 -13.4731   6.4249  False
      Chui_Russian  Issyk-Kul_Russian   -3.125    1.0 -16.2498   9.9998  False
      Chui_Russian  Jalal-Abad_Kyrgyz -15.0305    0.0 -23.8365  -6.2246   True
      Chui_Russian Jalal-Abad_Russian  -9.9906 0.0537 -20.0408   0.0596  False
      Chui_Russian   Jalal-Abad_Uzbek -22.5182    0.0 -33.5812 -11.4552   True
      Chui_Russian       Naryn_Kyrgyz    -5.95 0.9837 -18.1324   6.2324  False
      Chui_Russian      Naryn_Russian    6.375    1.0 -16.6475  29.3975  False
      Chui_Russian         Osh_Kyrgyz -18.4399    0.0 -27.3827  -9.4971   True
      Chui_Russian        Osh_Russian -17.2544    0.0 -28.2068   -6.302   True
      Chui_Russian          Osh_Uzbek    -6.15 0.9991 -21.7646   9.4646  False
      Chui_Russian    Osh_city_Kyrgyz  -6.9737    1.0 -28.2977  14.3504  False
      Chui_Russian   Osh_city_Russian  -1.8636    1.0 -12.9266   9.1994  False
      Chui_Russian     Osh_city_Uzbek    -20.3 0.5981 -48.8702   8.2702  False
      Chui_Russian       Talas_Kyrgyz    -4.22 0.9996 -15.5923   7.1523  False
      Chui_Russian      Talas_Russian     -1.5    1.0 -17.1146  14.1146  False
  Issyk-Kul_Kyrgyz  Issyk-Kul_Russian   0.3991    1.0 -12.4554  13.2535  False
  Issyk-Kul_Kyrgyz  Jalal-Abad_Kyrgyz -11.5065 0.0002 -19.9041  -3.1088   True
  Issyk-Kul_Kyrgyz Jalal-Abad_Russian  -6.4665 0.7194 -16.1609    3.228  False
  Issyk-Kul_Kyrgyz   Jalal-Abad_Uzbek -18.9941    0.0 -29.7349  -8.2533   True
  Issyk-Kul_Kyrgyz       Naryn_Kyrgyz  -2.4259    1.0 -14.3165   9.4647  False
  Issyk-Kul_Kyrgyz      Naryn_Russian   9.8991 0.9965 -12.9703  32.7685  False
  Issyk-Kul_Kyrgyz         Osh_Kyrgyz -14.9158    0.0 -23.4569  -6.3748   True
  Issyk-Kul_Kyrgyz        Osh_Russian -13.7303 0.0007 -24.3572  -3.1034   True
  Issyk-Kul_Kyrgyz          Osh_Uzbek  -2.6259    1.0 -18.0139  12.7621  False
  Issyk-Kul_Kyrgyz    Osh_city_Kyrgyz  -3.4496    1.0 -24.6083  17.7091  False
  Issyk-Kul_Kyrgyz   Osh_city_Russian   1.6605    1.0  -9.0804  12.4013  False
  Issyk-Kul_Kyrgyz     Osh_city_Uzbek -16.7759 0.8875 -45.2229  11.6711  False
  Issyk-Kul_Kyrgyz       Talas_Kyrgyz  -0.6959    1.0  -11.755  10.3632  False
  Issyk-Kul_Kyrgyz      Talas_Russian   2.0241    1.0 -13.3639  17.4121  False
 Issyk-Kul_Russian  Jalal-Abad_Kyrgyz -11.9055 0.0544 -23.8972   0.0861  False
 Issyk-Kul_Russian Jalal-Abad_Russian  -6.8656 0.9586 -19.7985   6.0674  False
 Issyk-Kul_Russian   Jalal-Abad_Uzbek -19.3932 0.0001  -33.128  -5.6584   True
 Issyk-Kul_Russian       Naryn_Kyrgyz   -2.825    1.0 -17.4764  11.8264  False
 Issyk-Kul_Russian      Naryn_Russian      9.5 0.9992  -14.919   33.919  False
 Issyk-Kul_Russian         Osh_Kyrgyz -15.3149 0.0011 -27.4074  -3.2225   True
 Issyk-Kul_Russian        Osh_Russian -14.1294 0.0323 -27.7753  -0.4835   True
 Issyk-Kul_Russian          Osh_Uzbek   -3.025    1.0 -20.6338  14.5838  False
 Issyk-Kul_Russian    Osh_city_Kyrgyz  -3.8487    1.0 -26.6734  18.9761  False
 Issyk-Kul_Russian   Osh_city_Russian   1.2614    1.0 -12.4734  14.9962  False
 Issyk-Kul_Russian     Osh_city_Uzbek  -17.175 0.9054 -46.8821  12.5321  False
 Issyk-Kul_Russian       Talas_Kyrgyz   -1.095    1.0 -15.0801  12.8901  False
 Issyk-Kul_Russian      Talas_Russian    1.625    1.0 -15.9838  19.2338  False
 Jalal-Abad_Kyrgyz Jalal-Abad_Russian     5.04 0.8842  -3.4774  13.5573  False
 Jalal-Abad_Kyrgyz   Jalal-Abad_Uzbek  -7.4876 0.4204 -17.1793    2.204  False
 Jalal-Abad_Kyrgyz       Naryn_Kyrgyz   9.0805 0.2786  -1.8715  20.0326  False
 Jalal-Abad_Kyrgyz      Naryn_Russian  21.4055 0.0831  -0.9903  43.8014  False
 Jalal-Abad_Kyrgyz         Osh_Kyrgyz  -3.4094 0.9883 -10.5866   3.7678  False
 Jalal-Abad_Kyrgyz        Osh_Russian  -2.2238    1.0 -11.7891   7.3414  False
 Jalal-Abad_Kyrgyz          Osh_Uzbek   8.8805 0.8605  -5.7944  23.5555  False
 Jalal-Abad_Kyrgyz    Osh_city_Kyrgyz   8.0569 0.9992  -12.589  28.7028  False
 Jalal-Abad_Kyrgyz   Osh_city_Russian  13.1669 0.0002   3.4752  22.8586   True
 Jalal-Abad_Kyrgyz     Osh_city_Uzbek  -5.2695    1.0 -33.3371  22.7982  False
 Jalal-Abad_Kyrgyz       Talas_Kyrgyz  10.8105  0.019   0.7673  20.8538   True
 Jalal-Abad_Kyrgyz      Talas_Russian  13.5305  0.119  -1.1444  28.2055  False
Jalal-Abad_Russian   Jalal-Abad_Uzbek -12.5276 0.0061 -23.3623   -1.693   True
Jalal-Abad_Russian       Naryn_Kyrgyz   4.0406 0.9999  -7.9348  16.0159  False
Jalal-Abad_Russian      Naryn_Russian  16.3656 0.5874  -6.5481  39.2792  False
Jalal-Abad_Russian         Osh_Kyrgyz  -8.4494 0.0663 -17.1081   0.2093  False
Jalal-Abad_Russian        Osh_Russian  -7.2638 0.6913 -17.9855   3.4579  False
Jalal-Abad_Russian          Osh_Uzbek   3.8406    1.0 -11.6131  19.2942  False
Jalal-Abad_Russian    Osh_city_Kyrgyz   3.0169    1.0 -18.1896  24.2233  False
Jalal-Abad_Russian   Osh_city_Russian   8.1269 0.4836  -2.7077  18.9616  False
Jalal-Abad_Russian     Osh_city_Uzbek -10.3094 0.9998  -38.792  18.1731  False
Jalal-Abad_Russian       Talas_Kyrgyz   5.7706 0.9684  -5.3797  16.9208  False
Jalal-Abad_Russian      Talas_Russian   8.4906 0.9414  -6.9631  23.9442  False
  Jalal-Abad_Uzbek       Naryn_Kyrgyz  16.5682 0.0007    3.731  29.4053   True
  Jalal-Abad_Uzbek      Naryn_Russian  28.8932 0.0018   5.5176  52.2688   True
  Jalal-Abad_Uzbek         Osh_Kyrgyz   4.0783  0.998  -5.7379  13.8944  False
  Jalal-Abad_Uzbek        Osh_Russian   5.2638  0.994  -6.4126  16.9402  False
  Jalal-Abad_Uzbek          Osh_Uzbek  16.3682 0.0419   0.2375  32.4989   True
  Jalal-Abad_Uzbek    Osh_city_Kyrgyz  15.5445 0.5817  -6.1603  37.2493  False
  Jalal-Abad_Uzbek   Osh_city_Russian  20.6545    0.0   8.8744  32.4347   True
  Jalal-Abad_Uzbek     Osh_city_Uzbek   2.2182    1.0 -26.6373  31.0736  False
  Jalal-Abad_Uzbek       Talas_Kyrgyz  18.2982    0.0   6.2271  30.3693   True
  Jalal-Abad_Uzbek      Talas_Russian  21.0182 0.0006   4.8875  37.1489   True
      Naryn_Kyrgyz      Naryn_Russian   12.325   0.97 -11.6007  36.2507  False
      Naryn_Kyrgyz         Osh_Kyrgyz -12.4899 0.0091 -23.5523  -1.4275   True
      Naryn_Kyrgyz        Osh_Russian -11.3044 0.1677 -24.0464   1.4376  False
      Naryn_Kyrgyz          Osh_Uzbek     -0.2    1.0  -17.118   16.718  False
      Naryn_Kyrgyz    Osh_city_Kyrgyz  -1.0237    1.0 -23.3198  21.2724  False
      Naryn_Kyrgyz   Osh_city_Russian   4.0864    1.0  -8.7508  16.9235  False
      Naryn_Kyrgyz     Osh_city_Uzbek   -14.35 0.9831 -43.6529  14.9529  False
      Naryn_Kyrgyz       Talas_Kyrgyz     1.73    1.0 -11.3746  14.8346  False
      Naryn_Kyrgyz      Talas_Russian     4.45    1.0  -12.468   21.368  False
     Naryn_Russian         Osh_Kyrgyz -24.8149 0.0128 -47.2649  -2.3649   True
     Naryn_Russian        Osh_Russian -23.6294 0.0427 -46.9528  -0.3059   True
     Naryn_Russian          Osh_Uzbek  -12.525 0.9851 -38.3677  13.3177  False
     Naryn_Russian    Osh_city_Kyrgyz -13.3487 0.9941 -42.9923  16.2949  False
     Naryn_Russian   Osh_city_Russian  -8.2386 0.9998 -31.6142   15.137  False
     Naryn_Russian     Osh_city_Uzbek  -26.675 0.4627 -61.8927   8.5427  False
     Naryn_Russian       Talas_Kyrgyz  -10.595  0.994 -34.1185  12.9285  False
     Naryn_Russian      Talas_Russian   -7.875    1.0 -33.7177  17.9677  False
        Osh_Kyrgyz        Osh_Russian   1.1855    1.0  -8.5058  10.8769  False
        Osh_Kyrgyz          Osh_Uzbek  12.2899 0.2705  -2.4675  27.0474  False
        Osh_Kyrgyz    Osh_city_Kyrgyz  11.4662 0.9366  -9.2384  32.1709  False
        Osh_Kyrgyz   Osh_city_Russian  16.5763    0.0   6.7602  26.3924   True
        Osh_Kyrgyz     Osh_city_Uzbek  -1.8601    1.0 -29.9709  26.2508  False
        Osh_Kyrgyz       Talas_Kyrgyz  14.2199 0.0001   4.0565  24.3833   True
        Osh_Kyrgyz      Talas_Russian  16.9399 0.0069   2.1825  31.6974   True
       Osh_Russian          Osh_Uzbek  11.1044 0.6521  -4.9507  27.1594  False
       Osh_Russian    Osh_city_Kyrgyz  10.2807 0.9883 -11.3679  31.9293  False
       Osh_Russian   Osh_city_Russian  15.3907 0.0005   3.7144  27.0671   True
       Osh_Russian     Osh_city_Uzbek  -3.0456    1.0 -31.8589  25.7676  False
       Osh_Russian       Talas_Kyrgyz  13.0344  0.016   1.0646  25.0042   True
       Osh_Russian      Talas_Russian  15.7544 0.0623  -0.3007  31.8094  False
         Osh_Uzbek    Osh_city_Kyrgyz  -0.8237    1.0 -25.1655  23.5181  False
         Osh_Uzbek   Osh_city_Russian   4.2864    1.0 -11.8443  20.4171  False
         Osh_Uzbek     Osh_city_Uzbek   -14.15 0.9926 -45.0379  16.7379  False
         Osh_Uzbek       Talas_Kyrgyz     1.93    1.0 -14.4144  18.2744  False
         Osh_Uzbek      Talas_Russian     4.65    1.0 -14.8852  24.1852  False
   Osh_city_Kyrgyz   Osh_city_Russian     5.11    1.0 -16.5947  26.8148  False
   Osh_city_Kyrgyz     Osh_city_Uzbek -13.3263 0.9992 -47.4579  20.8052  False
   Osh_city_Kyrgyz       Talas_Kyrgyz   2.7537    1.0 -19.1104  24.6177  False
   Osh_city_Kyrgyz      Talas_Russian   5.4737    1.0 -18.8681  29.8155  False
  Osh_city_Russian     Osh_city_Uzbek -18.4364 0.7895 -47.2918  10.4191  False
  Osh_city_Russian       Talas_Kyrgyz  -2.3564    1.0 -14.4275   9.7147  False

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-15.4887,0.0715,-31.4691,0.4917,False
1,Batken_Kyrgyz,Batken_Tajik,-6.5238,0.9996,-24.1004,11.0527,False
2,Batken_Kyrgyz,Batken_Uzbek,-2.8141,1.0000,-14.5012,8.8730,False
3,Batken_Kyrgyz,Bishkek_Kyrgyz,3.3754,1.0000,-7.2869,14.0377,False
4,Batken_Kyrgyz,Bishkek_Russian,13.7143,0.0001,3.9725,23.4560,True
...,...,...,...,...,...,...,...
248,Osh_city_Russian,Talas_Kyrgyz,-2.3564,1.0000,-14.4275,9.7147,False
249,Osh_city_Russian,Talas_Russian,0.3636,1.0000,-15.7671,16.4943,False
250,Osh_city_Uzbek,Talas_Kyrgyz,16.0800,0.9354,-12.8954,45.0554,False
251,Osh_city_Uzbek,Talas_Russian,18.8000,0.8539,-12.0879,49.6879,False
252,Talas_Kyrgyz,Talas_Russian,2.7200,1.0000,-13.6244,19.0644,False

###List Comprehension Score Tukey Test

In [76]:
# Run Tukey's test
tukey_results = pairwise_tukeyhsd(base['list_comp_score_pcnt'], base['Region_Language'])
listcomptukey = pd.DataFrame(data=tukey_results._results_table.data[1:], columns=tukey_results._results_table.data[0])

# Print results
print(tukey_results)
listcomptukey

             Multiple Comparison of Means - Tukey HSD, FWER=0.05
==============================================================================
      group1             group2       meandiff p-adj   lower    upper   reject
------------------------------------------------------------------------------
     Batken_Kyrgyz     Batken_Russian -33.5414    0.0 -51.5349 -15.5478   True
     Batken_Kyrgyz       Batken_Tajik  29.4762    0.0   9.6854  49.2669   True
     Batken_Kyrgyz       Batken_Uzbek  37.3472    0.0  24.1878  50.5065   True
     Batken_Kyrgyz     Bishkek_Kyrgyz   7.2746  0.859  -4.7308  19.2801  False
     Batken_Kyrgyz    Bishkek_Russian  18.6614    0.0   7.6924  29.6303   True
     Batken_Kyrgyz        Chui_Kyrgyz  17.0972    0.0   6.2234  27.9709   True
     Batken_Kyrgyz       Chui_Russian -10.9683 0.0992 -22.6438   0.7073  False
     Batken_Kyrgyz   Issyk-Kul_Kyrgyz  10.9862 0.0683  -0.3015  22.2739  False
     Batken_Kyrgyz  Issyk-Kul_Russian   8.5804 0.9055  -6.2627  23.4234  False
     Batken_Kyrgyz  Jalal-Abad_Kyrgyz   4.0014 0.9989  -6.0103   14.013  False
     Batken_Kyrgyz Jalal-Abad_Russian -23.6307    0.0 -35.0315 -12.2299   True
     Batken_Kyrgyz   Jalal-Abad_Uzbek  23.5974    0.0  11.0639  36.1309   True
     Batken_Kyrgyz       Naryn_Kyrgyz   1.3929    1.0  -12.394  15.1797  False
     Batken_Kyrgyz      Naryn_Russian  15.1429 0.8977 -10.8169  41.1026  False
     Batken_Kyrgyz         Osh_Kyrgyz  -6.9243 0.6811 -17.0885     3.24  False
     Batken_Kyrgyz        Osh_Russian -39.5063    0.0  -51.916 -27.0965   True
     Batken_Kyrgyz          Osh_Uzbek  38.1429    0.0  20.5067   55.779   True
     Batken_Kyrgyz    Osh_city_Kyrgyz  21.1955 0.1772  -2.8548  45.2458  False
     Batken_Kyrgyz   Osh_city_Russian  -3.6753    1.0 -16.2088   8.8582  False
     Batken_Kyrgyz     Osh_city_Uzbek  22.1429 0.6632 -10.0563   54.342  False
     Batken_Kyrgyz       Talas_Kyrgyz   8.9429 0.6445  -3.9368  21.8225  False
     Batken_Kyrgyz      Talas_Russian -15.3571 0.1952 -32.9933    2.279  False
    Batken_Russian       Batken_Tajik  63.0175    0.0  38.9925  87.0426   True
    Batken_Russian       Batken_Uzbek  70.8885    0.0  51.9492  89.8278   True
    Batken_Russian     Bishkek_Kyrgyz   40.816    0.0  22.6594  58.9726   True
    Batken_Russian    Bishkek_Russian  52.2027    0.0  34.7142  69.6912   True
    Batken_Russian        Chui_Kyrgyz  50.6385    0.0  33.2096  68.0675   True
    Batken_Russian       Chui_Russian  22.5731 0.0012    4.633  40.5132   True
    Batken_Russian   Issyk-Kul_Kyrgyz  44.5276    0.0  26.8374  62.2177   True
    Batken_Russian  Issyk-Kul_Russian  42.1217    0.0  21.9761  62.2673   True
    Batken_Russian  Jalal-Abad_Kyrgyz  37.5427    0.0  20.6382  54.4473   True
    Batken_Russian Jalal-Abad_Russian   9.9106 0.9319  -7.8519  27.6732  False
    Batken_Russian   Jalal-Abad_Uzbek  57.1388    0.0  38.6288  75.6487   True
    Batken_Russian       Naryn_Kyrgyz  34.9342    0.0  15.5536  54.3148   True
    Batken_Russian      Naryn_Russian  48.6842    0.0   19.368  78.0004   True
    Batken_Russian         Osh_Kyrgyz  26.6171    0.0   9.6217  43.6124   True
    Batken_Russian        Osh_Russian  -5.9649    1.0 -24.3913  12.4615  False
    Batken_Russian          Osh_Uzbek  71.6842    0.0  49.4005  93.9679   True
    Batken_Russian    Osh_city_Kyrgyz  54.7368    0.0  27.0973  82.3764   True
    Batken_Russian   Osh_city_Russian   29.866    0.0  11.3561   48.376   True
    Batken_Russian     Osh_city_Uzbek  55.6842    0.0  20.7226  90.6458   True
    Batken_Russian       Talas_Kyrgyz  42.4842    0.0  23.7381  61.2303   True
    Batken_Russian      Talas_Russian  18.1842 0.3087  -4.0995  40.4679  False
      Batken_Tajik       Batken_Uzbek    7.871 0.9994 -12.7834  28.5254  False
      Batken_Tajik     Bishkek_Kyrgyz -22.2016 0.0114 -42.1406  -2.2625   True
      Batken_Tajik    Bishkek_Russian -10.8148 0.9302 -30.1475   8.5179  False
      Batken_Tajik        Chui_Kyrgyz  -12.379  0.782 -31.6579   6.8999  False
      Batken_Tajik       Chui_Russian -40.4444    0.0 -60.1866 -20.7023   True
      Batken_Tajik   Issyk-Kul_Kyrgyz   -18.49  0.091 -38.0053   1.0254  False
      Batken_Tajik  Issyk-Kul_Russian -20.8958 0.0792 -42.6617     0.87  False
      Batken_Tajik  Jalal-Abad_Kyrgyz -25.4748 0.0002 -44.2809  -6.6687   True
      Batken_Tajik Jalal-Abad_Russian -53.1069    0.0 -72.6879  -33.526   True
      Batken_Tajik   Jalal-Abad_Uzbek  -5.8788    1.0 -26.1402  14.3826  False
      Batken_Tajik       Naryn_Kyrgyz -28.0833 0.0003 -49.1431  -7.0236   True
      Batken_Tajik      Naryn_Russian -14.3333 0.9896 -44.7857   16.119  False
      Batken_Tajik         Osh_Kyrgyz -36.4005    0.0 -55.2882 -17.5127   True
      Batken_Tajik        Osh_Russian -68.9825    0.0 -89.1675 -48.7974   True
      Batken_Tajik          Osh_Uzbek   8.6667 0.9997 -15.0919  32.4253  False
      Batken_Tajik    Osh_city_Kyrgyz  -8.2807    1.0 -37.1225  20.5611  False
      Batken_Tajik   Osh_city_Russian -33.1515    0.0 -53.4129 -12.8901   True
      Batken_Tajik     Osh_city_Uzbek  -7.3333    1.0  -43.253  28.5863  False
      Batken_Tajik       Talas_Kyrgyz -20.5333 0.0484 -41.0107   -0.056   True
      Batken_Tajik      Talas_Russian -44.8333    0.0 -68.5919 -21.0747   True
      Batken_Uzbek     Bishkek_Kyrgyz -30.0725    0.0 -43.4539 -16.6911   True
      Batken_Uzbek    Bishkek_Russian -18.6858    0.0 -31.1457  -6.2259   True
      Batken_Uzbek        Chui_Kyrgyz   -20.25    0.0 -32.6262  -7.8738   True
      Batken_Uzbek       Chui_Russian -48.3154    0.0 -61.4016 -35.2292   True
      Batken_Uzbek   Issyk-Kul_Kyrgyz -26.3609    0.0 -39.1023 -13.6195   True
      Batken_Uzbek  Issyk-Kul_Russian -28.7668    0.0 -44.7433 -12.7903   True
      Batken_Uzbek  Jalal-Abad_Kyrgyz -33.3458    0.0 -44.9718 -21.7198   True
      Batken_Uzbek Jalal-Abad_Russian -60.9779    0.0 -73.8196 -48.1362   True
      Batken_Uzbek   Jalal-Abad_Uzbek -13.7498 0.0548 -27.6069   0.1074  False
      Batken_Uzbek       Naryn_Kyrgyz -35.9543    0.0 -50.9546  -20.954   True
      Batken_Uzbek      Naryn_Russian -22.2043 0.2679 -48.8284   4.4198  False
      Batken_Uzbek         Osh_Kyrgyz -44.2714    0.0 -56.0291 -32.5138   True
      Batken_Uzbek        Osh_Russian -76.8534    0.0 -90.5987 -63.1081   True
      Batken_Uzbek          Osh_Uzbek   0.7957    1.0 -17.8045  19.3959  False
      Batken_Uzbek    Osh_city_Kyrgyz -16.1517 0.7575 -40.9175   8.6142  False
      Batken_Uzbek   Osh_city_Russian -41.0225    0.0 -54.8796 -27.1654   True
      Batken_Uzbek     Osh_city_Uzbek -15.2043 0.9912 -47.9414  17.5327  False
      Batken_Uzbek       Talas_Kyrgyz -28.4043    0.0 -42.5753 -14.2333   True
      Batken_Uzbek      Talas_Russian -52.7043    0.0 -71.3045 -34.1041   True
    Bishkek_Kyrgyz    Bishkek_Russian  11.3867 0.0425   0.1523  22.6211   True
    Bishkek_Kyrgyz        Chui_Kyrgyz   9.8225 0.1767   -1.319   20.964  False
    Bishkek_Kyrgyz       Chui_Russian -18.2429    0.0 -30.1681  -6.3176   True
    Bishkek_Kyrgyz   Issyk-Kul_Kyrgyz   3.7116    1.0  -7.8342  15.2574  False
    Bishkek_Kyrgyz  Issyk-Kul_Russian   1.3057    1.0 -13.7346   16.346  False
    Bishkek_Kyrgyz  Jalal-Abad_Kyrgyz  -3.2733    1.0 -13.5751   7.0286  False
    Bishkek_Kyrgyz Jalal-Abad_Russian -30.9054    0.0 -42.5618 -19.2489   True
    Bishkek_Kyrgyz   Jalal-Abad_Uzbek  16.3228 0.0009   3.5563  29.0892   True
    Bishkek_Kyrgyz       Naryn_Kyrgyz  -5.8818 0.9977 -19.8807   8.1172  False
    Bishkek_Kyrgyz      Naryn_Russian   7.8682    1.0 -18.2048  33.9413  False
    Bishkek_Kyrgyz         Osh_Kyrgyz -14.1989 0.0002 -24.6491  -3.7488   True
    Bishkek_Kyrgyz        Osh_Russian -46.7809    0.0 -59.4259 -34.1359   True
    Bishkek_Kyrgyz          Osh_Uzbek  30.8682    0.0  13.0657  48.6707   True
    Bishkek_Kyrgyz    Osh_city_Kyrgyz  13.9208 0.9087 -10.2517  38.0934  False
    Bishkek_Kyrgyz   Osh_city_Russian   -10.95 0.2193 -23.7164   1.8165  False
    Bishkek_Kyrgyz     Osh_city_Uzbek  14.8682 0.9921 -17.4223  47.1587  False
    Bishkek_Kyrgyz       Talas_Kyrgyz   1.6682    1.0 -11.4382  14.7747  False
    Bishkek_Kyrgyz      Talas_Russian -22.6318  0.001 -40.4343  -4.8293   True
   Bishkek_Russian        Chui_Kyrgyz  -1.5642    1.0 -11.5802   8.4517  False
   Bishkek_Russian       Chui_Russian -29.6296    0.0 -40.5107 -18.7485   True
   Bishkek_Russian   Issyk-Kul_Kyrgyz  -7.6751 0.5314  -18.139   2.7887  False
   Bishkek_Russian  Issyk-Kul_Russian  -10.081 0.6036 -24.3076   4.1456  False
   Bishkek_Russian  Jalal-Abad_Kyrgyz   -14.66    0.0 -23.7327  -5.5873   True
   Bishkek_Russian Jalal-Abad_Russian -42.2921    0.0 -52.8779 -31.7063   True
   Bishkek_Russian   Jalal-Abad_Uzbek    4.936 0.9978   -6.861   16.733  False
   Bishkek_Russian       Naryn_Kyrgyz -17.2685 0.0005 -30.3894  -4.1476   True
   Bishkek_Russian      Naryn_Russian  -3.5185    1.0 -29.1308  22.0938  False
   Bishkek_Russian         Osh_Kyrgyz -25.5857    0.0 -34.8265 -16.3449   True
   Bishkek_Russian        Osh_Russian -58.1676    0.0 -69.8331 -46.5022   True
   Bishkek_Russian          Osh_Uzbek  19.4815  0.008   2.3609  36.6021   True
   Bishkek_Russian    Osh_city_Kyrgyz   2.5341    1.0 -21.1407  26.2089  False
   Bishkek_Russian   Osh_city_Russian -22.3367    0.0 -34.1337 -10.5397   True
   Bishkek_Russian     Osh_city_Uzbek   3.4815    1.0 -28.4382  35.4011  False
   Bishkek_Russian       Talas_Kyrgyz  -9.7185 0.3507 -21.8826   2.4456  False
   Bishkek_Russian      Talas_Russian -34.0185    0.0 -51.1391 -16.8979   True
       Chui_Kyrgyz       Chui_Russian -28.0654    0.0 -38.8506 -17.2803   True
       Chui_Kyrgyz   Issyk-Kul_Kyrgyz  -6.1109 0.8877  -16.475   4.2531  False
       Chui_Kyrgyz  Issyk-Kul_Russian  -8.5168 0.8668 -22.6702   5.6365  False
       Chui_Kyrgyz  Jalal-Abad_Kyrgyz -13.0958    0.0 -22.0532  -4.1384   True
       Chui_Kyrgyz Jalal-Abad_Russian -40.7279    0.0  -51.215 -30.2408   True
       Chui_Kyrgyz   Jalal-Abad_Uzbek   6.5002 0.9351  -5.2083  18.2088  False
       Chui_Kyrgyz       Naryn_Kyrgyz -15.7043  0.003 -28.7457  -2.6629   True
       Chui_Kyrgyz      Naryn_Russian  -1.9543    1.0  -27.526  23.6174  False
       Chui_Kyrgyz         Osh_Kyrgyz -24.0215    0.0 -33.1491 -14.8939   True
       Chui_Kyrgyz        Osh_Russian -56.6034    0.0 -68.1794 -45.0275   True
       Chui_Kyrgyz          Osh_Uzbek  21.0457 0.0019   3.9859  38.1055   True
       Chui_Kyrgyz    Osh_city_Kyrgyz   4.0983    1.0 -19.5325  27.7292  False
       Chui_Kyrgyz   Osh_city_Russian -20.7725    0.0  -32.481   -9.064   True
       Chui_Kyrgyz     Osh_city_Uzbek   5.0457    1.0 -26.8414  36.9327  False
       Chui_Kyrgyz       Talas_Kyrgyz  -8.1543 0.6978 -20.2327    3.924  False
       Chui_Kyrgyz      Talas_Russian -32.4543    0.0 -49.5141 -15.3945   True
      Chui_Russian   Issyk-Kul_Kyrgyz  21.9545    0.0  10.7522  33.1568   True
      Chui_Russian  Issyk-Kul_Russian  19.5486 0.0004   4.7704  34.3269   True
      Chui_Russian  Jalal-Abad_Kyrgyz  14.9696    0.0   5.0543   24.885   True
      Chui_Russian Jalal-Abad_Russian -12.6625 0.0105 -23.9788  -1.3462   True
      Chui_Russian   Jalal-Abad_Uzbek  34.5657    0.0   22.109  47.0223   True
      Chui_Russian       Naryn_Kyrgyz  12.3611 0.1466  -1.3559  26.0781  False
      Chui_Russian      Naryn_Russian  26.1111 0.0458   0.1884  52.0339   True
      Chui_Russian         Osh_Kyrgyz    4.044 0.9988  -6.0254  14.1133  False
      Chui_Russian        Osh_Russian  -28.538    0.0 -40.8702 -16.2059   True
      Chui_Russian          Osh_Uzbek  49.1111    0.0  31.5294  66.6928   True
      Chui_Russian    Osh_city_Kyrgyz  32.1637 0.0003   8.1534  56.1741   True
      Chui_Russian   Osh_city_Russian   7.2929 0.8943  -5.1637  19.7496  False
      Chui_Russian     Osh_city_Uzbek  33.1111  0.035   0.9418  65.2804   True
      Chui_Russian       Talas_Kyrgyz  19.9111    0.0   7.1062   32.716   True
      Chui_Russian      Talas_Russian  -4.3889    1.0 -21.9706  13.1928  False
  Issyk-Kul_Kyrgyz  Issyk-Kul_Russian  -2.4059    1.0 -16.8797  12.0679  False
  Issyk-Kul_Kyrgyz  Jalal-Abad_Kyrgyz  -6.9849 0.5163 -16.4404   2.4707  False
  Issyk-Kul_Kyrgyz Jalal-Abad_Russian  -34.617    0.0 -45.5327 -23.7013   True
  Issyk-Kul_Kyrgyz   Jalal-Abad_Uzbek  12.6112 0.0295   0.5173  24.7051   True
  Issyk-Kul_Kyrgyz       Naryn_Kyrgyz  -9.5934 0.5807 -22.9818   3.7951  False
  Issyk-Kul_Kyrgyz      Naryn_Russian   4.1566    1.0 -21.5938   29.907  False
  Issyk-Kul_Kyrgyz         Osh_Kyrgyz -17.9105    0.0 -27.5275  -8.2935   True
  Issyk-Kul_Kyrgyz        Osh_Russian -50.4925    0.0 -62.4581 -38.5269   True
  Issyk-Kul_Kyrgyz          Osh_Uzbek  27.1566    0.0   9.8301  44.4832   True
  Issyk-Kul_Kyrgyz    Osh_city_Kyrgyz  10.2093 0.9969 -13.6149  34.0334  False
  Issyk-Kul_Kyrgyz   Osh_city_Russian -14.6616 0.0026 -26.7555  -2.5677   True
  Issyk-Kul_Kyrgyz     Osh_city_Uzbek  11.1566 0.9999 -20.8739  43.1872  False
  Issyk-Kul_Kyrgyz       Talas_Kyrgyz  -2.0434    1.0 -14.4957  10.4089  False
  Issyk-Kul_Kyrgyz      Talas_Russian -26.3434    0.0 -43.6699  -9.0168   True
 Issyk-Kul_Russian  Jalal-Abad_Kyrgyz   -4.579 0.9999 -18.0813   8.9233  False
 Issyk-Kul_Russian Jalal-Abad_Russian -32.2111    0.0 -46.7733 -17.6489   True
 Issyk-Kul_Russian   Jalal-Abad_Uzbek   15.017   0.07   -0.448  30.4821  False
 Issyk-Kul_Russian       Naryn_Kyrgyz  -7.1875 0.9962 -23.6846   9.3096  False
 Issyk-Kul_Russian      Naryn_Russian   6.5625    1.0 -20.9327  34.0577  False
 Issyk-Kul_Russian         Osh_Kyrgyz -15.5046 0.0079 -29.1205  -1.8888   True
 Issyk-Kul_Russian        Osh_Russian -48.0866    0.0 -63.4515 -32.7217   True
 Issyk-Kul_Russian          Osh_Uzbek  29.5625    0.0   9.7354  49.3896   True
 Issyk-Kul_Russian    Osh_city_Kyrgyz  12.6151 0.9827  -13.085  38.3152  False
 Issyk-Kul_Russian   Osh_city_Russian -12.2557 0.3673 -27.7207   3.2093  False
 Issyk-Kul_Russian     Osh_city_Uzbek  13.5625 0.9986 -19.8869  47.0119  False
 Issyk-Kul_Russian       Talas_Kyrgyz   0.3625    1.0 -15.3844  16.1094  False
 Issyk-Kul_Russian      Talas_Russian -23.9375 0.0028 -43.7646  -4.1104   True
 Jalal-Abad_Kyrgyz Jalal-Abad_Russian -27.6321    0.0 -37.2224 -18.0418   True
 Jalal-Abad_Kyrgyz   Jalal-Abad_Uzbek   19.596    0.0   8.6835  30.5086   True
 Jalal-Abad_Kyrgyz       Naryn_Kyrgyz  -2.6085    1.0 -14.9403   9.7233  False
 Jalal-Abad_Kyrgyz      Naryn_Russian  11.1415 0.9954 -14.0757  36.3586  False
 Jalal-Abad_Kyrgyz         Osh_Kyrgyz -10.9257 0.0002  -19.007  -2.8443   True
 Jalal-Abad_Kyrgyz        Osh_Russian -43.5076    0.0 -54.2779 -32.7374   True
 Jalal-Abad_Kyrgyz          Osh_Uzbek  34.1415    0.0  17.6178  50.6651   True
 Jalal-Abad_Kyrgyz    Osh_city_Kyrgyz  17.1941 0.5136  -6.0526  40.4409  False
 Jalal-Abad_Kyrgyz   Osh_city_Russian  -7.6767 0.6184 -18.5893   3.2359  False
 Jalal-Abad_Kyrgyz     Osh_city_Uzbek  18.1415 0.9113  -13.462  49.7449  False
 Jalal-Abad_Kyrgyz       Talas_Kyrgyz   4.9415  0.996   -6.367  16.2499  False
 Jalal-Abad_Kyrgyz      Talas_Russian -19.3585 0.0049 -35.8822  -2.8349   True
Jalal-Abad_Russian   Jalal-Abad_Uzbek  47.2281    0.0  35.0286  59.4277   True
Jalal-Abad_Russian       Naryn_Kyrgyz  25.0236    0.0  11.5396  38.5076   True
Jalal-Abad_Russian      Naryn_Russian  38.7736    0.0  12.9734  64.5738   True
Jalal-Abad_Russian         Osh_Kyrgyz  16.7064    0.0    6.957  26.4559   True
Jalal-Abad_Russian        Osh_Russian -15.8755 0.0005 -27.9479  -3.8032   True
Jalal-Abad_Russian          Osh_Uzbek  61.7736    0.0  44.3731   79.174   True
Jalal-Abad_Russian    Osh_city_Kyrgyz  44.8262    0.0  20.9483  68.7042   True
Jalal-Abad_Russian   Osh_city_Russian  19.9554    0.0   7.7559  32.1549   True
Jalal-Abad_Russian     Osh_city_Uzbek  45.7736 0.0001   13.703  77.8442   True
Jalal-Abad_Russian       Talas_Kyrgyz  32.5736    0.0  20.0187  45.1285   True
Jalal-Abad_Russian      Talas_Russian   8.2736 0.9882  -9.1269   25.674  False
  Jalal-Abad_Uzbek       Naryn_Kyrgyz -22.2045    0.0 -36.6589  -7.7502   True
  Jalal-Abad_Uzbek      Naryn_Russian  -8.4545    1.0 -34.7749  17.8658  False
  Jalal-Abad_Uzbek         Osh_Kyrgyz -30.5217    0.0 -41.5744  -19.469   True
  Jalal-Abad_Uzbek        Osh_Russian -63.1037    0.0  -76.251 -49.9563   True
  Jalal-Abad_Uzbek          Osh_Uzbek  14.5455 0.3459  -3.6173  32.7082  False
  Jalal-Abad_Uzbek    Osh_city_Kyrgyz  -2.4019    1.0  -26.841  22.0371  False
  Jalal-Abad_Uzbek   Osh_city_Russian -27.2727    0.0 -40.5369 -14.0085   True
  Jalal-Abad_Uzbek     Osh_city_Uzbek  -1.4545    1.0 -33.9451   31.036  False
  Jalal-Abad_Uzbek       Talas_Kyrgyz -14.6545 0.0185 -28.2463  -1.0628   True
  Jalal-Abad_Uzbek      Talas_Russian -38.9545    0.0 -57.1173 -20.7918   True
      Naryn_Kyrgyz      Naryn_Russian    13.75 0.9729 -13.1897  40.6897  False
      Naryn_Kyrgyz         Osh_Kyrgyz  -8.3171 0.7176 -20.7731   4.1388  False
      Naryn_Kyrgyz        Osh_Russian -40.8991    0.0 -55.2463  -26.552   True
      Naryn_Kyrgyz          Osh_Uzbek    36.75    0.0  17.7007  55.7993   True
      Naryn_Kyrgyz    Osh_city_Kyrgyz  19.8026 0.3769  -5.3023  44.9075  False
      Naryn_Kyrgyz   Osh_city_Russian  -5.0682 0.9999 -19.5225   9.3861  False
      Naryn_Kyrgyz     Osh_city_Uzbek    20.75 0.8122 -12.2443  53.7443  False
      Naryn_Kyrgyz       Talas_Kyrgyz     7.55 0.9721  -7.2055  22.3055  False
      Naryn_Kyrgyz      Talas_Russian   -16.75 0.1805 -35.7993   2.2993  False
     Naryn_Russian         Osh_Kyrgyz -22.0671 0.1913 -47.3453    3.211  False
     Naryn_Russian        Osh_Russian -54.6491    0.0 -80.9108 -28.3875   True
     Naryn_Russian          Osh_Uzbek     23.0 0.3726  -6.0982  52.0982  False
     Naryn_Russian    Osh_city_Kyrgyz   6.0526    1.0 -27.3253  39.4306  False
     Naryn_Russian   Osh_city_Russian -18.8182 0.5852 -45.1385   7.5021  False
     Naryn_Russian     Osh_city_Uzbek      7.0    1.0 -32.6542  46.6542  False
     Naryn_Russian       Talas_Kyrgyz     -6.2    1.0 -32.6869  20.2869  False
     Naryn_Russian      Talas_Russian    -30.5 0.0275 -59.5982  -1.4018   True
        Osh_Kyrgyz        Osh_Russian  -32.582    0.0 -43.4942 -21.6698   True
        Osh_Kyrgyz          Osh_Uzbek  45.0671    0.0  28.4506  61.6837   True
        Osh_Kyrgyz    Osh_city_Kyrgyz  28.1198 0.0029   4.8069  51.4326   True
        Osh_Kyrgyz   Osh_city_Russian    3.249    1.0  -7.8038  14.3017  False
        Osh_Kyrgyz     Osh_city_Uzbek  29.0671 0.1235   -2.585  60.7193  False
        Osh_Kyrgyz       Talas_Kyrgyz  15.8671 0.0001   4.4234  27.3109   True
        Osh_Kyrgyz      Talas_Russian  -8.4329 0.9746 -25.0494   8.1837  False
       Osh_Russian          Osh_Uzbek  77.6491    0.0  59.5715  95.7267   True
       Osh_Russian    Osh_city_Kyrgyz  60.7018    0.0  36.3259  85.0776   True
       Osh_Russian   Osh_city_Russian  35.8309    0.0  22.6836  48.9783   True
       Osh_Russian     Osh_city_Uzbek  61.6491    0.0  29.2061  94.0921   True
       Osh_Russian       Talas_Kyrgyz  48.4491    0.0  34.9714  61.9269   True
       Osh_Russian      Talas_Russian  24.1491 0.0003   6.0715  42.2267   True
         Osh_Uzbek    Osh_city_Kyrgyz -16.9474 0.8347 -44.3556  10.4609  False
         Osh_Uzbek   Osh_city_Russian -41.8182    0.0 -59.9809 -23.6554   True
         Osh_Uzbek     Osh_city_Uzbek    -16.0 0.9922  -50.779   18.779  False
         Osh_Uzbek       Talas_Kyrgyz    -29.2    0.0 -47.6033 -10.7967   True
         Osh_Uzbek      Talas_Russian    -53.5    0.0 -75.4962 -31.5038   True
   Osh_city_Kyrgyz   Osh_city_Russian -24.8708 0.0404 -49.3099  -0.4318   True
   Osh_city_Kyrgyz     Osh_city_Uzbek   0.9474    1.0 -37.4839  39.3786  False
   Osh_city_Kyrgyz       Talas_Kyrgyz -12.2526 0.9796  -36.871  12.3657  False
   Osh_city_Kyrgyz      Talas_Russian -36.5526 0.0003 -63.9609  -9.1444   True
  Osh_city_Russian     Osh_city_Uzbek  25.8182 0.3617  -6.6723  58.3087  False
  Osh_city_Russian       Talas_Kyrgyz  12.6182 0.1114  -0.9736  26.2099  False

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-33.5414,0.0000,-51.5349,-15.5478,True
1,Batken_Kyrgyz,Batken_Tajik,29.4762,0.0000,9.6854,49.2669,True
2,Batken_Kyrgyz,Batken_Uzbek,37.3472,0.0000,24.1878,50.5065,True
3,Batken_Kyrgyz,Bishkek_Kyrgyz,7.2746,0.8590,-4.7308,19.2801,False
4,Batken_Kyrgyz,Bishkek_Russian,18.6614,0.0000,7.6924,29.6303,True
...,...,...,...,...,...,...,...
248,Osh_city_Russian,Talas_Kyrgyz,12.6182,0.1114,-0.9736,26.2099,False
249,Osh_city_Russian,Talas_Russian,-11.6818,0.7794,-29.8446,6.4809,False
250,Osh_city_Uzbek,Talas_Kyrgyz,-13.2000,0.9986,-45.8256,19.4256,False
251,Osh_city_Uzbek,Talas_Russian,-37.5000,0.0185,-72.2790,-2.7210,True
252,Talas_Kyrgyz,Talas_Russian,-24.3000,0.0004,-42.7033,-5.8967,True

##Tukey Analysis

The hypothesis was that Russian would, by and large, outperform the other languages, especially in Bishkek.

For that reason, all significant differences in any pairing with "Russian" and "Bishkek" will be reviewed.

###Original sample count by region and language, and pivot table with means by subtask

In [77]:
baselinecount = base.groupby(by=['region','language']).size().rename('count')
baselinecount
regethnics

region      language
Batken      Kyrgyz      140
            Russian      38
            Tajik        30
            Uzbek        93
Bishkek     Kyrgyz      129
            Russian     189
Chui        Kyrgyz      197
            Russian     144
Issyk-Kul   Kyrgyz      166
            Russian      64
Jalal-Abad  Kyrgyz      311
            Russian     159
            Uzbek       110
Naryn       Kyrgyz       80
            Russian      16
Osh         Kyrgyz      283
            Russian     114
            Uzbek        40
Osh_city    Kyrgyz       19
            Russian     110
            Uzbek        10
Talas       Kyrgyz      100
            Russian      40
Name: count, dtype: int64

,Ethnicity,Total Population,Batken,Jalal-Abad,Issyk-Kul,Naryn,Osh,Talas,Chui,Bishkek,Osh city
0,Sum population,"7,037,590","570,898","1,311,007","538,384","308,348","1,460,425","273,509","1,068,702","1,145,044","361,273"
2,Kyrgyz,"5,470,806","451,422","967,355","492,452","307,095","1,003,764","260,038","798,347","975,128","215,205"
3,Russians,"277,646","2,021","5,062","27,424",88,"1,254","3,257","124,640","110,439","3,461"
4,Uzbeks,"995,454","78,314","321,461","3,463",291,"421,519","1,006","17,480","15,899","136,021"
11,Tajiks,"60,752","36,921","7,153",213,23,"8,626",53,"5,208","1,743",812

In [78]:
baselinemean = base.pivot_table(index=
 ['region', 'language'],
 values=[
     'oral_read_score_pcnt',
     'read_comp_score_pcnt',
     'word_score_pcnt',
     'invent_word_score_pcnt',
     'list_comp_score_pcnt'],
aggfunc='mean')
baselinemean.round(2)

                     invent_word_score_pcnt  list_comp_score_pcnt  \
region     language
Batken     Kyrgyz                     62.86                 59.86
           Russian                    47.37                 26.32
           Tajik                      56.33                 89.33
           Uzbek                      60.04                 97.20
Bishkek    Kyrgyz                     66.23                 67.13
           Russian                    76.57                 78.52
Chui       Kyrgyz                     58.87                 76.95
           Russian                    61.50                 48.89
Issyk-Kul  Kyrgyz                     57.98                 70.84
           Russian                    58.38                 68.44
Jalal-Abad Kyrgyz                     46.47                 63.86
           Russian                    51.51                 36.23
           Uzbek                      38.98                 83.45
Naryn      Kyrgyz                     55.55                 61.25
           Russian                    67.88                 75.00
Osh        Kyrgyz                     43.06                 52.93
           Russian                    44.25                 20.35
           Uzbek                      55.35                 98.00
Osh_city   Kyrgyz                     54.53                 81.05
           Russian                    59.64                 56.18
           Uzbek                      41.20                 82.00
Talas      Kyrgyz                     57.28                 68.80
           Russian                    60.00                 44.50

                     oral_read_score_pcnt  read_comp_score_pcnt  \
region     language
Batken     Kyrgyz                   78.71                 64.14
           Russian                  54.21                 27.37
           Tajik                    65.70                 41.33
           Uzbek                    83.20                 82.80
Bishkek    Kyrgyz                   78.66                 63.41
           Russian                  90.30                 79.89
Chui       Kyrgyz                   71.76                 58.88
           Russian                  72.76                 46.11
Issyk-Kul  Kyrgyz                   76.13                 59.64
           Russian                  70.05                 58.75
Jalal-Abad Kyrgyz                   58.68                 45.72
           Russian                  61.77                 34.72
           Uzbek                    46.75                 40.00
Naryn      Kyrgyz                   70.55                 56.50
           Russian                  83.12                 60.00
Osh        Kyrgyz                   54.58                 37.95
           Russian                  48.84                 18.95
           Uzbek                    70.62                 66.00
Osh_city   Kyrgyz                   69.84                 61.05
           Russian                  71.86                 46.36
           Uzbek                    45.60                 46.00
Talas      Kyrgyz                   74.49                 56.00
           Russian                  73.95                 49.00

                     word_score_pcnt
region     language
Batken     Kyrgyz              54.16
           Russian             37.34
           Tajik               72.23
           Uzbek               87.72
Bishkek    Kyrgyz              57.89
           Russian             65.68
Chui       Kyrgyz              78.37
           Russian             48.86
Issyk-Kul  Kyrgyz              54.92
           Russian             56.52
Jalal-Abad Kyrgyz              60.85
           Russian             47.72
           Uzbek               61.69
Naryn      Kyrgyz              62.06
           Russian             70.81
Osh        Kyrgyz              48.19
           Russian             33.39
           Uzbek               88.30
Osh_city   Kyrgyz              78.05
           Russian             55.32
           Uzbek               55.10
Talas      Kyrgyz              64.80
           Russian             53.30

###Tukey Analysis - Two Way

In [79]:
oraltukey[oraltukey['reject'] == True]

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-24.5038,0.0002,-42.4541,-6.5534,True
4,Batken_Kyrgyz,Bishkek_Russian,11.5873,0.0239,0.6447,22.5299,True
9,Batken_Kyrgyz,Jalal-Abad_Kyrgyz,-20.0358,0.0000,-30.0235,-10.0482,True
10,Batken_Kyrgyz,Jalal-Abad_Russian,-16.9407,0.0000,-28.3141,-5.5673,True
11,Batken_Kyrgyz,Jalal-Abad_Uzbek,-31.9597,0.0000,-44.4631,-19.4564,True
...,...,...,...,...,...,...,...
231,Osh_Kyrgyz,Talas_Russian,19.3670,0.0051,2.7903,35.9436,True
232,Osh_Russian,Osh_Uzbek,21.7829,0.0028,3.7487,39.8171,True
234,Osh_Russian,Osh_city_Russian,23.0215,0.0000,9.9058,36.1373,True
236,Osh_Russian,Talas_Kyrgyz,25.6479,0.0000,12.2025,39.0933,True
237,Osh_Russian,Talas_Russian,25.1079,0.0001,7.0737,43.1421,True

In [80]:
readcomptukey[readcomptukey['reject'] == True]

,group1,group2,meandiff,p-adj,lower,upper,reject
0,Batken_Kyrgyz,Batken_Russian,-36.7744,0.0000,-57.1362,-16.4127,True
1,Batken_Kyrgyz,Batken_Tajik,-22.8095,0.0400,-45.2050,-0.4141,True
2,Batken_Kyrgyz,Batken_Uzbek,18.6528,0.0014,3.7615,33.5441,True
4,Batken_Kyrgyz,Bishkek_Russian,15.7513,0.0010,3.3387,28.1639,True
6,Batken_Kyrgyz,Chui_Russian,-18.0317,0.0002,-31.2439,-4.8196,True
...,...,...,...,...,...,...,...
232,Osh_Russian,Osh_Uzbek,47.0526,0.0000,26.5958,67.5095,True
233,Osh_Russian,Osh_city_Kyrgyz,42.1053,0.0000,14.5213,69.6892,True
234,Osh_Russian,Osh_city_Russian,27.4163,0.0000,12.5386,42.2940,True
236,Osh_Russian,Talas_Kyrgyz,37.0526,0.0000,21.8011,52.3042,True
237,Osh_Russian,Talas_Russian,30.0526,0.0000,9.5958,50.5095,True

In [81]:
wordscoretukey[wordscoretukey['reject'] == True]

,group1,group2,meandiff,p-adj,lower,upper,reject
2,Batken_Kyrgyz,Batken_Uzbek,33.5561,0.0000,21.1899,45.9223,True
4,Batken_Kyrgyz,Bishkek_Russian,11.5183,0.0108,1.2104,21.8261,True
5,Batken_Kyrgyz,Chui_Kyrgyz,24.2063,0.0000,13.9879,34.4246,True
15,Batken_Kyrgyz,Osh_Russian,-20.7695,0.0000,-32.4313,-9.1078,True
16,Batken_Kyrgyz,Osh_Uzbek,34.1357,0.0000,17.5625,50.7089,True
...,...,...,...,...,...,...,...
237,Osh_Russian,Talas_Russian,19.9053,0.0049,2.9173,36.8932,True
239,Osh_Uzbek,Osh_city_Russian,-32.9818,0.0000,-50.0498,-15.9138,True
240,Osh_Uzbek,Osh_city_Uzbek,-33.2000,0.0413,-65.8828,-0.5172,True
241,Osh_Uzbek,Talas_Kyrgyz,-23.5000,0.0002,-40.7941,-6.2059,True
242,Osh_Uzbek,Talas_Russian,-35.0000,0.0000,-55.6704,-14.3296,True

In [82]:
inventtukey[inventtukey['reject'] == True]

,group1,group2,meandiff,p-adj,lower,upper,reject
4,Batken_Kyrgyz,Bishkek_Russian,13.7143,0.0001,3.9725,23.4560,True
9,Batken_Kyrgyz,Jalal-Abad_Kyrgyz,-16.3877,0.0000,-25.2792,-7.4961,True
10,Batken_Kyrgyz,Jalal-Abad_Russian,-11.3477,0.0103,-21.4730,-1.2224,True
11,Batken_Kyrgyz,Jalal-Abad_Uzbek,-23.8753,0.0000,-35.0066,-12.7441,True
14,Batken_Kyrgyz,Osh_Kyrgyz,-19.7971,0.0000,-28.8241,-10.7700,True
...,...,...,...,...,...,...,...
228,Osh_Kyrgyz,Osh_city_Russian,16.5763,0.0000,6.7602,26.3924,True
230,Osh_Kyrgyz,Talas_Kyrgyz,14.2199,0.0001,4.0565,24.3833,True
231,Osh_Kyrgyz,Talas_Russian,16.9399,0.0069,2.1825,31.6974,True
234,Osh_Russian,Osh_city_Russian,15.3907,0.0005,3.7144,27.0671,True
236,Osh_Russian,Talas_Kyrgyz,13.0344,0.0160,1.0646,25.0042,True

# New Section